### ISSUE TITLE
Database migration tools?

### ISSUE THREAD

**Issue by potofpie** [pynamodb/PynamoDB#1023]
Does anyone have any suggestions on some database migration tools? I have been looking around but have not seen many articles related to pynamodb and these kinds of issues. Any ideas?

**Comment by ikonst** [comment]
What kind of migration? Migrating to/away from RDBMS? Migrating from old to new data schema? Changing a field's type?

**Comment by NimishVerma** [comment]
Curious why you want to use pynamodb and not just boto3 for migrating?

**Comment by ikonst** [comment]
I generally agree with @NimishVerma's perspecctive. PynamoDB attempts to support the parts of your app that need to last, not one-off code.

I do see how e.g. Django has "migration" support, but from a quick glance it seems to deal with changing a table's schema (not applicable in NoSQL) while their "data migrations" don't really give much of a framework.

**Comment by potofpie** [comment]
Hello. Thanks for the responses. I should have been a little clearer in my OP. Below I will try to detail how we are using pynamodb.

The models we have created represent almost everything in our application (user, tenants, permissions, roles, post, comments, reactions, etc.). After developing a feature the definition might change. (ie post no longer require `topics` but they do require `audience`).  The application would now be expecting `audience` to have a value but there would be entries from before `audience` existed. These changes in a SQL would be schema changes and would necessitate some migration process. 

The current lack luster solution would be write a "one off" script to convert these these elements pre deployment  but this seems a little hacky and unreliable. It looks like there are some SQL solution like [alembic](https://alembic.sqlalchemy.org/en/latest/) for SQLAlchemy but I have not been able to find a solution for NoSQL. 

This problem could be unique to my company. Truth be told the kind of data we are storing would be better suited for a SQL database but Dynamodb is just so competitive from a cost standpoint it makes it swap for other data storage solutions.

### **Imaginary library that could exists...but should it?:**
I can imagine an automated solution that compares the changes in the models from previous version and generated some conversion script or at the very least make the developer aware they will run into issues like this.
