### ISSUE TITLE
attributes_to_get not working for pynamodb.models.Model 's get method

### ISSUE THREAD

**Issue by ananya-dev** [pynamodb/PynamoDB#1033]
I'm trying to perform the following get operation.

```python
data = Model.get(hash_key='id-value', range_key='range-value', attributes_to_get=['key3'], consistent_read=True)
item = json.loads(json_dumps(data)) # custom logic to convert data into dict object.
print(item)
```

When printing item, instead of having only 'key3' key-value pair in dict, I'm getting the other attributes as well.

**UseCase** - I want to get only the key3 key-value pair in result when performing get operation on hash_key & range_key.

**Reference** - aws dynamodb get-item --table-name table --key '{"id": {"S": "id-value"}, "range_key_id": {"S": "range-value"}}' --projection-expression "key3" --endpoint-url http://localhost:8000 . This is working as expected on aws-cli. I wanted similar the similar results via pynamodb as well.

Kindly tell/suggest ways how to fix this. Thanks in advance!!

**Comment by ikonst** [comment]
Where does `json_dumps` comes from? You never defined that function.

I've just tried using `Model.get(..., attributes_to_get=[...])` on a model of my own, and it seems to work as I'd expect: attributes which I didn't request remain in their default or null values.

**Comment by ananya-dev** [comment]
@ikonst : Thanks for the clarity! I wasn't considering the Model defined default values. 
Closing this issue!
