### ISSUE TITLE
dynamodb tables 

### ISSUE THREAD

**Issue by rajshahdev** [pynamodb/PynamoDB#1035]
Hey,

i am using pynamodb connections.py file and this gives only table name

`from pynamodb.connection import Connection`

`# Get a connection`
`conn = Connection(host='http://localhost:8000')`
`# print(conn)`

`print(conn.list_tables())`

this gives only table name but i also want to use those tables and insert the data into that table without writing the model defination.

@garrettheel

**Comment by rajshahdev** [comment]
@ikonst

**Comment by ikonst** [comment]
PynamoDB's only advantage over using the [native DynamoDB Python API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html) is models. If you don't need models, consider using the native API.
