### ISSUE TITLE
TableError when creating table with ListAttribute

### ISSUE THREAD

**Issue by holyoaks** [pynamodb/PynamoDB#1042]
In 5.2.1, I've started having an issue that I didn't have in 5.1.0. I am no longer able to create a table when I also create a `GlobalSecondaryIndex`. This is occurring both in a local docker app running localstack 0.13, as well as in AWS itself. I have run the sample code below in iPython locally and on my EC2 server and it fails to create the table with the same error in both environments.

```
from pynamodb.attributes import (
    BooleanAttribute,
    ListAttribute,
    MapAttribute,
    NumberAttribute,
    UnicodeAttribute,
    UTCDateTimeAttribute,
)
from pynamodb.exceptions import DoesNotExist, GetError
from pynamodb.indexes import AllProjection, GlobalSecondaryIndex, IncludeProjection
from pynamodb.models import Model

class EmailDomainIndex(GlobalSecondaryIndex):
    """A secondary index on the Workspace email_domains attribute"""

    class Meta:
        index_name = "email-domain-ix"
        read_capacity_units = 250
        write_capacity_units = 10
        projection = IncludeProjection(["access_code", "company_name", "email_domains"])

    email_domains = UnicodeAttribute(hash_key=True)

class TestWorkspace(Model):
    class Meta:
        table_name = "workspace-test"
        write_capacity_units = 1
        read_capacity_units = 1
        region = "us-east-1"

    access_code = UnicodeAttribute(hash_key=True)
    company_name = UnicodeAttribute(null=True)
    email_domains = ListAttribute(null=True)
    email_lookup_index = EmailDomainIndex()

if not TestWorkspace.exists():
    TestWorkspace.create_table(wait=True)

```

The error I receive is 
```
TableError: Failed to create table: An error occurred (ValidationException) on request (2P1KPE623BTU6TMFML7CCLUVCVVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (workspace-test) when calling the CreateTable operation: 1 validation error detected: Value 'L' at 'attributeDefinitions.2.member.attributeType' failed to satisfy constraint: Member must satisfy enum value set: [B, N, S]
```

Again, I do not receive this error in the previous version I had installed, 5.1.0. Please fix, or let me know what changed between versions that requires me to update my approach. Thanks!

**Comment by holyoaks** [comment]
It appears that it is the ListAttribute that is causing the issue (I believe that is the `L` referred to in the error). So I cannot upgrade boto3 nor PynamoDB because of this error. Please help!!

**Comment by ikonst** [comment]
In the index, you define:
```python
email_domains = UnicodeAttribute(hash_key=True)
```
In the model, you define:
```python
email_domains = ListAttribute(null=True)
```

Did you mean this attribute to be a string (`S`) or a list (`L`)?

I have a slight suspicion you expected something like [MongoDB's Multikey Indexes] (https://www.mongodb.com/docs/manual/core/index-multikey/) here, but DynamoDB simply doesn't support that. A single table item will map to one or zero items in the GSI, but never more than 1.

**Comment by holyoaks** [comment]
Thank you @ikonst . Strange that prior to 5.2 this did not cause an error; perhaps it was boto3 that didn't do any checking and allowed this to go through.

**Comment by ikonst** [comment]
The main question is - how did it work? How was the table being created in practice?

**Comment by holyoaks** [comment]
The table was created fine prior to 5.2, but apparently we never actually used the index (or column), so we're simply going to drop the column and index.

**Comment by ikonst** [comment]
Alright, fair enough ;) I guess the tl;dr here is that DynamoDB doesn't have multikey indexes and it's a shame.
