### ISSUE TITLE
"UnicodeAttribute" object has no attribute "endswith"

### ISSUE THREAD

**Issue by hoIIer** [pynamodb/PynamoDB#1043]
Encountered a strange bug where the following works:
```
    models.Thing.foo_id_by_bar_id_index.query('baz', models.Thing.bar_id.startswith('abc'))
```

While the following fails with error in the title:
```
    models.Thing.foo_id_by_bar_id_index.query('baz', models.Thing.bar_id.endswith('abc'))
```

**Comment by ikonst** [comment]
There's no such expression in DynamoDB. For a list of supported expressions:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.KeyConditionExpressions

**Comment by hoIIer** [comment]
I see, weird they would add startswith but not endswith!

**Comment by ikonst** [comment]
startswith is mostly useful for sort indexes. Just like when searching in a name-sorted phone book, you can quickly filter by starts-with but not by ends-with.
