### ISSUE TITLE
How can I upload data to my AWS DynamoDB with the Django Admin?

### ISSUE THREAD

**Issue by Amechi101** [pynamodb/PynamoDB#105]
I have use the Model I created with pynamodb, to talk with the my AWS DynamoDB, but now I would like to view the contents and upload more things, while using the Django Admin interface.

**Comment by jpinner-lyft** [comment]
My interpretation of this issue is that you're asking for something like Django's `ModelAdmin` class to register PynamoDB's models with the Django admin interface. While such an adapter certainly sounds feasible, it is out-of-scope for this project.
