### ISSUE TITLE
Accessing model base class attributes

### ISSUE THREAD

**Issue by Mirch** [pynamodb/PynamoDB#1068]
I know the inheritance topic has been discussed a couple of times here, but I have a setup that is giving me headaches and I would like to know if whatever I am trying to accomplish is at all possible. The setup goes as follows:

```
class BaseModel(Model):
    foo = UnicodeAttribute()
    
class ActualModel1(BaseModel):
    class Meta:
        table_name = "actual_model_1"
        region = "eu-west-1"
        
    # other attributes
        
class ActualModel2(BaseModel):
    class Meta:
        table_name = "actual_model_2"
        region = "eu-west-1"
        
    # other attributes
```

Now, when doing certain update operations, the attributes are not referred to directly (in order to keep things generic), but through something like this:

```
key = "attribute_name"  # user input
value = "attribute_value"  # user input
actions = [ActualModel1.__getattribute__(ActualModel1, key).set(value)]
```

This all works fine until `key = "foo"`, and the error I'm getting is:

```
AttributeError: 'MetaModel' object has no attribute 'foo'
```

What would be a way of accomplishing this? Perhaps building a model object from the user input and then basing the update expression on that would work?

**Comment by garrettheel** [comment]
Try `getattr(ActualModel1, key)` instead. The way you're using `__getattribute__` in the example would not find attributes on parents (not a pynamo specific thing, it would have the same issue with vanilla python classes)

**Comment by Mirch** [comment]
> Try `getattr(ActualModel1, key)` instead. The way you're using `__getattribute__` in the example would not find attributes on parents (not a pynamo specific thing, it would have the same issue with vanilla python classes)

Thanks, this solved it.
