### ISSUE TITLE
[Feature] add __post_init__ method to allow any customization

### ISSUE THREAD

**Issue by MacHu-GWU** [pynamodb/PynamoDB#1070]
## WHY

Most of modern ORM or data class library support user custom "Post Initialization Hook" that allow user to run any code after the instance is initialized. By doing this, user can implement their own easily:

- Write Procedure
- Validation
- Or any custom requirements

For example:

- The standard library dataclass support [__post_init__](https://docs.python.org/3/library/dataclasses.html#post-init-processing)
- The attrs support [__attrs_post_init__](https://www.attrs.org/en/stable/init.html?highlight=__attrs_post_init__#post-init)
- The sqlalchemy support [reconstructor](https://docs.sqlalchemy.org/en/14/orm/constructors.html#sqlalchemy.orm.reconstructor) 

You should consider doing this too

## HOW

I would recommend to just define an dummy function ``__post_init__`` in your ``Model`` class and call this function at the end of your ``__init__`` function [HERE](https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/models.py#L304):

```python
class Model:
    def __init__(self, ...):
        ... # your code
        self.__post_init__()

    def __post_init__(self):
        pass
```

**Comment by MacHu-GWU** [comment]
never mind I added this feature in [pynamodb_mate](https://pypi.org/project/pynamodb-mate/) from 5.3.4.4

**Comment by ikonst** [comment]
This is a good idea. Have to think a bit about when and how, e.g.
- on init vs. on save
- load existing model vs. construct new mode
