### ISSUE TITLE
[Typing] Expected type 'Condition | None', got 'bool' instead 

### ISSUE THREAD

**Issue by soer7022** [pynamodb/PynamoDB#1075]
Hello, 
I'm using pynamodb version: 5.2.1, with python 3.10, coding in IDE: PyCharm professional, but I'm getting the following warning whenever I want to use Conditions while scanning:
![Screenshot 2022-09-23 at 11 24 26](https://user-images.githubusercontent.com/17567175/191930877-002f3e01-733f-4c40-8d5e-642d67807035.png)
Would be awesome if this could be fixed, or maybe some guidance on how to use Conditions instead of Bools?
Regards

**Comment by ikonst** [comment]
This is likely a PyCharm limitation. Other type checkers handle the overloading of `==` correctly.
