### ISSUE TITLE
Broken with latest version of Boto3 just released

### ISSUE THREAD

**Issue by danros** [pynamodb/PynamoDB#1084]
2022-10-25T15:59:15.987+01:00 | ap = AP.get(pk, 'root')
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/models.py", line 540, in get
  | 2022-10-25T15:59:15.987+01:00 | data = cls._get_connection().get_item(
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/table.py", line 213, in get_item
  | 2022-10-25T15:59:15.987+01:00 | return self.connection.get_item(
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/base.py", line 1197, in get_item
  | 2022-10-25T15:59:15.987+01:00 | operation_kwargs = self.get_operation_kwargs(
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/base.py", line 903, in get_operation_kwargs
  | 2022-10-25T15:59:15.987+01:00 | operation_kwargs.update(self.get_identifier_map(table_name, hash_key, range_key, key=key))
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/base.py", line 820, in get_identifier_map
  | 2022-10-25T15:59:15.987+01:00 | tbl = self.get_meta_table(table_name)
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/base.py", line 548, in get_meta_table
  | 2022-10-25T15:59:15.987+01:00 | data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/base.py", line 329, in dispatch
  | 2022-10-25T15:59:15.987+01:00 | data = self._make_api_call(operation_name, operation_kwargs, settings)
  | 2022-10-25T15:59:15.987+01:00 | File "/var/task/pynamodb/connection/base.py", line 358, in _make_api_call
  | 2022-10-25T15:59:15.987+01:00Copyrequest_dict = self.client._convert_to_request_dict( | request_dict = self.client._convert_to_request_dict(
  | 2022-10-25T15:59:15.987+01:00CopyTypeError: _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url' | TypeError: _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'
  | 2022-10-25T15:59:15.987+01:00

**Comment by notenti** [comment]
I think this issue was addressed in #1083.

**Comment by ikonst** [comment]
This should be fixed in 5.2.3.
