### ISSUE TITLE
TypeError: _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url' after Botocore 1.28.0

### ISSUE THREAD

**Issue by porterhyphenborden** [pynamodb/PynamoDB#1089]
Seeing an error in a get request since [Botocore 1.28.0 ](https://pypi.org/project/botocore/1.28.0/) was released the other day.

`File \"/var/task/pynamodb/pagination.py\", line 194, in __next__\n    self._get_next_page()\n  File \"/var/task/pynamodb/pagination.py\", line 179, in _get_next_page\n    page = next(self.page_iter)\n  File \"/var/task/pynamodb/pagination.py\", line 115, in __next__\n    page = self._operation(*self._args, settings=self._settings, **self._kwargs)\n  File \"/var/task/pynamodb/connection/table.py\", line 270, in query\n    return self.connection.query(\n  File \"/var/task/pynamodb/connection/base.py\", line 1288, in query\n    tbl = self.get_meta_table(table_name)\n  File \"/var/task/pynamodb/connection/base.py\", line 548, in get_meta_table\n    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)\n  File \"/var/task/pynamodb/connection/base.py\", line 329, in dispatch\n    data = self._make_api_call(operation_name, operation_kwargs, settings)\n  File \"/var/task/pynamodb/connection/base.py\", line 358, in _make_api_call\n    request_dict = self.client._convert_to_request_dict(\nTypeError: _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'`

Seems to be caused by a change in the signature for the private method `botocore.client._convert_to_request_dict`:
https://github.com/boto/botocore/compare/1.27.96...1.28.0#diff-5060d2324ee91a83dabd55d229d545c2900d28da7b07b7eb70e4dd01ae52a108L956-R968

We fixed for now by pinning botocore to 1.27.96.

**Comment by ikonst** [comment]
Dup of #1081, addressed in pynamodb 5.2.3.
