### ISSUE TITLE
Clarify changes in 5.3.0

### ISSUE THREAD

**Issue by captaincoordinates** [pynamodb/PynamoDB#1097]
Could you please clarify what changes are required to use release 5.3.0? Release Notes are currently missing for 5.3.0 but the available info implies that this version includes breaking changes. I'm seeing test failures since 5.3.0 (dependency is `^5.2.0`). If 5.3.0 does include breaking changes please consider changing the version to 6.0.0.

<img width="727" alt="Screen Shot 2022-11-03 at 4 44 35 PM" src="https://user-images.githubusercontent.com/64801328/199855764-8c94a539-147e-402a-829f-95d2b1577895.png">

**Comment by ikonst** [comment]
The correct release notes for 5.3.0 can be seen:
- in [the docs for the stable version](https://pynamodb.readthedocs.io/en/stable/release_notes.html)
- in [docs/release_notes.rst with 5.3.0 tag](https://github.com/pynamodb/PynamoDB/blob/5.3.0/docs/release_notes.rst)

I'll look into ways to integrate better with pypi.

Regardless, the change from 5.2.2 to 5.3.0 was intended to be an enhancement but not something that should've impacted reasonable use. Can you share more information about what broke?

**Comment by captaincoordinates** [comment]
@ikonst thanks for clarifying; I didn't realise there could be different release notes in different locations.

An error occurs in the `query` method when a model's `Meta.host` property is present and points to a local instance of DynamoDB. I would probably need some time to reproduce the error in an isolated repo, but here is the exception:
```
        try:
            return self.dispatch(QUERY, operation_kwargs, settings)
        except BOTOCORE_EXCEPTIONS as e:
>           raise QueryError("Failed to query items: {}".format(e), e)
E           pynamodb.exceptions.QueryError: Failed to query items: An error occurred (ResourceNotFoundException) on request (b5ae5c12-eaa5-4691-b4c7-9d5bd3a2e0af) on table (TableName) when calling the Query operation: Cannot do operations on a non-existent table
/usr/local/lib/python3.8/site-packages/pynamodb/connection/base.py:1375: QueryError
```
All I have to do to fix this error is limit the PynamoDB version with `~5.2.3`

**Comment by ikonst** [comment]
It's curious, since our integration tests do exactly that (running `dynamodb-local` and pointing `host` to `http://localhost:8000`), e.g.
https://github.com/pynamodb/PynamoDB/blob/43a303bea99033348274c3990c6ab71810b76758/tests/integration/binary_update_test.py#L12

Is your table named `TableName` or is it your own redaction?

**Comment by captaincoordinates** [comment]
`TableName` is not the real table name. So far I've not been able to identify any other changes, besides the version, that affect the error so I'll have to try to isolate the issue in a minimal repo. I suggest closing this issue and I'll open a new one when I am able to reproduce.

**Comment by ikonst** [comment]
It's worth seeing if `create_table` calls result in tables being created. There's been some subtle changes there, but I cannot know how you might've depended on the old implementation.
