### ISSUE TITLE
Question about custom attribute

### ISSUE THREAD

**Issue by eherozhao** [pynamodb/PynamoDB#1115]
I have a use case to save an attribute like {"STATE": ["live", "published"]} which key is a UnicodeAttribute and value is a ListAttribute holding UnicodeAttribute. Does anyone have any clue I can achieve it? Thank you.

**Comment by ikonst** [comment]
```python
class MyModel(Model):
  key = UnicodeAttribute(hash_key=True)
  state = ListAttribute(of=UnicodeAttribute)
```

Re-open if you have any more specific question.

**Comment by eherozhao** [comment]
The key is dynamic not a static one so I can have `{"STATE": {"live", "publish"}, "BRANCH": {"live"}}`.

**Comment by ikonst** [comment]
I'm not sure what a "dynamic" key is. You have to give more details.

**Comment by eherozhao** [comment]
okay. I have a Model with an attribute called "dynamic_map". I would like to save a map into this attribute. Key is a string and value is a list of string. They are all changeable which means I can have `{"STATE": {"live", "publish"}, "BRANCH": {"live"}}` with different key and different value. The default MapAttribute will make the key static so I use dynamic as an opposite.

**Comment by ikonst** [comment]
This should work, yes.

**Comment by eherozhao** [comment]
hmm I don't think so. what I want is for a single attribute not for the whole table..
The json result for that attribute should be
```
dynamic_map: {
          State:
               [live, delivered],
          Branch:
               [live]
}
```

**Comment by ikonst** [comment]
```
class MyModel(Model):
  dynamic_map = MapAttribute()
```
and then
```
```

**Comment by eherozhao** [comment]
kind of similar to this request: https://github.com/pynamodb/PynamoDB/issues/500

**Comment by eherozhao** [comment]
hmm. this works but I am looking for a way to directly use `setattr(resource, attribute, value)` to update the whole attribute so it seems not work for this request. Isn't it?

**Comment by eherozhao** [comment]
I think I figured it out. Thanks @ikonst for your help!

**Comment by eherozhao** [comment]
However, is there a way I can format my attribute value type to just allow key: string and value: list of string?

**Comment by ikonst** [comment]
There's no runtime enforcement, but you can decorate the type and have a type-checker enforce it:
```python
from typing import List, Union

class MyModel(Model):
  dynamic_map: MapAttribute[str, Union[str, List[str]] = MapAttribute()
```

**Comment by eherozhao** [comment]
Nice! This should work. Thanks again!
