### ISSUE TITLE
KeyError: 'attribute_name'

### ISSUE THREAD

**Issue by sdzimiri** [pynamodb/PynamoDB#1132]
Hi, I had a question regarding this commit https://github.com/pynamodb/PynamoDB/pull/1091/commits/a11576098199909c33a6cefdead4358fd1b324e7

In our code base, we were using PynamoDB and the change in this commit broke our pipeline since we are using `attribute_name` and getting key_error. Please see below for the error message. We now have a chicken and egg problem since we need the commit in our pipelines but we also need a code change to get in before the commit. 

```
(attr_def for attr_def in tbl_prop["attribute_definitions"] if attr_def.attribute_name == index_attribute_definition["attribute_name"]), None
KeyError: 'attribute_name'
```

Wondering what would be the fix for this ? Thanks

**Comment by ikonst** [comment]
What do you refer to by "pipeline"?

If you refer to CI, in a typical setup CI starts off by installing packages, so if your change-set includes both a change to your requirements.txt and a change to the code, then you can have CI check it in tandem.

**Comment by sdzimiri** [comment]
Yes, I am referring to CI but the change in our code should be something like this right ? with `ATTR_NAME` instead of `attribute_name`

`(attr_def for attr_def in tbl_prop["attribute_definitions"] if attr_def.attribute_name == index_attribute_definition[ATTR_NAME]), None`

**Comment by ikonst** [comment]
BTW, `ATTR_NAME` is just `"AttributeName"`. Also, are you calling `_get_schema()`?  This function starts with an underscore, meaning it's not part of the public API, and that's why we changed it.

**Comment by ikonst** [comment]
What kind of "index data" you need? I don't have the full context.

**Comment by sdzimiri** [comment]
From the `_get_schama,` that would be `attribute_definitions` and `global_secondary_indexes`
