### ISSUE TITLE
unsupported operand type(s) for &: 'NotExists' and 'bool'

### ISSUE THREAD

**Issue by Unintendedz** [pynamodb/PynamoDB#1137]
Hi there, I'm new to DynamoDB and I'm trying to implement some conditions, but I'm having some trouble. I have the following code:
```
condition = None
condition &= Account.expired.does_not_exist()
condition &= Account.country == country  # I'm getting an error here: "unsupported operand type(s) for &: 'NotExists' and 'bool'"
```
Is there something that I'm missing? Any help would be greatly appreciated. Thank you in advance!

**Comment by ikonst** [comment]
Can you share a snippet of your `Account` class where you define `expired` and `country`?

**Comment by Unintendedz** [comment]
Thanks for your quick reply. I'm sorry I didn't provide enough information in my initial submission. I'm currently trying to reproduce the problem with simpler code, but the error disappears when I do this, which is confusing me🤦‍♂. Can you give me a little more time to figure out what's going on? I'd really appreciate it. Thanks for your understanding.

**Comment by Unintendedz** [comment]
I understand now. My country parameter was accidentally passed None as its value. Even though I annotated the function parameter as a str, I didn't check the value of country. This issue has nothing to do with PynamoDB, it was just a mistake on my part. I'm sorry for the inconvenience and I will close this issue.
