### ISSUE TITLE
Accomplishing upsert operations

### ISSUE THREAD

**Issue by mijolabs** [pynamodb/PynamoDB#1138]
Imagining a table with UTCDateTimeAttributes named `created_at` and `updated_at`, we want an item's `created_at` field to be set to the datetime the item was first created, and `updated_at` to be updated only during any future changes to the item.

Is it possible to create a new item if it doesn't exist, else if the item already exists we only update the `updated_at` field? All of this in one single request (else we might as well send two requests and handle the logic locally).

At first glance the UpdateItem looked promising:
> The UpdateItem DynamoDB operations allows you to create or modify attributes of an item using an update expression.

But this seems to only work for existing items. The conditional will fail if the item doesn't yet exist. Is this understanding correct, and is there a way of accomplishing item creation or updating in the same request?

**Comment by ikonst** [comment]
[UpdateItem docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) say:
> Edits an existing item's attributes, or adds a new item to the table if it does not already exist.

so you could do something like:
```python
my_model.update_item(hk, actions=[
  MyModel.created_at.set(MyModel.created_at | datetime.utcnow()),
  MyModel.updated_at.set(datetime.utcnow()),
])
```

The syntax for `if_not_exists` is documented [here](https://pynamodb.readthedocs.io/en/stable/updates.html) but we definitely could do a better job...

**Comment by mijolabs** [comment]
Thanks, that does seem to work nicely. I had gotten lost in trying to use `exists()`/`does_not_exist()`.

Do you know if it's possible to perform many of these updates in a batch operation?

**Comment by mijolabs** [comment]
Reopening because of strange behavior. It worked perfectly against my LocalStack instance, the item including all fields got created, but if the item already exists then only the `updated_at` field was updated, as expected.

But performing this against real DynamoDB results in only creating the HK attribute and the fields specified in the `actions` parameter list. I don't know if this behavior is due to LocalStack's implementation, or if this is a bug in PynamoDB.

**Comment by ikonst** [comment]
Please share the update command or at least a reduced example.

**Comment by mijolabs** [comment]
Here's a minimal version of `MyModel`:
```python
class MyModel(Model):
    class Meta:
        table_name = config.defaults.table_name

    _id = UnicodeAttribute(hash_key=True)
    created_at = UTCDateTimeAttribute(default=get_timestamp())
    updated_at = UTCDateTimeAttribute(default=get_timestamp())
    source = UnicodeAttribute(default=config.defaults.source_name)
    score = NumberAttribute(default=config.defaults.score)
```

`item.attribute_values`:
```python
{'score': 3, 'created_at': datetime.datetime(2022, 12, 16, 12, 4, 5, tzinfo=datetime.timezone.utc), 'score': 3, 'updated_at': datetime.datetime(2022, 12, 16, 13, 2, 46, tzinfo=datetime.timezone.utc), '_id': 'GNWDZPmi'}
```

The `item` MyModel object contains several attributes, but trying the below operation only creates the hash key (`_id`) and `created_at`.

```python
item.update(
    actions=[
        MyModel.created_at.set(MyModel.created | get_timestamp())
    ]
)
```

The end goal is to perform batch upserts and since the `update` method isn't supported in `batch_write()`, I was hoping to use `TransactionWrite` instead. So I had also tried this:
```python
with TransactWrite(connection=self.connection) as transaction:
    for item in batch:
        transaction.update(
            item,
            actions=[
                MyModel.created_at.set(MyModel.created_at | get_timestamp())
            ]
        )
```
If I try to `MyModel.get("GNWDZPmi").attribute_values`, it will show all the attributes. But in the AWS console when exploring the table items, there are only columns with `_id` and `created_at` (testing on an empty table).

If I fetch the item with boto3: `{'Items': [{'created': '2022-12-16T12:04:05.000000+0000', '_id': 'GNWDZPmi'}], ... }`

Is this the expected behavior? I'm still open to having misunderstood the functionality.

If this is indeed the expected behavior, is there perhaps some way to include the remainder of the `item` attributes in the operation so they get created?

**Comment by ikonst** [comment]
The `attribute_values` you're "getting back" is a result of PynamoDB filling in for missing values based on the `default=`s. This is done so that you could take an existing table with existing data, and add a new attribute without having to backfill that attribute's default across millions or billions of items: instead, you specify the default in code and have it filled-in on deserialization. If you then choose to `save()` the model, those defaults would be written into the actual item in DynamoDB so that clients that don't have the PynamoDB model definition (e.g. boto) would see them.

**Comment by mijolabs** [comment]
That confirms what I suspected. I just thought I was doing something wrong because was under the impression it would be possible to create the entire object (all attributes), or just update certain attributes, in one single request. If we `save()` to update, it means we're sending another request. So I'm concluding that it's not possible.

Thanks again for your clarification.

**Comment by ikonst** [comment]
Well, you can add the defaults as actions, we just don't silently insert them into `update`s:
```diff
 item.update(
     actions=[
         MyModel.created_at.set(MyModel.created | get_timestamp()),
+        MyModel.source.set(MyModel.source | config.defaults.source_name),
     ]
 )
```
or if you don't want not to repeat the default value
```diff
 item.update(
     actions=[
         MyModel.created_at.set(MyModel.created | get_timestamp()),
+        MyModel.source.set(MyModel.source | MyModel.source.default),
     ]
 )
```

**Comment by mijolabs** [comment]
Understood this is possible, but in my model example I had omitted some attributes that can be nullable/empty, so not all `item` objects may have all of the attributes or the exact same set of them. Just trying to follow best practice as described in [the docs](https://pynamodb.readthedocs.io/en/stable/tutorial.html#defining-model-attributes) by omitting attributes when possible instead of giving them a placeholder value.

It will be a fairly large amount of objects so need to perform the update operations in a loop.

Is there a clever way to populate the actions parameter list dynamically, or is my best option to set null/placeholder values as defaults instead of omitting certain attributes entirely?

**Comment by ikonst** [comment]
> Is there a clever way to populate the actions parameter list dynamically

You'd have to write that code yourself. PynamoDB doesn't.

> or is my best option to set null/placeholder values as defaults instead of omitting certain attributes entirely?

It's really up to you. If you're spending the WCUs to update millions of items, you might as well "materialize" those defaults by adding them to the update actions.

> It will be a fairly large amount of objects so need to perform the update operations in a loop.

While at it, I don't think **transactions** are what you're looking for. They're more expensive that just doing the `UpdateItem`s one by one:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html#transaction-capacity-handling

**Comment by mijolabs** [comment]
It'll be done in a Lambda so there's a time limit to perform the entire operation, that's why I was hoping to batch them that way. But thanks for the link, I suppose I'll look into performing them one-by-one asynchronously instead.

Appreciate your input. Thanks

**Comment by mijolabs** [comment]
Just for follow-up in case anyone needs to do the same thing, this is a bit hackish and ain't pretty, but seems to work:

```python
actions = [
    getattr(MyModel, k).set(getattr(item, k)) for k in item.attribute_values.keys()
    if k not in ("_id", "created_at")
    ]

actions.append(MyModel.created_at.set(MyModel.created_at | get_timestamp()))

MyModel.update(item, actions=actions)
```
It beats having to explicitly set each attribute in the actions parameter list, and also allows for nullable attributes.
