### ISSUE TITLE
Incostistent log and documentation. 

### ISSUE THREAD

**Issue by vamsis-adapa** [pynamodb/PynamoDB#1139]
https://github.com/pynamodb/PynamoDB/blob/b3330a43ee8f9c203a32834f080dde42ab4cf8c7/pynamodb/attributes.py#L886

expected format is %Y-%m-%dT%H:%M:%S.%f+0000 (seen here https://github.com/pynamodb/PynamoDB/blob/b3330a43ee8f9c203a32834f080dde42ab4cf8c7/pynamodb/attributes.py#L882-L886 )
but logs and documentation show that required format is %Y-%m-%dT%H:%M:%S.%fZ

**Comment by vamsis-adapa** [comment]
Especially confusing due to the fact that strict adherence to format is required.

**Comment by ikonst** [comment]
Good eye.
To clarify, the difference is:
```diff
-%Y-%m-%dT%H:%M:%S.%fZ
+%Y-%m-%dT%H:%M:%S.%f+0000
````

In other words, we don't support arbitrary timezones, but do require explicit UTC in the form of `+0000` (and no other form).

**Comment by vamsis-adapa** [comment]
Thanks, that would be great!
