### ISSUE TITLE
How to build dynamic update expression

### ISSUE THREAD

**Issue by vaimdev** [pynamodb/PynamoDB#1142]
First of all, thanks for building this great library.
I am developing a base CRUD class /functions using pynamoDB.
I found it not possible to write something like 

`MyModel.update(actions=[getattr(MyModel, k).set(v) for k, v in mydata.dict()])

 `
 is there anyway to do that ? or any suggestions?

**Comment by ikonst** [comment]
Why is it not possible? Perhaps you forgot to call `.items()` on `mydata.dict()`?

For the record, I find this schema-less approach to be messy, but it should work.

**Comment by ikonst** [comment]
Re-open if you have more questions.
