### ISSUE TITLE
Add upgrade guide to docs

### ISSUE THREAD

**Issue by ikonst** [pynamodb/PynamoDB#1149]
# PynamoDB 2 -> 3

- https://pynamodb.readthedocs.io/en/stable/upgrading_unicodeset.html

# PynamoDB 3 -> 4

- Rewriting conditional expressions (e.g. `foo__none=True` -> `condition=MyModel.foo.does_not_exist()`)
- Rewriting actions

# PynamoDB 4 -> 5

- TODO: Release notes should be split into breaking changes and features
- Maps in lists now have nullability enforced
- Empty strings no longer coalesced to `None` on read-back

# PynamoDB 5 -> 6

- https://pynamodb.readthedocs.io/en/latest/upgrading_binary.html

**Comment by zhang-alvin** [comment]
not related to this issue directly, but what is the intended release schedule for version 6.0?
