### ISSUE TITLE
How to use pynamodb to implement records pagination

### ISSUE THREAD

**Issue by vaimdev** [pynamodb/PynamoDB#1153]
Thanks for this  good library !

As mentioned in subject, how to implement records pagination with pynamodb? 
A normal query() will return records by limit but how do we can make use of it to implement records pagination?

**Comment by ikonst** [comment]
Either use [last_evaluated_key](https://pynamodb.readthedocs.io/en/stable/indexes.html?highlight=last_evaluated_key#pagination-and-last-evaluated-key), or simply add a range key condition requesting items after the last seen item. For example:
```python
UserCarModel.query(
  hash_key=user_id,
  range_key_condition=UserCarModel.purchased_at > last_seen_car_purchased_at,
  limit=10,
)
```

Let me know if you need more help.

**Comment by vaimdev** [comment]
@ikonst , thanks. I think last_evaluated_key will work for me!
