### ISSUE TITLE
PynamoDB writes data despite Condition expression failure

### ISSUE THREAD

**Issue by thegeekcentaur** [pynamodb/PynamoDB#1161]
Greetings,

I have a simple pynamodb model as below -

```
class Space(Model):
    class Meta:
        """Pynamodb meta info"""
        table_name = "space"

    t_id = UnicodeAttribute(hash_key=True)
    w_id = UnicodeAttribute(range_key=True)
    name = UnicodeAttribute()
    checksum = UnicodeAttribute()
```

I want to use a condition while writing such that if the checksum matches, the save will not happen (to avoid duplicate) -
```
        try:
            obj = space.save(condition = (Space.checksum != curr_checksum))
        except (VerboseClientError, PutError, BotoCoreError, ClientError) as save_error:
            LOG.error(save_error)
            abort(HTTPStatus.CONFLICT)
```
While I can see the exception being raised in LOG.error, I am also seeing that the record is being written to the dynamodb.

Set-up versions -
    Python: 3.7.12
    pynamodb: 5.3.4
    boto3: 1.19.4
    botocore: 1.22.4

Any suggestion/lead/correction welcome.

**Comment by ikonst** [comment]
How do you observe it being written?

**Comment by thegeekcentaur** [comment]
by going to the AWS console and checking the dynamodb. I can see fresh records there with same/duplicate data.

**Comment by ikonst** [comment]
I think there's some chance something else happened, unrelated (i.e. maybe something else made some change in parallel). This functionality is really quite solid.

**Comment by thegeekcentaur** [comment]
Can you possibly point me to some sample code/project/examples. I have followed the documentation and as I mentioned somehow I coult not get it to work as expecetd.

My requirement is when the checksum for an inbound record is not found in the *checksum* attribute/key for existing documents in the collection called `Space`, then and only then proceed to PynamoDB save, otherwise raise a duplicate error.

**Comment by ikonst** [comment]
Ooh. I think you might have a false impression of how DynamoDB works. Except for attributes that are a hash/range key, there's no way to maintain an invariant where an attribute is compared with attributes in other items.

If it was possible, it would mean that DynamoDB would do a full table scan on each "save" (PutItem).

For example:
```python
space = Space(t_id='one', w_id='two', checksum='spam')
space.save()
# This will FAIL because item ('one', 'two') has checksum 'spam'
space.save(condition=Space.checksum != 'spam')
```
but then
```python
space2 = Space(t_id='one', w_id='three', checksum='spam')
# This will succeed since item ('one', 'three') doesn't even exist yet,
# and its checksum doesn't exist either.
# It doesn't matter that ('one', 'two') has that same checksum.
space.save(condition=Space.checksum != 'spam')
```

If there should be just one item for any checksum, you quite simply should create a table with just a hash key, where the hash key is the checksum. (This is not an RDBMS, think purely of how you read/write the data, as if this was a data structure.)

**Comment by thegeekcentaur** [comment]
Thanks for the great example. Yes, that totally makes sense now.
