### ISSUE TITLE
Need last_evaluated_key from last query

### ISSUE THREAD

**Issue by LiteWait** [pynamodb/PynamoDB#118]
I was wondering if there was a way to get the last_evaluated_key returned from the query method so I can implement paging on my Web client.

Edit: It seems query() can't take a last_evaluated_key either.  Hopefully someone has a solution or workaround before I decide to fork and doing something stupid.

Thanks.

**Comment by danielhochman** [comment]
I think we can make a backwards compatible change to allow this functionality. We can have a `query_builder` method on the model which returns a `Query` object that exposes `last_evaluated_key` and other query arguments. We can have an `execute` method on `Query` that returns the result iterator. We can move all of the query logic to `Query` then have the current `query` method proxy to call `query_builder(*args, **kwargs).execute()`.

Then, to look at the `last_evaluated_key`, your code would look something like:

```
def get_page():
    q = MyModel.query_builder(hash_key='daniel', consistent_read=True)
    results = []
    for idx, result in enumerate(q.execute()):
        results.append(result)
        if idx == 99:
            return page, q.last_evaluated_key
    return page, None
```

Could also implement the `__iter__` and `next` methods directly and simplify this a bit. I'd have to think about it a bit more.

Thoughts?

**Comment by LiteWait** [comment]
Great idea, sounds pretty clean.  Should you implement this happy to test it.  If not, I get the concept and when I get some time I'll give it a go.

**Comment by danielhochman** [comment]
We should treat `scan` the same way, potentially with classes that inherit some behavior from a shared base class.

**Comment by jlafon** [comment]
@danielhochman what about creating a `QueryResult` class with an `__iter__` method that is a generator (and thus backward compatible) but also has `last_evaluated_key` and other attributes?

**Comment by danielhochman** [comment]
@jlafon yeah, I was leaning that way too. I might take a crack at this tomorrow.

**Comment by jpinner-lyft** [comment]
Fixed in https://github.com/pynamodb/PynamoDB/pull/379
