### ISSUE TITLE
Bug `model.batch_get()` reports duplicates when there are none.

### ISSUE THREAD

**Issue by bradwood** [pynamodb/PynamoDB#1180]
model def:

```python

class StatsScheduleModel(Model):
    """Specify a schedule for StatsBot cron-triggered jobs"""

    class Meta(Model.Meta):
        table_name = os.environ["APP_DYN_STATSSCHEDULES_TABLENAME"]

    frequency = UnicodeAttribute(hash_key=True)
    job_name = UnicodeAttribute(range_key=True)
    target_type = UnicodeEnumAttribute(TargetType)
    athena_workgroup = UnicodeAttribute()
    athena_database = UnicodeAttribute()
    msteams_config = MSTeamsConfig(null=True)

```

calling code:

```python
def get_jobs_for_freq(frequencies):
    """
    For a given list of frequencies, query dynamoDB and return all jobs that
    should be run for the frequencies passed.
    """
    jobs = []
    LOGGER.info(f"Searching DB for jobs with frequencies: {frequencies}")

    for schedule in StatsScheduleModel.batch_get(frequencies):
        jobs.append(schedule)

    LOGGER.info(jobs)
    return (None, "replace me")

```

when I call the above function with `['once_a_month', 'once_a_day', 'twice_a_day']` as my parameter, I get the following when run against AWS:

```
An error occurred (ValidationException) on request (G976CCPIAM7N5LR5KDPA7ETI6BVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (test-stats-schedules) when calling the BatchGetItem operation: Provided list of item keys contains duplicates"
```

But there are no duplicates anywhere...  Also, `model.query()` works fine.   I also tried replacing `frequencies` with `list(set(frequencies))` just in case -- no joy.

related to #1179  perhaps?

PS: I am running version 5.5.0 of pynamodb

**Comment by ikonst** [comment]
Your model has a hash key and a range key, so the keys in the list should be a 2-item iterables (e.g. 2-item tuples).

As for the reason for this weird message: my guess is that since ring in Python is iterable, `'once_a_month'` is interpreted as:
```python
key = 'once_a_month'
hash_key, range_key, *_ = key
assert hash_key == 'o'
assert range_key == 'n'
```
and similarly:
```python
key = 'once_a_day'
hash_key, range_key, *_ = key
assert hash_key == 'o'
assert range_key == 'n'
```
and DynamoDB complains that `[('o', 'n'), ('o', 'n'), ...]` contains the same item twice.

We should probably add some safeguards here:
- ensure each key has exactly 2 items
- assert the key is not a `str`
