### ISSUE TITLE
Workaround for measuring with opentelemetry?

### ISSUE THREAD

**Issue by kmkhr** [pynamodb/PynamoDB#1187]
As mentioned in #1079, it seems that currently it is not possible to measure access to dynamodb using the opentelemetry botocore instrumentation.

Is there any workaround to enable instrumentation?

**Comment by jereje** [comment]
I was looking for this same feature and I have realized that the latest version (6.0.0) added compatibility for opentelemetry botocore package: https://pynamodb.readthedocs.io/en/stable/release_notes.html#v6-0-0

Did not implemented yet but will try it soon

**Comment by ikonst** [comment]
This should be possible in 6.0. If not, please re-open.
