### ISSUE TITLE
batch write doesn't support condition?

### ISSUE THREAD

**Issue by Wan-Yifei** [pynamodb/PynamoDB#1203]
My model:

```
class Metadata(Model):
    """
    A DynamoDB table for Fastq Metadata.
    """

    class Meta:
        table_name = "Sample"
        region = 'us-east-1'
        host = "http://localhost:8000"
        write_capacity_units = 10
        read_capacity_units = 10

    sample_id = UnicodeAttribute(hash_key=True)
    nextflow_timestamp = UTCDateTimeAttribute(range_key=True)
```

I only want to save when the timestamp doesn't exist:
```
# batch is the instance of Metadata
batch.save(item.nextflow_timestamp.does_not_exist())
```

I got the error:
`AttributeError: 'datetime.datetime' object has no attribute 'does_not_exist'`

**Comment by Aareon** [comment]
Seems you are using `UTCDateTimeAttribute` wrong? I would suggest doing a get for all entries with that timestamp to perform that condition, and if nothing returns, then do a batch save.

**Comment by ikonst** [comment]
You cannot specify conditions in batch writes:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html
