### ISSUE TITLE
Breaking changes v6.0.0 No module named 'pynamodb.util'

### ISSUE THREAD

**Issue by jovana** [pynamodb/PynamoDB#1220]
Running the latest version 6.0.0 gives me a few other breaking changes then documented. 

**Issue 1:**
pynamodb.util does not exist:
```
from pynamodb.util import attribute_value_to_json
ModuleNotFoundError: No module named 'pynamodb.util'
```

**Issue 2:**
ValueError: An attribute's 'default' must be immutable (str, int, float, datetime, timedelta, bytes, bool, tuple, frozenset, NoneType) or a callable (see https://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.attributes.Attribute)
(below does work in 5.5.1)
```
files = ListAttribute(default=[])
```

**Issue 3:**
RuntimeError: Error calling __set_name__ on 'SettingsFinancial' instance 'branding_financial' in 'SettingsBranding'
(below does work in 5.5.1)
```
class SettingsFinancial(MapAttribute):
    prices_include_vat = BooleanAttribute(default=True)

class SettingsBranding(MapAttribute):
    branding_financial = SettingsFinancial(null=True, default={"prices_include_vat": True, })
```

Issue 1, I will use the new function ```to_json```
Issue 2 and 3 I want to know how to set the defaults for sub classes?

Thanks for any help!

Jo

**Comment by jovana** [comment]
> Running the latest version 6.0.0 gives me a few other breaking changes then documented.
> 
> **Issue 1:** pynamodb.util does not exist:
> 
> ```
> from pynamodb.util import attribute_value_to_json
> ModuleNotFoundError: No module named 'pynamodb.util'
> ```
> 
> **Issue 2:** ValueError: An attribute's 'default' must be immutable (str, int, float, datetime, timedelta, bytes, bool, tuple, frozenset, NoneType) or a callable (see https://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.attributes.Attribute) (below does work in 5.5.1)
> 
> ```
> files = ListAttribute(default=[])
> ```
> 
> **Issue 3:** RuntimeError: Error calling **set_name** on 'SettingsFinancial' instance 'branding_financial' in 'SettingsBranding' (below does work in 5.5.1)
> 
> ```
> class SettingsFinancial(MapAttribute):
>     prices_include_vat = BooleanAttribute(default=True)
> 
> class SettingsBranding(MapAttribute):
>     branding_financial = SettingsFinancial(null=True, default={"prices_include_vat": True, })
> ```
> 
> Issue 1, I will use the new function `to_json` Issue 2 and 3 I want to know how to set the defaults for sub classes?
> 
> Thanks for any help!
> 
> Jo

Okay I have found in the documentation about these breaking changes (issues 2 and 3). If anyone also wants to know how to fix, the solution can found here: https://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.attributes.Attribute

```
A simple workaround is to pass an initializer (e.g. change default={} to default=dict) or wrap in a lambda (e.g. change default={'foo': 'bar'} to default=lambda: {'foo': 'bar'}).
```

**Comment by ikonst** [comment]
With your permission I'll re-open since those are actual documentation bugs.

> **Issue 1:** pynamodb.util does not exist:

Thanks, removed it in #1126 and forgot to document.

> **Issue 2:** ValueError: An attribute's 'default' must be immutable (str, int, float, datetime, timedelta, bytes, bool, tuple, frozenset, NoneType) or a callable (see https://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.attributes.Attribute) (below does work in 5.5.1)

Ahh, that was a big one. Forgot to mention, will do.

> **Issue 3:** RuntimeError: Error calling **set_name** on 'SettingsFinancial' instance 'branding_financial' in 'SettingsBranding' (below does work in 5.5.1)

If I understand correctly, it stems from the same issue as #2.

**Comment by jovana** [comment]
> With your permission I'll re-open since those are actual documentation bugs.
> 
> 
> 
> > **Issue 1:** pynamodb.util does not exist:
> 
> 
> 
> Thanks, removed it in #1126 and forgot to document.
> 
> 
> 
> > **Issue 2:** ValueError: An attribute's 'default' must be immutable (str, int, float, datetime, timedelta, bytes, bool, tuple, frozenset, NoneType) or a callable (see https://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.attributes.Attribute) (below does work in 5.5.1)
> 
> 
> 
> Ahh, that was a big one. Forgot to mention, will do.
> 
> 
> 
> > **Issue 3:** RuntimeError: Error calling **set_name** on 'SettingsFinancial' instance 'branding_financial' in 'SettingsBranding' (below does work in 5.5.1)
> 
> 
> 
> If I understand correctly, it stems from the same issue as #2.

Thank you for the update. 
Yes basically issue 2 and 3 are related to each other. I have mentioned it to have twi different examples.
