### ISSUE TITLE
[Question] 5.4.x and 5.5.x changes are not documented in release note

### ISSUE THREAD

**Issue by MacHu-GWU** [pynamodb/PynamoDB#1237]
On [PyPI](https://pypi.org/project/pynamodb/#history), it has 5.4.X, 5.5.X. But in the [release note](https://pynamodb.readthedocs.io/en/latest/release_notes.html), there's no description about what's the feature added to them. May I know what's new in 5.4 and 5.5?

**Comment by ikonst** [comment]
Yeah, it must be because 5.4.x has backports. The changelog is on the `5.x` branch:
https://github.com/pynamodb/PynamoDB/blob/5.x/docs/release_notes.rst

We can copy it over to the master branch.

**Comment by ikonst** [comment]
Done: https://github.com/pynamodb/PynamoDB/commit/7d0ebf3979d9a8c537b6ce876ca09cc91e96ef64

**Comment by MacHu-GWU** [comment]
Y
