### ISSUE TITLE
[Question]Why am I intermittently encountering the error "TypeError: _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'" in production, and what could be causing this issue?

### ISSUE THREAD

**Issue by Rudraprakash054** [pynamodb/PynamoDB#1252]
Hi @ikonst 

Recently, we encountered an intermittent error in production: **"TypeError: _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'"**. To temporarily resolve the issue, we redeployed the applications in production.

We are using the following libraries:

- boto3==1.18.44
- botocore==1.21.44
- pynamodb==5.1.0

What could be causing this issue, and how can we fix it permanently?

**Comment by ikonst** [comment]
You should upgrade pynamodb to latest 5.x version.

**Comment by Rudraprakash054** [comment]
Ok @ikonst 
I'll update the pynamodb version to 5.2.3. Thanks a lot!

**Comment by ikonst** [comment]
5.5.1

**Comment by Rudraprakash054** [comment]
@ikonst why the 5.5.1 release change is not include in the documentation?

**Comment by ikonst** [comment]
Good catch, need to fix something in RTFD

**Comment by ikonst** [comment]
Should be fixed now
