### ISSUE TITLE
update_item delete item from set fails

### ISSUE THREAD

**Issue by eukaryote** [pynamodb/PynamoDB#132]
Here is a simple test case that attempts to remove an value from a UnicodeSet attribute:

``` python
from pynamodb.models import Model
from pynamodb.attributes import NumberAttribute, UnicodeSetAttribute


class UserModel(Model):

    class Meta:
        table_name = 'User'
        region = 'us-west-2'
        read_capacity_units = 1
        write_capacity_units = 1
        host = 'http://localhost:8000'

    id = NumberAttribute(hash_key=True)
    nicknames = UnicodeSetAttribute(null=True)


UserModel.create_table(wait=True)
try:
    original_nicknames = {'name1', 'name2', 'name3'}
    nicknames_to_remove = {'name2'}
    expected_result_nicknames = original_nicknames - nicknames_to_remove
    user = UserModel(id=1, nicknames=original_nicknames)
    user.save()
    user = UserModel.get(1)
    print('original nicknames:', user.nicknames)
    assert original_nicknames == user.nicknames
    print('nicknames to remove:', nicknames_to_remove)
    user.update_item('nicknames', value=nicknames_to_remove, action='delete')
    user = UserModel.get(1)
    print('expected result nicknames:', expected_result_nicknames)
    print('  actual result nicknames:', user.nicknames)
    print()
    assert expected_result_nicknames == user.nicknames
finally:
    UserModel.delete_table()
```

When running this test case, the output is:

```
original nicknames: {'name2', 'name3', 'name1'}
nicknames to remove: {'name2'}
expected result nicknames: {'name3', 'name1'}
  actual result nicknames: None

Traceback (most recent call last):
  File "mytest.py", line 34, in <module>
    assert expected_result_nicknames == user.nicknames
AssertionError
```

I expected 'name2' to be removed from the `{'name1', 'name2', 'name3'}` set, but instead all the values were removed.

This bug exists since 1.4.4 (1.4.3 works fine), and is still present in 1.6.0. The associated pull request has been updated to be be based on the post 1.6.0 devel branch, and it includes a unit test that fails with only the 'pynamodb/tests' commits applied but succeeds with the changes to connection/base.py and models.py (for update_item of connection and model, respectively).

**Comment by eukaryote** [comment]
See pull request #133 for a tentative fix that may still need some work.

**Comment by eukaryote** [comment]
A similar problem also occurs with the new update method, and the pull request has been updated to add a test for 'update' and to apply a similar fix for that case.

**Comment by jpinner-lyft** [comment]
@eukaryote the new update api correctly handles this use case:
```
>>> user = UserModel(1, nicknames={'name1', 'name2', 'name3'})
>>> user.save()
>>> user.update(actions=[UserModel.nicknames.delete({'name2'})])
{u'Attributes': {u'id': {u'N': u'1'}, u'nicknames': {u'SS': [u'name1', u'name3']}}}
>>> user.nicknames
set([u'name3', u'name1'])
```

**Comment by jpinner-lyft** [comment]
Fixed: https://github.com/pynamodb/PynamoDB/pull/374

**Comment by vinhvugearinc** [comment]
I got this error when updating a number attribuet ```UpdateError: Failed to update item: An error occurred (ValidationException) when calling the UpdateItem operation: One or more parameter values were invalid: DELETE action with value is not supported for the type N```  Is this possible to delete this attribute?
