### ISSUE TITLE
Allow scan on Secondary Indexes

### ISSUE THREAD

**Issue by behos** [pynamodb/PynamoDB#141]
Hi,

Looking at the docs here:

https://aws.amazon.com/about-aws/whats-new/2015/02/10/secondary-index-scan-a-simpler-way-to-scan-dynamodb-table/

It seems that DDB allows scanning on the secondary indexes for a while now.

Is there a plan to add this feature to pynamodb?

**Comment by jpinner-lyft** [comment]
Seems like this would be pretty easy to do by adding an `index_name` parameter to the low-level scan api and adding a convenience function to the index model.
