### ISSUE TITLE
Question: Making complex queries with filter expressions

### ISSUE THREAD

**Issue by synic** [pynamodb/PynamoDB#142]
I am working with calendar events, with fields like `start` and `end` indicating the start and end of the event.  

I need to get all events that intersect with a certain time range.  How can I do a query similar to this, where `start_time` and `end_time` are the passed in daterange:

```
(start < [start_time] AND end > [start_time]) OR 
(start > [start_time] AND start < [end_time])
```

**Comment by jpinner-lyft** [comment]
With 3.2.0+ PynamoDB supports the condition expression api:
```
((Item.start < start_time) & (Item.end > start_time)) |
((Item.start > start_time) & (Item.start < end_time))
```
