### ISSUE TITLE
Deserialize hash key while loading from json

### ISSUE THREAD

**Issue by krishna-lyft** [pynamodb/PynamoDB#143]
While trying to load a table from a json dump, https://github.com/jlafon/PynamoDB/blob/devel/pynamodb/models.py#L764 does not deserialize the hash key. Hence, we run into an exception if the hash key is anything other than a UnicodeAttribute. 

For example, the following will lead to an exception.

```
from pynamodb.models import Model
from pynamodb.attributes import (
    UnicodeAttribute, NumberAttribute
)

class Thread(Model):
    class Meta:
        table_name = 'Thread'

    forum_name = NumberAttribute(hash_key=True)
    subject = UnicodeAttribute(range_key=True)
    views = NumberAttribute(default=0)

# After the table has been populated

Thread.dump("thread_backup.json")
Thread.load("thread_backup.json")
```

**Comment by jpinner-lyft** [comment]
Fixed by https://github.com/pynamodb/PynamoDB/pull/386
