### ISSUE TITLE
Can't save UTCDateTimeAttribute

### ISSUE THREAD

**Issue by ccverak** [pynamodb/PynamoDB#162]
```
from datetime import datetime
...
model.last_executed_at = datetime.now()
model.save()
```

In python 2.7 doesn't work, I get `TypeError: datetime.datetime(2016, 9, 22, 13, 47, 8, 735446, tzinfo=<UTC>) is not JSON serializable`

What am I doing wrong?

**Comment by mikecee** [comment]
Seems to be working fine for me with pynamo 1.5.3 and python 2.7.12; following snippet might give you some other ideas to try?

```python
from datetime import datetime
import pytz

utc_tz = pytz.timezone('UTC')

def the_time_now():
    return datetime.now(utc_tz)

...
class Foo(Model):

    class Meta:
        table_name = 'proj-dev-foo'
        region     = 'us-west-2'
    ...
    updated_at = UTCDateTimeAttribute(default=the_time_now)
```

**Comment by mikecee** [comment]
Any chance you could post actual code and stack trace from this?  I've managed to get same outcome now, but in my case was not a Pynamo problem. The root cause for me was that the timezone element wasn't handled by the serialiser; the fix was to adjust the time to incorporate the timezone, and then set the tzinfo property to `None`.  It's not pretty and probably not "robust" if you need to worry about daylight savings etc. Code broken out to help explain

```python
   # Time now, with TZ recorded
   tmp = datetime.now(utc_tz)   
   # Convert to UTZ local and remove TZ
   ret = tmp.astimezone(utc_tz).replace(tzinfo=None)
   # Change representation to ISO8601 (i.e. string)
   ret = ret.isoformat() + 'Z'
```

**Comment by mathom** [comment]
I've found that you can't serialize datetime objects in a MapAttribute. I'm just using strings manually for now.

**Comment by yedpodtrzitko** [comment]
> I've found that you can't serialize datetime objects in a MapAttribute

The thing is - you cant serialize `datetime` in Python by default. You need to use a custom encoder class, eg:

```
class MyEncoder(json.JSONEncoder):

    def default(self, obj):
        if isinstance(obj, datetime):
            return int(mktime(obj.timetuple()))

        return json.JSONEncoder.default(self, obj)

json.dumps(datetime.now(), cls=MyEncoder)
```

**Comment by mathom** [comment]
Yeah I know, it would just be nice if the default pynamo types were supported out of the box. DynamoDB doesn't support datetime as a column either but it gets serialized as a part of the model, just not in the MapAttribute.

**Comment by edouardpoitras** [comment]
I have the same issue where UTCDateTimeAttribute inside of a MapAttribute object is not supported. Seems to work fine in my base models.
For now I'm using a UnicodeAttribute to get around this issue and manually serializing/deserializing as needed.

**Comment by jethroguce** [comment]
I'm also having the same issue, and can't get past thru this currently

**Comment by jharley** [comment]
For what it's worth, I've been developing using the `dynamodb2` mock from [moto](https://github.com/spulec/moto) and ran into an issue where moto seems to be converting the timestamp to string -- breaking `save` calls.

I got around it with this subclass for the moment (Python 3), sharing here in case it helps someone else?

```python
from dateutil.parser import parse as parsedatestring

class DatestampAttribute(UTCDateTimeAttribute):
    """
    An Attribute that works with moto and DynamoDB by intercepting the value, and
    converting it back to a 'datestamp' if it got converted to a 'str'
    """
    def serialize(self, value):
        if isinstance(value, str):
            value = parsedatestring(value)

        super().serialize(value)
```

**Comment by flavioribeiro** [comment]
the snippet above worked for me, only thing I needed to change is `def _serialize` instead of `def serialize`.
