### ISSUE TITLE
PynamoDB Relationships PR or standalone package?

### ISSUE THREAD

**Issue by yfilali** [pynamodb/PynamoDB#169]
In order to get a useful GraphQL implementation, I had to implement my own relationships on top of PynamoDB.

You can see what came out of it here: https://github.com/yfilali/graphql-pynamodb/blob/master/graphene_pynamodb/relationships.py

I don't feel this is the place for it, so I was wondering if you'd consider a PR to add OneToOne and OneToMany relationships to PynamoDB maybe under a relationships or contrib.relationships module. My other choice is to take that part out of graphene-pynamodb and into a standalone pynamodb-relationships package.

Any thoughts?

**Comment by garrettheel** [comment]
This is something that we're unlikely to add to PynamoDB itself, as it starts to stretch into the bounds of being a full ORM. A standalone package which augments PynamoDB in this way would be great though and we could certainly link to it in our docs :)

**Comment by yfilali** [comment]
Sounds good, I'll move that part out into a standalone package.
