### ISSUE TITLE
Model.batch_get doesn't utilize attributes_to_get parameter

### ISSUE THREAD

**Issue by 2x2xplz** [pynamodb/PynamoDB#189]
Records retrieved via `Model.batch_get` include all attributes, even when `attributes_to_get` is a list. Both calls to `cls._batch_get_page` inside the method specify `attributes_to_get=None` instead of passing along the input parameter.

**Comment by jpinner-lyft** [comment]
Fixed by https://github.com/pynamodb/PynamoDB/pull/308 in 3.1.0
