### ISSUE TITLE
Doc improvment:  Model Settings should not show region and localhost in the same example

### ISSUE THREAD

**Issue by tagleader** [pynamodb/PynamoDB#215]
I spent a bunch of hours trying to troubleshoot connection settings and AWS dynamoDB before I realized that I had screwed up the basic config from Model Settings example:
the Doc example:
        # Specifies the region
        region = 'us-west-1'
        # Specifies the hostname
        host = 'http://localhost'

The host is optional, since the regions should normally cause the endpoint URL to be automatically set correctly.  However, by putting in an example using localhost, which is completely invalid for AWS, it causes 'connection refused' from AWS with no useful log messages of why.  This only creates pain for newbies like myself trying to get a basic dynamoDB setup working.

I strongly recommend changing the example to be:
    # Specify the hostname only if it needs to be changed from the default AWS setting
   host = 'http://dynamodb.us-west-1.amazonaws.com'

**Comment by jmphilli** [comment]
https://github.com/pynamodb/PynamoDB/pull/400
