### ISSUE TITLE
Support new DynamoDB API

### ISSUE THREAD

**Issue by garrettheel** [pynamodb/PynamoDB#219]
This is a pretty big change, so keeping track of things in here.

We should move off of the legacy API for conditions whilst keeping backwards compatibility with PynamoDB 2.x for now (with a view to deprecate things at some point in the future).

See the following DynamoDB doc for more information on the changes:

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.html

This should be a major version bump up to 3 as it will change a lot and likely introduce a new API for some things.

**Comment by jpinner-lyft** [comment]
Complete Expression API Support: https://github.com/pynamodb/PynamoDB/pull/352
