### ISSUE TITLE
Support for versioned optimistic locking a la DynamoDBMapper

### ISSUE THREAD

**Issue by brandond** [pynamodb/PynamoDB#228]
Use a version attribute like DynamoDBMapper does to ensure that the record being updated hasn't changed server-side since last accessed by the client:
> http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html

**Comment by sdavids13** [comment]
Should this be closed? I believe this capability was merged in via: https://github.com/pynamodb/PynamoDB/pull/664

**Comment by ikonst** [comment]
Thanks, this was indeed merged :)
