### ISSUE TITLE
Is PynamoDB an asyc?

### ISSUE THREAD

**Issue by jl-DaDar** [pynamodb/PynamoDB#229]
I am considering using Tornado with pynamodb,
and want to make sure Pynamodb support asychronous db calls.
Pynamodb is not listed on https://github.com/tornadoweb/tornado/wiki/links
but botocore is

does that make pynamodb a good match for tornado?

Thanks!

**Comment by garrettheel** [comment]
We don't support asynchronous calls in this way, so would not currently be a good fit with Tornado if you need concurrency. I'd be interested and happy to discuss the possibility of how we could support such a thing in future (be it in the core library or with an add-on), though!

**Comment by jin09** [comment]
@garrettheel You can leverage the aioboto3 library for the library core instead to achieve this. The world is anyways moving towards the async side of python.
