### ISSUE TITLE
Update readthedocs.io

### ISSUE THREAD

**Issue by brandond** [pynamodb/PynamoDB#236]
The documentation on reathedocs.io seems to be stuck at 1.6.0 for stable and 1.4.3 for master. It'd sure be nice if these were in sync with the actual code.

**Comment by garrettheel** [comment]
@jlafon can you help out with this? Ideally the contributors would have access to push these updates

**Comment by garrettheel** [comment]
We've since started syncing this with the releases, should be up to date now. Thanks!
