### ISSUE TITLE
true / false as string in UnicodeSetAttribute is returned as True and False boolean

### ISSUE THREAD

**Issue by jl-DaDar** [pynamodb/PynamoDB#249]
just found this problem in UnicodeSetAttribute. true and false string stored in the set is converted to boolean...

**Comment by jmphilli** [comment]
https://github.com/pynamodb/PynamoDB/pull/294
 looks like it works to me -- can you write a test that breaks so i can see what you mean?

**Comment by jmphilli** [comment]
nvm found it

**Comment by jmphilli** [comment]
the `3.0.1` release fixes this. can you try that version out in a dev environment and see if it works for you? be warned there are breaking changes
