### ISSUE TITLE
Add support for Django-style Model Methods

### ISSUE THREAD

**Issue by brandond** [pynamodb/PynamoDB#251]
Since PynamoDB is clearly inspired by the Django Model classes, it would be nice if it also supported model methods: https://docs.djangoproject.com/en/1.10/topics/db/models/#model-methods

This would allow for easy extension of model classes, updating the model (adding/removing fields) while still maintaining the data contract, etc.

**Comment by funkybob** [comment]
I've just looked at the code for models, and don't see a reason why subclassing Model and adding your own methods won't work.

However, it does look like MetaModel (the metaclass for Model) isn't quite right. I've only ever seen/used them with a __new__ method, never a __init__ method.

**Comment by jpinner-lyft** [comment]
@brandond Model's are subclass-able and you can define your own methods on the subclass:
```
>>> class UserModel(Model):
...     id = NumberAttribute(hash_key=True)
...     first_name = UnicodeAttribute()
...     last_name = UnicodeAttribute()
...
...     @property
...     def full_name(self):
...         return self.first_name + ' ' + self.last_name
... 
>>> user = UserModel(id=1, first_name='John', last_name='Doe')
>>> user.full_name
'John Doe'
```
