### ISSUE TITLE
BooleanAttribute backwards compatibility

### ISSUE THREAD

**Issue by lalvarezguillen** [pynamodb/PynamoDB#255]
Hello. We have been using PynamoDB 1.5.3 for a while, and we've been trying to migrate to 2.x.x lately. I ran into this issue while doing so.

Consider the following model in PynamoDB < 2.0.0

    class Superhero:

        is_superhero = NumberAttribute(hash_key=True, default=1)

        name = UnicodeAttribute(range_key=True, null=False)

        is_cool = BooleanAttribute(default=True)

That would store is_cool on Dynamo using 1 and 0. And we'd be able to query by is_cool in PynamoDB<2.0.0:

    cool_heroes = Superhero.query(1, is_cool__eq=True)
 
If we upgraded to PynamoDB 2.x.x however, and tried to run the previous query on the data we stored using PynamoDB < 2.0.0, the result would be empty.

Getting an entry from DB an then trying to access its is_cool attribute would work in both versions though:

    superman = Superhero.get(1, "Superman")

    print(superman.is_cool)

I'll take a look at PynamoDB's source, but thought I'd report it first.

Cheers

**Comment by yedpodtrzitko** [comment]
Hi,
PynamoDB < 1.6 doesn't store Boolean attribute values as bool. To keep the original behaviour you can use `LegacyBooleanAttribute`. See 1.6 release notes for details: 
https://github.com/pynamodb/PynamoDB/blob/devel/docs/release_notes.rst#v160
