### ISSUE TITLE
Get-Item followed by Save-Item could preserve Item attributes that are not in the Model

### ISSUE THREAD

**Issue by victoreufrasio** [pynamodb/PynamoDB#284]
When we get an item that has attributes which are not present in the Model specification and then save it, those attributes are lost.

Wouldn't be better to preserve those attributes intact?

Ex.:
User Table
name   |   address | age
chris    |   1st street | 27

```python
class User(Model):
    class Meta:
        table_name='User'
    name = UnicodeAttribute(hash_key = True)
    address = UnicodeAttribute(null = True)

u = User.get('chris')
u.address = "2nd street"
u.save()
```

Age is lost:

User Table
name  | address
chris  | 2nd street

**Comment by jpinner-lyft** [comment]
The semantics of DynamoDB's `PutItem` operation (and so of the `save()` method) are that any existing item in the table is replaced with the new item. I believe having PynamoDB's behavior be inconsistent with Dynamo's in this regard would be confusing at best.

You can however use the `UpdateItem` operation to modify an attribute without over-writing other existing fields:
```
u = User('chris')
u.update(actions=[User.address.set("2nd street")])
```
