### ISSUE TITLE
Support Functions for Condition Expressions

### ISSUE THREAD

**Issue by AntonioAngelino** [pynamodb/PynamoDB#288]
Hello,

I need to prevent the override of an existing item. I want to use a conditional expression that takes advantage of the "**attribute_not_exists**" function. 

DDB Doc: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html#Expressions.ConditionExpressions.PreventingOverwrites

Do you plan to support the conditional expression functions (attribute_exists, attribute_not_exists, attribute_type, contains, begins_with, size) ?

**Comment by garrettheel** [comment]
We definitely plan to support the new API and a bunch of us have been discussing this and trying to figure out the best way to implement it. Closing this as a dup of #219; please follow that issue for any updates!
