### ISSUE TITLE
is it possible to change table capacity-units on an already existing model?

### ISSUE THREAD

**Issue by fbrau** [pynamodb/PynamoDB#293]
I mean... does it have something like
MyTable.create_table(read_capacity_units=5, write_capacity_units=5)
but like
MyTable.update_table_specs(read_capacity_units=5, write_capacity_units=5)

**Comment by jmphilli** [comment]
https://github.com/pynamodb/PynamoDB/blob/6d4e120bcd723a5ac9d7500b03a9e8ef8a3ed74e/pynamodb/connection/table.py#L234-L234

**Comment by jmphilli** [comment]
all good @fbrau ???
