### ISSUE TITLE
Strange issue with creating Model instances using multiprocessing.Pool workers

### ISSUE THREAD

**Issue by devangmehta123** [pynamodb/PynamoDB#318]
We have encountered a strange issue with creating Model instances when we use multiprocessing.Pool workers. It seems to be threading issue but Pool workers are in separate processes, so we are confused.

The problem starts in 3.0.1 and is also present in 3.1.0.

We are creating several instances of a Model using Pool.starmap(). Everything seems fine until we try to access an attribute of the model. Note, that until this time, we have not done a Model.save(), so we do not expect any interaction with network or dynamo.

Then we get this error.
 
  File "/usr/local/lib/python3.5/dist-packages/pynamodb/attributes.py", line 48, in __get__
    attr_name = instance._dynamo_to_python_attrs.get(self.attr_name, self.attr_name)
AttributeError: 'NoneType' object has no attribute 'get'

We noted some interesting facts about this.

Even a slight time delay seems to fix this problem. So, it is hard to reproduce with breakpoints. Somone from our team debugged it and introduced this hack which seems to fix it.

Our python is version 3.5.2, botocore is 1.5.90.

See code snippet below which shows our hack.

```
                with Pool(processes=options.get("workers")) as pool:
                    items = pool.starmap(index_map_function,
                                         ((x, options) for x in inputs_by_date[date_string]))
                    # TODO: this is hack, because multiprocessing doesn't work well, example:
                    #   File "/usr/local/lib/python3.5/dist-packages/pynamodb/attributes.py", line 48, in __get__
                    #     attr_name = instance._dynamo_to_python_attrs.get(self.attr_name, self.attr_name)
                    # AttributeError: 'NoneType' object has no attribute 'get'
                    sleep(1)
                    for item in items:
                        item._initialize_attributes()
```

**Comment by garrettheel** [comment]
I think this is probably related to how we did lazy initialization of models. This has been changed a little in `3.2.0` (being released today), can you give it another try there and see if it's fixed? A quick look at how this works suggests it would be (assuming the Model has been imported before your `with` statement)

**Comment by garrettheel** [comment]
Closing this for now. Please feel free to re-open if you try my suggestion and it doesn't work!
