### ISSUE TITLE
Expected behaviour for UTCDateTimeAttribute.serialize(None)

### ISSUE THREAD

**Issue by FWirtz** [pynamodb/PynamoDB#340]
I am currently running into troubles when calling `UTCDateTimeAttribute.serialize(None)`.
`UnicodeAttribute` and `NumberAttribute` both work fine when calling `.serialize(None)`, though they have different outputs (see below).

What should be the expected behaviour of `UTCDateTimeAttribute.serialize(None)`? I would prefer it to not throw an Exception as it breaks my tests.
Would returning e.g. `None` be a viable option?

### Extensive example
```
>>> UnicodeAttribute().serialize(None)
>>> NumberAttribute().serialize(None)
'null'
```
For `UTCDateTimeAttribute` however this happens:
```
>>> UTCDateTimeAttribute(None).serialize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: serialize() missing 1 required positional argument: 'value'
>>> UTCDateTimeAttribute().serialize(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ping/.pyenv/versions/ts-cloud/lib/python3.6/site-packages/pynamodb/attributes.py", line 387, in serialize
    if value.tzinfo is None:
AttributeError: 'NoneType' object has no attribute 'tzinfo'
```

Might be related to #33

**Comment by jmphilli** [comment]
hey @FWirtz we're considering deprecating this attribute in a future version of pynamo. 
my suggestion is to extend this attribute and add the `None` check to your `FWirtzUTCDateAttribute` or whatever you want to call it. 
we talked about it and couldn't decide on a clear path forward here... if we allow it to check for and return `None` then it makes the deserialization more complex as well.
