### ISSUE TITLE
Update pip release

### ISSUE THREAD

**Issue by Gatisseja** [pynamodb/PynamoDB#347]
Significant changes have been made to Model.py query method to warrant a re-release to pip since 3.1.0 on 2017/07/07. 
https://github.com/pynamodb/PynamoDB/blame/master/pynamodb/models.py

 Can we please release a new version? 
@jlafon

**Comment by gtseres** [comment]
@jlafon I second that. This would be of great value

**Comment by jpinner-lyft** [comment]
The latest release candidate (3.2.0rc2) should now be available via pip:
```
$ pip show pynamodb
Name: pynamodb
Version: 3.2.0rc2
...
```
