### ISSUE TITLE
Support for inheritance between models

### ISSUE THREAD

**Issue by eapolinario** [pynamodb/PynamoDB#361]
Right now it is not possible to have a model `Foo` inherit from model `Bar`, i.e.:

```python
class Bar(Model):
    class Meta:
        table_name = 'bar_table'
...

class Foo(Bar):
    class Meta:
        table_name = 'foo_table'
...
```

Apparently the connection to the underlying tables is cached between these two models, which causes accesses to `Foo` to refer to the table 'bar_table' instead of 'foo_table'.

**Comment by helveticafire** [comment]
@eapolinario have a look at https://github.com/pynamodb/PynamoDB/issues/164 which should shed some light on what you are suggesting.
