### ISSUE TITLE
query filters and conditional delete not working

### ISSUE THREAD

**Issue by gopalsareen** [pynamodb/PynamoDB#365]
I am trying to filter the query results using hash and range key, but filters aren't working properly. Am facing the same issue with conditional operations(Delete item).  I tried using the same code provided in examples but it just doesn't check for conditions.

**Comment by stickystyle** [comment]
I just ran into this as well, it looks like the version published on pip doesn't have filters working. Installing the 3.2.0rc1 version from github worked for me, `pip install git+https://github.com/pynamodb/PynamoDB#egg=3.2.0rc1`

There is an issue to update the version here https://github.com/pynamodb/PynamoDB/issues/347

**Comment by jpinner-lyft** [comment]
@stickystyle is correct -- you need to use a 3.2 release -- the latest (3.2.0rc2) is now on pypi
