### ISSUE TITLE
Saving Conditions in List/ Dict before passing them to scan/ query

### ISSUE THREAD

**Issue by kappa90** [pynamodb/PynamoDB#394]
With the legacy filter conditions, I could save conditions to a dict before passing them to a scan/ query operation.

For example:

```
filters = {'attribute__eq': 'value'}
if condition:
    filter.update({'attribute2__eq': 'value2'})
Model.scan(filters)
```

With the new Conditions, I can't find a way to do this. Is this still possible?

**Comment by jpinner-lyft** [comment]
@kappa90 You can still create (and reuse) the filter condition before passing it to the operation, but you no longer need a dictionary:
```
filters = Model.attribute == 'value'
if condition:
    filters &= Model.attribute2 == 'value2'
Model.scan(filter_condition=filters)
```
