### ISSUE TITLE
read/write capacity units needing to be defined for global secondary indexes

### ISSUE THREAD

**Issue by chuckoy** [pynamodb/PynamoDB#401]
I was going through the documentation here https://pynamodb.readthedocs.io/en/latest/indexes.html, specifically: 
> For Global secondary indexes, the read_capacity_units and write_capacity_units also need to be provided.

I was wondering how this would work if we had auto scaling set up on the secondary indexes and the units defined in the code versus the actual units provisioned got out of sync... does anybody know what would happen?

**Comment by jpinner-lyft** [comment]
The values are only used when calling `create_table`. If auto scaling modifies the actual provisioned units, the units defined in the Meta class are unchanged (but unused).

**Comment by chuckoy** [comment]
Awesome, thanks for the reply! Was worried it might be a blocker for me as I'm using CFN templates to create my tables.
