### ISSUE TITLE
Same name different attribute type

### ISSUE THREAD

**Issue by intoxicated** [pynamodb/PynamoDB#402]
Is it possible to have dynamic attribute type in pynamodb? For instance, User.meta is json string but newly created User.meta is map attribute. Fields in db can be migrated into same type, but I would like to know if it is supported. Thanks

**Comment by jpinner-lyft** [comment]
The provided attributes do not have the ability to dynamic deserialize based upon the type of the value in the table. You could however write your own attribute subclass with a custom deserialization method that would handle both json strings and dictionaries.
