### ISSUE TITLE
bump botocore for 4.x release

### ISSUE THREAD

**Issue by scode** [pynamodb/PynamoDB#407]
In #405 we bumped botocore for developers because newly introduced integration tests surfaced https://github.com/boto/botocore/issues/1079

We chose to not touch `requirements.txt` at the time because it would effectively be a breaking change for consumers.

This issue is to follow-up and actually bump it up to `>=0.6.0` in `setup.py` and put `0.6.0` in `requirements.txt` for a 4.0.0 release (and remove the comments in `requirements-dev.txt`).

**Comment by asottile** [comment]
`requirements.txt` isn't packaged -- changing it doesn't affect consumers at all.  And [`setup.py` already allows newer versions](https://github.com/pynamodb/PynamoDB/blob/8ab34d01a59c5347858c301a433987cd19c7702c/setup.py#L16) -- `pip` (without any constraints) will automatically pick the _latest version_ (at the time of writing 1.9.3)

**Comment by scode** [comment]
cc @jpinner-lyft who I think wanted it this way.

**Comment by scode** [comment]
The point might  be to keep requirements.txt and setup.py in sync

**Comment by asottile** [comment]
The general best practice for _libraries_ is to not have a `requirements.txt` at all (maybe including dev-only requirements in a requirements-dev.txt for installation convenience) -- contrasted with applications where a `requirements.txt` should pin *all* dependencies.  Here's [a little more on this subject](https://github.com/Yelp/requirements-tools#our-stance-on-pinning-requirements)

**Comment by scode** [comment]
In any case, I think the main point here is `setup.py` (backwards compatibility issue). I'm neutral/non-opinionated about the policy for `requirements.txt`; don't disagree with what you're saying, but the precedent at the time was that we had it, so this issue mentions both.

**Comment by jpinner-lyft** [comment]
closed in https://github.com/pynamodb/PynamoDB/pull/580
