### ISSUE TITLE
Detail Documenation needs

### ISSUE THREAD

**Issue by intoxicated** [pynamodb/PynamoDB#411]
I'm pretty new to Pynamodb, and I believe there's plenty of room for documentation improvement. For example, I had to use filter query with date range. I couldn't not find any a specific example or usage how to filter query in docs. In fact, I found legacy condition operator "createdAt__between=[start, end]". But pynamodb have some other parameters to deal with thing like this with range_key_condition or filter_condition. But in documentation, it didn't describe what those parameters should be.

**Comment by intoxicated** [comment]
Ok, I found Condition instance in expressions folder which didn't mention in docs at all entirely. I wonder `Between("updatedAt", start, end)` would be enough to do such query. I tried this and got `AttributeError: 'str' object has no attribute 'serialize'` error tho..

**Comment by jpinner-lyft** [comment]
Have you taken a look at the documentation site? http://pynamodb.readthedocs.io/

There is an example for querying with a condition filter:
http://pynamodb.readthedocs.io/en/latest/quickstart.html#querying

In addition more complete condition expression documentation is available:
http://pynamodb.readthedocs.io/en/latest/conditional.html

As for using a `between` filter, the example in the documentation is: `Thread.views.between(1, 5)`
where `views` is the attribute and `1` and `5` are the `start` and `end` parameters.

**Comment by intoxicated** [comment]
those operators `between` applies identical to index querying? like Thread.index.query(hashKey).between(1, 5) ?

**Comment by jpinner-lyft** [comment]
The operators also apply to index queries: http://pynamodb.readthedocs.io/en/latest/indexes.html#querying-an-index

`Thread.index.query(hashKey, Thread.range_attr.between(1, 5))`
