### ISSUE TITLE
UserWarning: Legacy attribute updates are deprecated in favor of update actions

### ISSUE THREAD

**Issue by medwig** [pynamodb/PynamoDB#415]
I'm struggling to find information about this warning: 

UserWarning: Legacy attribute updates are deprecated in favor of update actions
  warnings.warn("Legacy attribute updates are deprecated in favor of update actions")

The code that triggers it is:
```
update_dict = {k: {'action': 'put', 'value': v} for k, v in data.items()}
db_item.update(update_dict)
```

What's the correct way to refactor this?

**Comment by jpinner-lyft** [comment]
Hi @medwig the corresponding update expression version of this code would be something like:
```
update_actions = [getattr(DBItem, k).set(v) for k, v in data.items()]
db_item.update(actions=update_actions)
```
where `DBItem` is the model class of `db_item`.

For more thorough documentation on the different types of update expressions, see http://pynamodb.readthedocs.io/en/latest/updates.html
