### ISSUE TITLE
BinarySetAttribute broken when using Python 3

### ISSUE THREAD

**Issue by Dunedan** [pynamodb/PynamoDB#420]
I noticed the `BinarySetAttribute` is broken when using Python 3.

Assume you have the following model:

```python
from pynamodb.attributes import BinarySetAttribute, UnicodeAttribute
from pynamodb.models import Model

class TestModel(Model):
    class Meta:
        table_name = 'test-table'
        region = 'eu-central-1'

    id = UnicodeAttribute(hash_key=True)
    binset = BinarySetAttribute()
```

I can add items just fine with Python 2 and Python 3 using:

```python
TestModel(id='1', binset={b'foo'}).save()
```

However, when I try to get items again with the following code, it only works with Python 2:

```python
TestModel.get('1')
```

With Python 3 I get the following exception instead:

```
Traceback (most recent call last):
  File "./foo.py", line 15, in <module>
    TestModel.get("1")
  File "/tmp/binsettest/lib/python3.6/site-packages/pynamodb/models.py", line 474, in get
    return cls.from_raw_data(item_data)
  File "/tmp/binsettest/lib/python3.6/site-packages/pynamodb/models.py", line 507, in from_raw_data
    kwargs[attr_name] = attr.deserialize(attr.get_value(value))
  File "/tmp/binsettest/lib/python3.6/site-packages/pynamodb/attributes.py", line 332, in deserialize
    return set([b64decode(val.encode(DEFAULT_ENCODING)) for val in value])
  File "/tmp/binsettest/lib/python3.6/site-packages/pynamodb/attributes.py", line 332, in <listcomp>
    return set([b64decode(val.encode(DEFAULT_ENCODING)) for val in value])
AttributeError: 'bytes' object has no attribute 'encode'
```

I tried it out with PynamoDB 3.1.0 and 3.2.1 and both show the same issue.

**Comment by r5sec5cyl** [comment]
I believe it may have to do with how boto3 handles Binary data types - it seems to be made for Python 2 not Python 3. In Python 2 str and bytes were treated similarly, but not in Python 3. boto3's Binary type provides a `str` output but outputs type `bytes`. In Python 2 this will be fine as it will cast it to a str, but Python 3 treats them differently. `b64decode(val.encode(DEFAULT_ENCODING))` relies on val having an encode function. Since val is `bytes`, it has the necessary function in Python 2, but not in Python 3.

**Comment by r5sec5cyl** [comment]
Also, shouldn't that line use **de**code instead of **en**code:
```return set([b64decode(val.decode(DEFAULT_ENCODING)) for val in value])```
instead of 
```return set([b64decode(val.encode(DEFAULT_ENCODING)) for val in value])```

**Comment by betamoo** [comment]
This has been fixed in https://github.com/pynamodb/PynamoDB/pull/480
