### ISSUE TITLE
Querying Global Secondary Index Range Key is not working 

### ISSUE THREAD

**Issue by valeriyaxref** [pynamodb/PynamoDB#429]
Hi!

I'm trying to count GSI based on hash key and range key:

```
from pynamodb.indexes import GlobalSecondaryIndex, AllProjection

class MyIndex(GlobalSecondaryIndex): 
    class Meta:
        index_name = 'IndexName'
        projection = AllProjection()

    field_name = NumberAttribute(range_key=True)
    index_hash_field = NumberAttribute(hash_key=True)
 
class MyTable(Model):  
    class Meta:
        table_name = 'TableName'

    field_name = NumberAttribute()
    table_hash_field = NumberAttribute(hash_key=True)
    table_index = MyIndex()


result = MyTable.table_index.count(100, MyTable.field_name == 200)
```

But as a result I get the same value that I have for MyTable.table_index.count(100), without conditions on the range key of the index.
Looks like range key condition does not work.
Or I'm doing something wrong. 

It seems that what I intend to be the range_key filter is actually being parsed by pynamodb as the positional argument `consistent_read`. When I try to add another filter, it throws a `TypeError` saying `count() takes at most 3 arguments (4 given)`.

Thanks!

**Comment by nsosamontevideolabs** [comment]
Your hash_key attribute in MyIndex does not exist in the table attributes. That might explain why it doesn't work

**Comment by ikonst** [comment]
Thanks @nsosamontevideolabs !
