### ISSUE TITLE
how do you append to a list of map attributes?

### ISSUE THREAD

**Issue by knap1930** [pynamodb/PynamoDB#434]
http://pynamodb.readthedocs.io/en/latest/attributes.html#list-attributes

My guess would be like this, but it does not work?
```
emp5 = OfficeEmployeeMap(
    office_employee_id=555,
    person='derek'
)

Office(
    office_id=3
).update(
    actions=[
        Office.employees.append([emp5])
    ]
)
```

ValueError: unsupported action type: '_ListAppend'"

**Comment by knap1930** [comment]
figured it out... feel free to close. may also consider adding it to the examples.

```
Office(
    office_id=3
).update(
    actions=[
        Office.employees.set(Office.employees.append([emp5]))
    ]
)
```

**Comment by knap1930** [comment]
now I need to figure out how to handle the case where employees does not exist...

need to combine list_append, and if_not_exists. is this possible?

```
'SET my_list2 = list_append(if_not_exists(my_list2, :empty_list), :my_value)'
```

**Comment by knap1930** [comment]
This works...

```
Office(
    office_id=3
).update(
    actions=[
        Office.employees.set((Office.employees|[]).append([emp5]))
    ]
)
```

**Comment by rschmidtz** [comment]
@knap1930 this was really helpful, thanks for share

**Comment by jl-DaDar** [comment]
doesn't seem to work for me. I got this error when appending
when calling the UpdateItem operation: The provided expression refers to an attribute that does not exist in the item

i do have the attribute.

**Comment by YukSeungChan** [comment]
Thanks :D

**Comment by dedominicisfa** [comment]
Happy that it worked for you, I have a None is not iterable error in pynamodb attributes.py. COld you please post a small example that works?

**Comment by knap1930** [comment]
@dedominicisfa if you paste the code above in to the example code at https://github.com/pynamodb/PynamoDB/blob/master/docs/attributes.rst#list-attributes it should just work...

**Comment by jin09** [comment]
This clearly shows the need for better explanation and examples in the Pynamodb documentation
