### ISSUE TITLE
Filters for attributes of type List or Map in Query or Scan operation

### ISSUE THREAD

**Issue by 3dw1np** [pynamodb/PynamoDB#435]
I would like to scan my dynamodb table with a filter on a specific attribute inside a map attribute:

```
class Email(MapAttribute):
    address = UnicodeAttribute()
    ....

class ProfileModel(Model):
    email = Email()
    ...
```

I am still using the old way to make the conditional operation but I get an error while I am doing this:

```
ProfileModel.scan(email.address__contains='gmail')
```

`
  File "/var/task/pynamodb/models.py", line 761, in scan
    filters=filters
  File "/var/task/pynamodb/models.py", line 1019, in _build_filters
    raise ValueError("Attribute {0} specified for filter does not exist.".format(attr_name))
ValueError: Attribute email.address_contains specified for filter does not exist.
`

Is it a limitation of Dynamodb API ?

**Comment by jpinner-lyft** [comment]
This is a limitation of the deprecated legacy conditional operator api (which has been removed in the upcoming 4.0 release). You can achieve this using the new expression api: `ProfileModel.email.address.contains('gmail')`
