### ISSUE TITLE
Dynamically building queries

### ISSUE THREAD

**Issue by kevgliss** [pynamodb/PynamoDB#444]
Similar to:
https://stackoverflow.com/questions/48089051/python-pynamodb-creating-dynamic-queries-with-flask 

Is there any guidance one how we should go about building dynamic queries? Is there a form of query we can pass that lends itself to dynamic building? 

I would have expected something similar to sqlalchemy expressions:
http://docs.sqlalchemy.org/en/latest/core/sqlelement.html

But as far as I can tell similar expressions are not exposed via Pynamodb.

**Comment by pjz** [comment]
I sometimes do things like:
```
    groups = [ "admin", "user", "development", "operations", "marketing" ]
    condition = None
    for g in groups:
         newcond = UserClass.groups.contains(g)
         condition = newcond if condition is None else condition | newcond
```

**Comment by asdrubalsantander** [comment]
I find this way:
```python
from functools import reduce
from pynamodb.expressions.condition import And

filter_conditions = []

filter_conditions.append(PynamodbModel.attr1 == 'value1')
filter_conditions.append(PynamodbModel.attr2.contains('value2'))
filter_conditions.append(PynamodbModel.attr3.exists())

query = CommentModel.query(
    hash_key='my_hash_key',
    filter_condition=reduce(And, filter_conditions)
)
```
