### ISSUE TITLE
InsertOrUpdate operation?

### ISSUE THREAD

**Issue by alexanderfanz** [pynamodb/PynamoDB#446]
Hi, I'm wondering if there is a way to perform an insert_or_update operation.

I have two process that compute different attributes for the same item, and I would like to put the result in the same table, but without asking if exist.

My code is like this:
```

from pynamodb.attributes import UnicodeAttribute
from pynamodb.models import Model


class Model1(Model):
    class Meta:
        table_name = 'test'

    pk = UnicodeAttribute(hash_key=True)
    sk = UnicodeAttribute(range_key=True)
    v1 = UnicodeAttribute()


class Model2(Model):
    class Meta:
        table_name = 'test'

    pk = UnicodeAttribute(hash_key=True)
    sk = UnicodeAttribute(range_key=True)
    v2 = UnicodeAttribute()

```
and I would like to perform this two calls in any order, even one (or both) of them multiple times
```
item = Model1('123', '123', v1='value1')
item.insertorupdate() # or any possible way
item.save()

```

```
item = Model2('123', '123', v2='value2')
item.insertorupdate()
item.save()
```

and obtain the same result in dynamodb:

```
  pk                sk              v1              v2
'123'             '123'           'value1'        'value2' 
```

Thanks in advance

**Comment by menge101** [comment]
I think i just replied to you on the PynamoDB group.

Take a look at:
http://pynamodb.readthedocs.io/en/latest/updates.html

The first line of that page: "The UpdateItem DynamoDB operations allows you to *create or modify* attributes of an item using an update expression."

**Comment by menge101** [comment]
I threw this together in unittest:


    def test_update_with_no_create(self):
        PynamoTestModel.create_table(read_capacity_units=1, write_capacity_units=1, wait=True)
        x = PynamoTestModel('test1').update(actions=[PynamoTestModel.description.set('hi')])
        y = PynamoTestModel.get('test1')
        z = PynamoTestModel('test1').update(actions=[PynamoTestModel.start_time.set(datetime.now())])
        a = PynamoTestModel.get('test1')

**Comment by alexanderfanz** [comment]
Thank you very much, with that I found what I was looking for

### Place 1:
```
class Model1(Model):
    class Meta:
        table_name = 'my_table'

    pk = UnicodeAttribute(hash_key=True)
    v1 = UnicodeAttribute()
```
```
item1 = Model1('123')
item1.update(actions=[Model2.v2.set('value2')])
```

### Place 2:
```
class Model2(Model):
    class Meta:
        table_name = 'my_table'

    pk = UnicodeAttribute(hash_key=True)
    v2 = UnicodeAttribute()
```

```
item2 = Model2('123')
item2.update(actions=[Model2.v2.set('value2')])
```

work in different places with different models on the same table with the same items ;)
Thanks a lot
