### ISSUE TITLE
Indexes support a `.get` method

### ISSUE THREAD

**Issue by garrettheel** [pynamodb/PynamoDB#453]
It would be great if `Index`es supported a `.get`, like `Model`s do, as a convenience method.

The workaround is to do `.query(..., limit=1)`.

**Comment by jpinner-lyft** [comment]
@garrettheel not sure what you want the return to be here -- `get` usually returns the item or raises an exception, but for indexes you are not guaranteed uniqueness so you'd either have to choose the "first" one (as in your example) or return an iterator

**Comment by garrettheel** [comment]
Yep, this was a misunderstanding on my part. From the docs:

> In a DynamoDB table, each key value must be unique. However, the key values in a global secondary index do not need to be unique. To illustrate, suppose that a game named Comet Quest is especially difficult, with many new users trying but failing to get a score above zero. The following is some data that could represent this.

Closing this one, since it doesn't make sense.
