### ISSUE TITLE
Fix the use of scan_filter

### ISSUE THREAD

**Issue by pjz** [pynamodb/PynamoDB#461]
According to [DynamoDB Docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html), ScanFilter aka scan_filter is a "legacy parameter" and FilterExpression should be used instead.

Personally, I found the existence of both to be confusing.  It's not Pynamo's fault - AWS is supporting both for legacy reasons - but Pynamo users could be less confused if that arg wasn't passed through.

For backwards compatability, I suggest turning any filters passed in as a 'scan filter' into a filter_expression, by ANDing them all together.  This will preserve the functionality while making it clear what's actually going on.

**Comment by jpinner-lyft** [comment]
The legacy filter parameters have been removed in the upcoming 4.0 release.
