### ISSUE TITLE
Question: Query filtering with many arguments?

### ISSUE THREAD

**Issue by cantoniazzi** [pynamodb/PynamoDB#472]
Hi, guys.

How can I create a query filter with many QueryFilter arguments?

e.g (in sql language): ```SELECT * FROM MY_TABLE WHERE FIELD1=query_param_1 AND FIELD2=query_param_2```....

I'm developing an API and I need to implement a GET route filtering total records where my query clausule will use the all query parameters.

And by the docs I don't understand how i make it.  :~(

Thanks!

**Comment by shadycuz** [comment]
@cantoniazzi Docs for querying https://pynamodb.readthedocs.io/en/latest/quickstart.html#querying
```
for user in UserModel.query('Smith', UserModel.first_name.startswith('J') | UserModel.email.contains('domain.com')):
    print(user)
```

You can also do any type of `and` `or` like...

```
for prev in Image.query(args['app'], (Image.latest==True) & (Image.branch == args['branch'])):
```

**Comment by cantoniazzi** [comment]
@shadycuz Thanks!
