### ISSUE TITLE
Possible to filter a scan() using filters against 2 types?

### ISSUE THREAD

**Issue by brandoconnor** [pynamodb/PynamoDB#490]
Hey there and thanks for this project!

I'm trying to apply 2 filters to a `scan()` operation but it's failing due to type difference as enforced [here](https://github.com/pynamodb/PynamoDB/blob/5fd2ee03fa714a5fa7e41ef5811488617248543a/pynamodb/expressions/condition.py#L28):

```python
DatapointModel.created_at.between(arrow.get(
            '2018-04-12T20:58:07.337829+0000'), arrow.get('2018-04-12T20:58:35.897689+0000')) & DatapointModel.sensor_id == '123abc')
...
TypeError: ("unsupported operand type(s) for &: '{0}' and '{1}'", 'Between', 'UnicodeAttribute')
```

Individually, these filters work as expected. Chained together they fail.

It doesn't look like this is a limitation of `scan()` generally as I can perform this exact query within the dynamo console and it filters as expected. Surely I'm just doing something wrong. Any guidance is appreciated!

**Comment by brandoconnor** [comment]
It would seem the boto3 client supports this: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.Python.04.html#GettingStarted.Python.04.Query.02

From that example:

```python
response = table.query(
    ProjectionExpression="#yr, title, info.genres, info.actors[0]",
    ExpressionAttributeNames={ "#yr": "year" }, # Expression Attribute Names for Projection Expression only.
    KeyConditionExpression=Key('year').eq(1992) & Key('title').between('A', 'L')
)
```

**Comment by brandoconnor** [comment]
Closing as this appears to be an unmaintained project.

**Comment by ParkerD559** [comment]
If anyone stumbles on this, you need parentheses separating conditions so the above should be
```
earliest = arrow.get('2018-04-12T20:58:07.337829+0000')
latest = arrow.get('2018-04-12T20:58:35.897689+0000')
DatapointModel.scan(
    (DatapointModel.created_at.between(earliest, latest))
    & (DatapointModel.sensor_id == '123abc'))
)

```
