### ISSUE TITLE
PynamoDB datastore

### ISSUE THREAD

**Issue by Seluj78** [pynamodb/PynamoDB#495]
Hi there :wave: 

I'd like to use Flask-Security to create a flask app along with my PynamoDB databasde (I can't use another DB, work obligations). 

If i want to use Flask-Security, I need a Datastore, and I can't recreate one (cf. https://github.com/mattupstate/flask-security/issues/774). Do you guys think it's possible to make one for pynamodb ?

**Comment by tomateos** [comment]
Hi @Seluj78

Have you tried using the Model class from PynamoDB? Check this out https://github.com/pynamodb/PynamoDB/blob/3d21f5b907c0b400b1cde7dae4469e47094de556/docs/quickstart.rst. Here they create a UserModel by extending Model. I think most of the methods you have in your codeshare could be implemented as part of this model layer, or as an API that interacts with the model.

In short, yes I think it's possible

**Comment by Seluj78** [comment]
You mean, using this : https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/models.py 
?

**Comment by tomateos** [comment]
Yes, you can create a Model that stores the appropriate information for auth (role, status, etc), then maybe create an API to interact with your Flask service. It's pretty simple to add attributes to a PynamoDB model (just pass them in as kwargs)
