### ISSUE TITLE
query with exclusive_start_key

### ISSUE THREAD

**Issue by mpresh** [pynamodb/PynamoDB#50]
Hello,
I am trying to run a table query by providing the last_evaluated_key int he following format 
exclusive_start_key': {'found': {'S': 'bla'}, 'id': {'S': u'67d54268-dab1-4c73-a424-dbe75d466bb5|subnet-69755941'}}
and I am receiving an error 
127.0.0.1 - - [01/Dec/2014 16:21:38] "GET /api/resources/?limit=25&env=67d54268-dab1-4c73-a424-dbe75d466bb5&last=67d54268-dab1-4c73-a424-dbe75d466bb5|subnet-69755941 HTTP/1.1" 500 -
....
QueryError: Failed to query items: {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided starting key is invalid"}

Any idea if this is supported by Dynamodb. It works fine with scan but doesn't work with query.
I am tryign to figure out if this is a dynamodb issue, a pynamodb issue, or something with my code

Thanks for any help you can provide.
-Mike

**Comment by jpinner-lyft** [comment]
Exclusive Start Key parameter requires hash and range keys of the item for both the table and the index -- it appears that `get_exclusive_start_key_map` doesn't handle this correctly.

**Comment by jpinner-lyft** [comment]
Fixed in https://github.com/pynamodb/PynamoDB/pull/379
