### ISSUE TITLE
ListAttribute behavior with null values

### ISSUE THREAD

**Issue by jney** [pynamodb/PynamoDB#514]
Hello, I have something similar to the following model:

```py
class SingleItem(MapAttribute):
    item_id = UnicodeAttribute()

class Group(Model):
    items = ListAttribute(default=[], of=SingleItem)
    session_id = UnicodeAttribute(hash_key=True)
```

In this way it kind of work. but, if i replace the parameter `default=[]` by `null=True` i've got exceptions while getting a `Group.get("someid")` i got error `TypeError: 'NoneType' object is not iterable`.
Worse, when the `field` is explicitly set to `null (not empty)` in db. everything the record can not me read. same error.

I'm using pynamo 3.3.0

Thank you

**Comment by jakubro** [comment]
@jney Use `default=lambda: []` instead of `default=[]`, since the default value is mutable in your case.

**Comment by luisdemarchi** [comment]
I've got the same issue in pynamodb 3.3.1.

**Comment by jney** [comment]
sorry I didn't reply. I think I solved it with `default=list`, @jakubro's proposition would also work
