### ISSUE TITLE
Referencing other pynamodb objects

### ISSUE THREAD

**Issue by mikekhristo** [pynamodb/PynamoDB#52]
Thanks for the work so for on pynamodb!

What's the best way to reference another pynamodb model when defining a model? For example how would you structure users that could be part of one or more teams where the team also has a reference back to the user that created it?

**Comment by Ryan-K** [comment]
PynamoDB isn't really a relational ORM so you can't quite do things you might be used to with SQLAlchemy or other tools for more traditional datastores.

What you would likely want to do is use the hash key from your Team object and store it as a team_id attribute on your User object. Then, I'd add a team property which returns Team.get(team_id). 

If that's going to be frequently accessed on your User object, storing the team as self._team and only calling Team.get if self._team isn't set will prevent having to query Dynamo to get multiple properties on the team object. Depending on your application, you may also want to do some short term caching for common items to reduce your Dynamo Capacity needs.

I know it's a very delayed response, but hopefully that helps!

**Comment by mojimi** [comment]
> 
> 
> PynamoDB isn't really a relational ORM so you can't quite do things you might be used to with SQLAlchemy or other tools for more traditional datastores.
> 
> What you would likely want to do is use the hash key from your Team object and store it as a team_id attribute on your User object. Then, I'd add a team property which returns Team.get(team_id).
> 
> If that's going to be frequently accessed on your User object, storing the team as self._team and only calling Team.get if self._team isn't set will prevent having to query Dynamo to get multiple properties on the team object. Depending on your application, you may also want to do some short term caching for common items to reduce your Dynamo Capacity needs.
> 
> I know it's a very delayed response, but hopefully that helps!

Well, isn't referencing the id pretty much simulating a foreign key? Is that an okay thing to do?

What happens if a referenced object is deleted, the application needs to handle it?

**Comment by ikonst** [comment]
Since DynamoDB has no concept of foreign keys then, yes, you might try to implement them applicatively. PynamoDB doesn't strive to offer features on top of DynamoDB's features, so we leave emulation of foreign keys to the applications.

**Comment by mikekhristo** [comment]
When I posed the original question 4 years ago, I had no idea of the underlying power dynamodb. I'll just leave this here for future viewers: https://www.youtube.com/watch?v=HaEPXoXVf2k

**Comment by mojimi** [comment]
> 
> 
> When I posed the original question 4 years ago, I had no idea of the underlying power dynamodb. I'll just leave this here for future viewers: https://www.youtube.com/watch?v=HaEPXoXVf2k

I have watched that and a couple other explanations on the adjacency list design pattern.

I don't know if I can't understand it or just can't agree with it, because you end up with such an unnatural and ugly table structure just to save one extra query.

I just find the way they visually represent a DynamoDB table model really confusing.
