### ISSUE TITLE
Proper way to handle schema changes?

### ISSUE THREAD

**Issue by mikegrima** [pynamodb/PynamoDB#532]
Hello!

What is the proper way of handling schema changes?

Namely, if I had the following table:
```
class SomeModel(Model):
    Foo = UnicodeAttribute()
    Bar = UnicodeAttribute()
```
... and changed the schema:

```
class SomeModel(Model):
       Foo = UnicodeAttribute()
```

Adding or removing a field will cause problems when fetching data from this table. If removing a field, PynamoDB will complain that a required field is missing. If adding a field, it will also complain because there is an undefined field.

Is there a way to configure PynamoDB to ignore schematic differences? While that may seem like an anti-pattern, there needs to be a clean way of handling schema changes.

**Comment by leobarcellos** [comment]
I ran into this from time to time, what I usually do is to add a `null=True` or `default` on the new attribute.

And if you use `Model.save()`, PynamoDB will ignore all non defined attributes too. 
However if you use `Model.update()` you will run into this issue too, what I usually do is to check in the instance if already have this new attribute, before updating. (Or in some migration code)

**Comment by benhowes** [comment]
I've been looking in to this a bit too, and it looks like a moderately good method for more complex migrations is documented here: https://stackoverflow.com/a/48053997/145412. That would work for removing data too.

**Comment by mikegrima** [comment]
I'm going to close out this issue.

It looks like there are a number of ways to do this. Unfortunately, they all seem to have a lot of work associated, so best to never make changes to the schema 😂
