### ISSUE TITLE
rate_limited_scan doesn't return ResultIterator 

### ISSUE THREAD

**Issue by szymonhab** [pynamodb/PynamoDB#549]
Hi!

I'm using `last_evaluated_key` for parallel table scanning. 
But `rate_limited_scan()` in `pynamodb.models.py` doesn't return ResultsIterator like normal `scan()` 
I'm not able to reuse that key easily.
  
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.ParallelScan

`def scan():`
![image](https://user-images.githubusercontent.com/10489428/47436506-e7e6b680-d7a6-11e8-9b13-6c83b8948188.png)

`def rate_limited_scan():`
![image](https://user-images.githubusercontent.com/10489428/47436605-1795be80-d7a7-11e8-9d6c-a3cb99ee8b25.png)

Is it intentional?

Thanks in advance!

**Comment by jpinner-lyft** [comment]
The `rate_limited_scan()` function is deprecated and has been removed in the upcoming 4.0 release.
This functionality has been replaced by the `rate_limit` parameter.
see https://pynamodb.readthedocs.io/en/latest/rate_limited_operations.html
