### ISSUE TITLE
Conditional update fails if field is NULL

### ISSUE THREAD

**Issue by ghost** [pynamodb/PynamoDB#55]
I'm trying to do a conditional update on a field that doesn't yet have a value. My code looks something like this

```
thread = Thread.get(thread_uuid)
existing_thread_details = thread.details
thread.update_item(
    attribute='details',
    value='{"owner": "Michael"}',
    action='PUT',
    details__eq=existing_thread_details
)
```

If the `details` field hasn't been set yet, and the model is defined like `details = JSONAttribute(null=True)`,  the above code will fail.

However I've found that if I set a default value of an empty array `details = JSONAttribute(default={})`, the conditional update works.

**Comment by twork-veracode** [comment]
I've discovered that the conditional update also fails if if you have a UnicodeAttribute, not just a JSONAttribute. The traceback is as follows:

```  File "/Users/twork/.virtualenvs/mcp/lib/python2.7/site-packages/pynamodb/models.py", line 344, in update_item
    **kwargs
  File "/Users/twork/.virtualenvs/mcp/lib/python2.7/site-packages/pynamodb/connection/table.py", line 61, in update_item
    return_values=return_values)
  File "/Users/twork/.virtualenvs/mcp/lib/python2.7/site-packages/pynamodb/connection/base.py", line 637, in update_item
    response, data = self.dispatch(UPDATE_ITEM, operation_kwargs)
  File "/Users/twork/.virtualenvs/mcp/lib/python2.7/site-packages/pynamodb/connection/base.py", line 213, in dispatch
    response, data = self.service.get_operation(operation_name).call(self.endpoint, **operation_kwargs)
  File "/Users/twork/.virtualenvs/mcp/lib/python2.7/site-packages/botocore/operation.py", line 115, in call
    request_dict = self.build_parameters(**kwargs)
  File "/Users/twork/.virtualenvs/mcp/lib/python2.7/site-packages/botocore/operation.py", line 256, in build_parameters
    raise ParamValidationError(report=errors.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Expected.scan_activities.AttributeValueList[0].S, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>```

**Comment by jlafon** [comment]
Hi there, I'm trying to reproduce this. Are you passing None as the 'value' argument to update_item?

**Comment by twork-veracode** [comment]
Hey looks like you got this figured out?

Tobias Work | Senior Software Engineer
Veracode, Inc. | twork@veracode.com<mailto:twork@veracode.com>



On Apr 3, 2015, at 10:26 AM, Jharrod LaFon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there, I'm trying to reproduce this. Are you passing None as the 'value' argument to update_item?

**Comment by jpinner-lyft** [comment]
This should work using DynamoDB's condition expression api
```
thread = Thread.get(thread_uuid)
existing_thread_details = thread.details
thread.update(
    actions=[
        Thread.details.set({"owner": "Michael"})
    ],
    condition=(Thread.details == existing_thread_details)
)
```

**Comment by shahabyounas** [comment]
@jpinner-lyft  How can we manage optional fields, when update condition changes.  Lets say in some cases a user intend to update `details` only and in other case update all the fields 
`thread = Thread.get(thread_uuid)
existing_thread_details = thread.details
thread.update(
    actions=[
        Thread.another1.set({"newfield1": "x"})
        Thread.another2.set({"newfield2": "x"})
        Thread.details.set({"owner": "Michael"})
    ],
    condition=(Thread.details == existing_thread_details)
)`

**Comment by dcy0577** [comment]
> 

Hi did you figure it out?

**Comment by dcy0577** [comment]
> @jpinner-lyft How can we manage optional fields, when update actions get change. Lets say in some cases a user intend to update `details` only and in other case update all the fields
> 
> ```
> thread = Thread.get(thread_uuid)
> existing_thread_details = thread.details
> thread.update(
>     actions=[
>         Thread.attributeX.set({"foo": "x"})
>         Thread.attributeY.set({"bar": "Y"})
>         Thread.details.set({"owner": "Michael"})
>     ],
>     condition=(Thread.details == existing_thread_details)
> )
> ```

Hi, did you figure it out?

**Comment by ikonst** [comment]
One thing to keep in mind: PynamoDB operations mirror the underlying DynamoDB operations, e.g. when you invoke `update`, all we do is make one call to the [UpdateItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) API.

UpdateItem supports something similar to what you're asking for, in the form of the `if_not_exists` function:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-AttributeUpdates

For the PynamoDB equivalent, see the `if_not_exists` example here:
https://pynamodb.readthedocs.io/en/latest/updates.html#update-expressions
