### ISSUE TITLE
virtual attribute

### ISSUE THREAD

**Issue by jney** [pynamodb/PynamoDB#560]
hi, could you tell me what's the way to go to have virtual attributes (attributes used in the python model but not saved to dynamo)?
i tried using python getter/setter but it does not look to work. i did it this `NullAttribute`, is it really the way to go?

**Comment by mikegrima** [comment]
Taking a stab in the dark... Would Python class properties work?

**Comment by jney** [comment]
> disclaimer: python is not my primary language 

I did something like this and it didn't work:

```py
@property
def prop(self):
    return self.__prop
    
@prop.setter
def prop(self, val):
    self.__prop = val
```

**Comment by ikonst** [comment]
You should be able to use regular class attributes. Unless an attribute is derived from `pynamodb.attributes.Attribute`, it is not treated as anything special by pynamodb.

**Comment by willtraweek** [comment]
is there a way to use python properties with anything that does end up in dynamo?  I'd like to have more control over how attributes are set before they enter the database
