### ISSUE TITLE
pynamodb stubs in typeshed

### ISSUE THREAD

**Issue by srittau** [pynamodb/PynamoDB#573]
I am one of typeshed's maintainers. I noticed that pynamodb now ships with its own stubs, which is of course preferable to shipping them in typeshed. Do you see any issues with us removing the stubs from typeshed?

**Comment by garrettheel** [comment]
Hey @srittau, thanks for bringing this up! I actually haven't cut a new release that includes the stubs yet, however the typeshed stubs are already out of date and that will continue to worsen over time.

I believe quite a few people are relying on typeshed for these right now and removing it would impact their workflow. Would it be okay if I cut a release shortly to introduce the stubs and we remove them from typeshed in 3 months or so? This should give consumers adequate time to upgrade.

I'm open to other options if you have them. Thanks!

**Comment by srittau** [comment]
Sounds like a good plan. We should probably wait for one or two mypy/pytype releases before removing them from typeshed, after the pynamodb release has been cut. This would most likely work out to about 3 months or so.

**Comment by garrettheel** [comment]
Great, I just cut a new version (3.3.2) containing the stubs so we can circle back after a couple of mypy/pytype releases. Thanks again!

**Comment by garrettheel** [comment]
@srittau just circling back here, I think we've shipped the stubs long enough that it makes sense to remove them from typeshed. Let me know if you'd like me to open a PR for that!

**Comment by srittau** [comment]
@garrettheel Sure, that would be great!

**Comment by garrettheel** [comment]
Sorry for losing track of this one. https://github.com/python/typeshed/pull/4917 has been created, so I'll close this issue
