### ISSUE TITLE
Batch update

### ISSUE THREAD

**Issue by pedromachados** [pynamodb/PynamoDB#591]
Is it possible to do a batch update passing multiple items in a single operation? My use case is to do an upsert of multiple items. I understand that `save` will overwrite existing items so was trying to accomplish the same with an update.

**Comment by iraabbott** [comment]
Hi,

I am new to pynamodb, but can comment from reading the docs in DynamoDB that AWS doesn't support the operation you are asking about in the underlying API.  [https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html](url)

'batch' and 'transact' operations combine 'get_item' and 'put_item' operations (although they are called 'batch_write_item' and 'transact_write_item'), their is no similar 'batch_update' request to update single fields in multiple records simultaneously, so any attempt by pynamodb to support an operation like this would both not achieve the efficiency you want and also introduce potential consistency issues.

**Comment by pedromachados** [comment]
Got it. Thanks!

**Comment by hallie** [comment]
@pedromachados pynamodb 4.0.0 will include support `TransactWrite`, which includes the ability to `update` multiple items in one operation :0 hope that helps!
