### ISSUE TITLE
Is there anyway to inject local dynamo db client to models through pytest?

### ISSUE THREAD

**Issue by akashg90** [pynamodb/PynamoDB#595]
Hi All,

I am trying run functional test on pynamodb model through pytest. I am using fixtures to start dynamo db on local. But I am failing to inject local client created by fixtures to pynamodb client. 

Please help me with this issue. 

Thanks,
Akash Gupta

**Comment by ikonst** [comment]
What I’d typically do is set the DynamoDB hostname from an environment variable.

**Comment by ikonst** [comment]
You can always add something like this to conftest.py. Perhaps there should be an easier way to override it.

```py
def patch_dynamodb_host():
    from pynamodb.connection import TableConnection
    original_init = TableConnection.__init__

    def init(*args, **kwargs):
        kwargs['host'] = 'http://localhost:8000'
        return original_init(*args, **kwargs)

    TableConnection.__init__ = init


patch_dynamodb_host()
```

**Comment by JCapriotti** [comment]
I stumbled on this old issue... currently, you can set the host in the `Meta` class, which would allow use of an environment variable:

```python
class YourModel(Model):
    class Meta:
        host = 'http://localhost:8000'
```

**Comment by ikonst** [comment]
It doesn't seem to be an active issue so I'd be closing this.
