### ISSUE TITLE
UnrecognizedClientException 

### ISSUE THREAD

**Issue by venkateshanbalagan** [pynamodb/PynamoDB#603]
We are getting this exception. Do you have any solution?

conn = TableConnection('Request', aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
                       aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"])
conn.describe_table()

pynamodb.exceptions.VerboseClientError: An error occurred (UnrecognizedClientException) on request (9H9CMALLM6AC4E94UOHEQUNV2NVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (Request) when calling the DescribeTable operation: The security token included in the request is invalid

**Comment by mattjegan** [comment]
This error will occur when either the AWS credentials are non-existent or incorrect. Have you made sure to populate your environment with the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variables?

**Comment by venkateshanbalagan** [comment]
This error finally was resolved by providing session_token. We had override the tableconnection.__init__ to take session token and pass it on to connection.session.set_credentials

**Comment by San-kalp** [comment]
@venkateshanbalagan can you please provide the code snippet as well regrading how the error was resolved. Thanking you in advanvce.
