### ISSUE TITLE
Expose private helpers as public

### ISSUE THREAD

**Issue by emise** [pynamodb/PynamoDB#614]
Sometimes it would be helpful to build DynamoDB json using a PynamoDB model for unsupported features, such as Transactions. Could we surface these methods, i.e.

[`_get_json`](https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/models.py#L1174-L1185),
`_get_meta_data`,
`_serialize_value`,
`_hash_key_attribute`,

etc. as public methods?

Suggestion is to remove the `_` and document them in the documentation.

**Comment by garrettheel** [comment]
Exposing these methods publicly would mean we'd need to document them and a lot of what should be internal-only changes would now require a major release. I can certainly see a case being made for exposing some data that we currently don't publicly, however making these public doesn't align well with the goals and level of abstraction of this project.

I'd suggest using the private methods sparingly and carefully, if necessary, while support for new DynamoDB features is added.
