### ISSUE TITLE
Why does scan use generator not iterator?

### ISSUE THREAD

**Issue by jl-DaDar** [pynamodb/PynamoDB#619]
How come scan and rate_limited_scan uses generator and not iterator like query?
I am forced to handle pagination differently right now.

**Comment by ikonst** [comment]
Generators are iterators. Could you illustrate the difference with some sample code perhaps?

**Comment by jl-DaDar** [comment]
well, I am trying to get last_evaluated_key from the scan, but because it uses generator not resultIterator, I cannot use the same way that I use for query

**Comment by jpinner-lyft** [comment]
Which version of pynamodb are you using? On the latest version `scan` returns a `ResultIterator`.
`rate_limited_scan` still yields values but is deprecated. Use the `rate_limit` parameter in the `scan` function.
