### ISSUE TITLE
Support for On Demand mode and Global Secondary Indexes

### ISSUE THREAD

**Issue by techdragon** [pynamodb/PynamoDB#629]
The current code has incomplete support for the On Demand billing mode of DynamoDB. 

The notes around the launch state that the indexes inherit the On Demand mode from their tables.

https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/

> Indexes created on a table using on-demand mode inherit the same scalability and billing model. You don’t need to specify throughput capacity settings for indexes, and you pay by their use. If you don’t have read/write traffic to a table using on-demand mode and its indexes, you only pay for the data storage. 

But the code currently throws an error `AttributeError: type object 'Meta' has no attribute 'read_capacity_units'` when trying to make a Global Secondary Index on a table using the On Demand mode.

**Comment by 3dw1np** [comment]
Any update on this ?

**Comment by ikonst** [comment]
Haven't had a chance to address this yet.

**Comment by sreid** [comment]
Curiosity question: Ignoring the ability to create tables, if I put in arbitrary values in for the `read_capacity_units`/`write_capacity_units` for an existing table, will it affect the query execution in any way?

**Comment by ikonst** [comment]
No, `read/write_capacity_units` are only used for provisioning table _if_ you choose to use PynamoDB for provisioning. Otherwise, they're unused.

I think we should consider making them optional and only raising an error if and when you choose to invoke `create_table`.

**Comment by 3dw1np** [comment]
I hope the bug can be fixed before the release of v4.0 :)

**Comment by 3dw1np** [comment]
But even when I remove the read and write capacity in the Meta of a Model (v3.4.1).
I've got this error:

```
TableError: Failed to create table: Parameter validation failed:
Invalid type for parameter ProvisionedThroughput.WriteCapacityUnits, value: None, type: <type 'NoneType'>, valid types: <type 'int'>, <type 'long'>
Invalid type for parameter ProvisionedThroughput.ReadCapacityUnits, value: None, type: <type 'NoneType'>, valid types: <type 'int'>, <type 'long'>
```

@techdragon Did u apply a patch commit to enabling the on-demand mode capacity?

**Comment by ikonst** [comment]
As I said, those parameters _do_ affect `create_table`.

**Comment by 3dw1np** [comment]
@ikonst I deleted the tables and I re-created them, I was thinking the issue was only for GSI.
But as u said, the `read/write_capacity_units` parameters must be optional on invoking `create_table`.

**Comment by wobeng** [comment]
Any update on this? I ran into the same issue

` AttributeError: type object 'Meta' has no attribute 'read_capacity_units'` its a temp fix around?

**Comment by ikonst** [comment]
If you set the read and write capacity to e.g. 1, will it work for you? DynamoDB shouldn't take them into consideration once your billing mode is on-demand.

Alternatively, you don't have to use PynamoDB to provision your tables. You can use:
1) AWS Console
2) `aws` command line utility
3) Terraform
4) Any other tool which orchestrates AWS resources

**Comment by 3dw1np** [comment]
Last week, I moved the provisioning of the tables / GSI with Cloudformation.
If I removed the read and write capacity attributes of the Model it works. But if I removed that also on the GlobalSecondaryIndex, I hit the following error like @wobeng :

`AttributeError: class Meta has no attribute 'read_capacity_units'`

**Comment by fvess** [comment]
Any update on this? I believe many AWS users have moved to on-demand tables, and it would be very beneficial to have the support soon. Thanks.

**Comment by ikonst** [comment]
@fvess There are no updates. Do note that is not a blocking issue for on-demand tables.

**Comment by tedivm** [comment]
It's not? Is there documentation somewhere saying how we can use PynamoDB for creating on-demand tables?

**Comment by ikonst** [comment]
@tedivm There's no documentation yet (contributions welcome) but basically you set `billing_mode` in the table's `Meta`. This would have effect on the GSIs and LSIs you're creating too. GSIs and LSIs will need a `read_capacity_units` but you can set `read_capacity_units = 1` and it will have no effect.

Furthermore, you can use PynamoDB to access existing tables that you provision through different means (e.g. AWS console etc.).

**Comment by fvess** [comment]
For anyone still wondering how to create on-demand DynamoDB tables with pynamodb, just add `billing_mode = 'PAY_PER_REQUEST'` in the Meta of your model class.

Additionally, if you are using pynamodb with serverless, you might encounter this error:
`Unknown parameter in input: "BillingMode", must be one of: AttributeDefinitions, TableName, KeySchema, LocalSecondaryIndexes, GlobalSecondaryIndexes, ProvisionedThroughput, StreamSpecification, SSESpecification` when your app tries to create the tables.
This is because pynamodb uses boto3, and the boto3 that is provided in Lambda by AWS is an older version which does not support the On-Demand features of DynamoDB.

**Comment by ikonst** [comment]
> This is because pynamodb uses boto3, and the boto3 that is provided in Lambda by AWS is an older version which does not support the On-Demand features of DynamoDB.

IIRC, it's a botocore issue (we use botocore, not boto3). The minimum version for 'BillingMode' is botocore 1.12.54 and it should already be installed when `pip install`-ing pynamodb:
https://github.com/pynamodb/PynamoDB/blob/7d6849bbf434be94441dbcdaf6bed6664a1236dd/setup.py#L27

**Comment by shivamsharma0612** [comment]
Even in the current release (v.4.0.0) there is a bug in the code. While creating the table it still uses PROVISIONED_THROUGHPUT in a map even when billing mode is set to PAY_PER_REQUEST. Which fails to create the table eventually with a validation error 

> ProvisionedThroughput should not be specified for index: <INDEX_NAME> when BillingMode is PAY_PER_REQUEST

as dynamodb does not expect provisioning options for on demand mode. I have a fix for this bug but I am not sure how to request for a push access after forking a branch from the master. Please suggest.

**Comment by tedivm** [comment]
@shivamsharma0612- you shouldn't need push access, you should be able to just make a pull request. What branch did you make the changes in on your fork?

**Comment by shivamsharma0612** [comment]
@tedivm I cloned the repo and forked the master branch but the push in the new branch dint go through, with a permission denied error. Should i fork the repo and then make the changes, my bad i am a new contributor. Any help will be much appreciated.

**Comment by tedivm** [comment]
What you'll need to do is change your local clone to reference your personal fork on the website.

[Github has some instructions on this](https://help.github.com/en/articles/changing-a-remotes-url).

Essentially run this in the repo-

> git remote set-url origin git@github.com:shivamsharma0612/PynamoDB.git

Then you can commit your changes to your fork, and make a pull request back here.

**Comment by tedivm** [comment]
For the record this issue is definitely not resolved. We've followed all of the advice in this thread and can not get the create tables functionality working. We have a fully up to date version of boto3 and botocore, but keep getting this-


> pynamodb.exceptions.TableError: Failed to create table: An error occurred (ValidationException) on request (REQUEST_ID) on table (TABLE_NAME) when calling the CreateTable operation: One or more parameter values were invalid: ProvisionedThroughput should not be specified for index: INDEX_NAME when BillingMode is PAY_PER_REQUEST

**Comment by tedivm** [comment]
Researching this a bit more, it seems that the AWS API itself is getting more strict about this. I looked at the botocore code and it's just passing things along blindly, and the actual documentation is very explicit that we should not be passing these parameters.

My guess is that they were not as strict about the API earlier and were silently discarding these fields, but as of the most current versions they no longer are. It really seems like merging #690 or attempting to resolve this in some other way is needed now.

**Comment by andre-at-clubien** [comment]
just adding to the thread what others have pointed already:
I ran into the same issue and by simply setting read_capacity and write_capacity to 1 was enough to make it work. As far as I can tell, there's no difference in the behavior of the application after doing it.

Ideally, this should be an optional attribute, unless while trying to provision a DynamoDB table.

**Comment by CodePint** [comment]
When trying to use a global secondary index:

```class ExternalIdIndex(GlobalSecondaryIndex):
    class Meta:
        index_name = 'resource_external_id_index'
        projection = AllProjection()
```
 
I get the following error when trying to make a query:
```*** AttributeError: type object 'Meta' has no attribute 'read_capacity_units'```
