### ISSUE TITLE
Get query result as list?

### ISSUE THREAD

**Issue by mojimi** [pynamodb/PynamoDB#630]
I've noticed some imitations with the query result (ResultIterator)

1) I can't use indexing, for example queryResult[2]
2) I can't get its length
3) I can't iterate it twice

```python
for result in queryResult:
    print(result) #prints the object
for result in queryResult:
    print(result) #never prints anything
```

Is there a method to turn a ResultIterator into a list and force it to get everything at once?

**Comment by ikonst** [comment]
Simply wrap it in `list`, i.e. `my_list = list(MyModel.query(...))`.
