### ISSUE TITLE
Implement S3 Backed Binary Attribute

### ISSUE THREAD

**Issue by MacHu-GWU** [pynamodb/PynamoDB#651]
@jlafon Hi, I want to implement a special attribute for Binary attribute that stored on S3.

It is like if you defined a large binary field and another unicode field for s3 uri, it actually writes the binary to s3 bucket instead of dynamodb. when you delete that item, it also delete the s3 object. when you update that item, it also update the s3 object. I think it is a very nice to have feature for web crawler

```python
class MyModel(Model):
    s3_uri = UnicodeAttribute(hash_key=True)
    content = S3BackedBinaryAttribute(uri_key="s3_uri")

my_model = MyModel(s3_uri="s3://my-bucket/my-object.dat", content=b"Hello World")
my_model.save() # create s3://my-bucket/my-object.dat

my_model = MyModel.get("s3://my-bucket/my-object.dat")
my_model.delete() # delete s3://my-bucket/my-object.dat

my_model = MyModel.get("s3://my-bucket/my-object.dat")
my_model.content = "An Update" # update s3://my-bucket/my-object.dat
```

**Comment by ikonst** [comment]
@MacHu-GWU Generally we're trying to keep only attributes that map to core DynamoDB features. Some of the existing attributes (e.g. `UTCDateTimeAttribute`) don't match that definition, but we're trying not to add more of those :)

I've created lyft/pynamodb-attributes to collect some of those "useful but not core" attributes. That being said, I find this pattern to be somewhat strange -- e.g. `save()` now has multiple causes for failure, and relies on a AWS service that you don't expect `pynamodb.models.Model.save` to access.

**Comment by MacHu-GWU** [comment]
@ikonst Thank you for your quick reply! Good point, then I think I can create a Mixin class for that purpose without changing ``.save()`` behavior.
