### ISSUE TITLE
`id` field not available in 4.0.0b2 and up

### ISSUE THREAD

**Issue by svdgraaf** [pynamodb/PynamoDB#662]
I bumped into an issue with while testing out 4.0.0b2 and up. Posting this to keep a record, I'm actively working on finding what the issue is. (Python 3.7)

**What is happening**
The `id` field (and only the `id` field) does not seem to be available, or is at least broken. Not sure yet if this is because the `id` is a preserved name or not.

```python
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute


class Foobar(Model):
    class Meta:
        table_name = "test_table"
        region = "eu-west-1"

    id = UnicodeAttribute(null=False, hash_key=True)
    name = UnicodeAttribute(null=False)


foo = Foobar.get("9")
print(foo)
# test_table<None>
print(foo.id)
# None
print(foo.name)
# Foobar
```

**When does this occur**
This only occurs in `b2` and `b3`. In `4.0.0b1` this works as expected:

```python
foo = Foobar.get("9")
print(foo)
# test_table<9>
print(foo.id)
# 9
print(foo.name)
# Foobar
```

Perhaps `id` is deprecated? Or did I miss a readme somewhere? Still working on resolving the root cause.

**Comment by ikonst** [comment]
I changed your code slightly to get the table to create and to save the item:
```py
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute


class Foobar(Model):
    class Meta:
        table_name = "test_table"
        host = 'http://localhost:8000/'
        read_capacity_units = 10
        write_capacity_units = 10

    id = UnicodeAttribute(null=False, hash_key=True)
    name = UnicodeAttribute(null=False)

Foobar.create_table()

foo = Foobar("9")
foo.name = "bar"
foo.save()

foo = Foobar.get("9")
print(foo)
print(foo.id)
print(foo.name)
```
got me:
```
test_table<9>
9
bar
```

**Comment by svdgraaf** [comment]
I've found the issue to be in `models.py from_raw_data`, I see a lot of code got removed in this commit for 4.0.0b2, maybe a bit too much? 😄 

https://github.com/pynamodb/PynamoDB/commit/1b7eeb0e3874df8fb8ef2f8527cde04b88bb748e#diff-66d6c6d3d504b9e11a4e236e67133ddeL415

I'll see if I can provide a PR to reconstruct the hash key's correctly.

**Comment by svdgraaf** [comment]
Ok, got it. It's sort of a bug, maybe? :)

I used a `UnicodeAttribute` for my id's. Those were actually setup as `int` in Dynamo (table was created through cloudformation outside of PynamoDB). Fetching with a string instead of int just happens to work (probably because of some mapping somewhere).

Previously, in b1 and before, the key was explicitly given in the `from_raw_data` cls init (return line) as `arg`:
https://github.com/pynamodb/PynamoDB/blob/4.0.0b1/pynamodb/models.py#L535

From b2 forward, the `from_raw_data` was refactored, and looks a lot cleaner. Now, the key is no longer explicitly passed, but is fetched like any other attribute:

https://github.com/pynamodb/PynamoDB/blob/4.0.0b2/pynamodb/models.py#L431

In my case, this now breaks the fetching of the `hash_key`, because I was using the wrong attribute type and it couldn't be mapped any longer. This is also why in @ikonst version of the test code it works, as the table is created with the `UnicodeAttribute` as string, and we are fetching it as a string.

So, all in all, bug was on my part. But perhaps a note is needed somewhere to inform of this parser change?

**Comment by ikonst** [comment]
@jpinner-lyft thoughts?

**Comment by jpinner-lyft** [comment]
@ikonst maybe just more explicit release notes stating that the attribute types for the hash and range keys used in the model must match the table definition
