### ISSUE TITLE
why does changing items require get?

### ISSUE THREAD

**Issue by wobeng** [pynamodb/PynamoDB#674]
First of thanks for PynamaDb. Great tool. 

I was reading the  [changing items](https://pynamodb.readthedocs.io/en/latest/quickstart.html#changing-items)in documentation

```
user = UserModel.get('test@example.com')
user.update(
  actions=[
    UserModel.first_name.set('Robert')
  ]
)
```

I was wondering why a read/get from the db is required before updating an  item. Why can't I just update the item?

**Comment by ikonst** [comment]
Technically I don't think you need to `get` -- might suffice to:
```python
user = UserModel()
user.email = 'test@example.com'
user.update(
  actions=[
    UserModel.first_name.set('Robert')
  ]
)
```

**Comment by wobeng** [comment]
got it...thanks
