### ISSUE TITLE
a way to return values when putting an item

### ISSUE THREAD

**Issue by wobeng** [pynamodb/PynamoDB#675]
Is it possible to specify return values when putting an item (using save) just in case I'm overwriting? 

something like this 

```
user = UserModel.get('test@example.com')
user.first_name = 'Robert'
user.save(return_values='ALL_OLD')

```

**Comment by ikonst** [comment]
`save` doesn't accept `return_values `currently. In fact, pynamodb doesn't surface `return_values` at in the high level API. I suspect this is because, being an ORM, it has certain expectations about return values.

Is this a feature request?

**Comment by wobeng** [comment]
I see, maybe we should find a way to specify it somehow. `ALL_OLD` or `None` is the only option for put item so if we make the default ALL_OLD and save it somewhere it won't hurt.

**Comment by ikonst** [comment]
What are you trying to achieve with this?

**Comment by wobeng** [comment]
I want to be able to process delete an old item in another system after overwriting,

The current way is to get the item, overwrite it and process delete an old item

**Comment by wobeng** [comment]
closing does not fit ORM
