### ISSUE TITLE
Can't Query table without AWS credentials in in Model's Meta class

### ISSUE THREAD

**Issue by skytreader** [pynamodb/PynamoDB#678]
Similar to my scenario in #448, I discovered that I can't query on my table due to permissions:

```
pynamodb.exceptions.QueryError: Failed to query items: An error occurred (AccessDeniedException) on request (HASH) on table (tbl-dev) when calling the Query operation
```

This, despite that `dynamodb:Query` is declared in my allowed actions in the `iamRoleStatements` declaration of my `serverless.yml`.

The only way I got it to query at all is by including my AWS credentials in the Meta class of my table model.

In fact, I discovered that, at least for querying, my `iamRoleStatements` do not seem to matter and only the credentials declared in my Meta class does; I can remove the declarations for `dynamodb:Query` in `serverless.yml` and everything will be fine as long as the credentials are declared in my Meta class.

(For additional debugging, I included all possible IAM permissions in my `serverless.yml` and I still did not get to query successfully, until I added my AWS creds in Meta.)

Am I missing something here? As much as possible I would really rather not include my AWS credentials in my source code.

**Comment by garrettheel** [comment]
Storing credentials in source code is certainly not recommended or required. PynamoDB should respect all of the standard credential mechanisms through the underlying use of `botocore`. Environment variables, instance metadata, config file, etc. should all work fine.

It sounds like you're using lambda, so you'd be relying on the environment variables set in https://docs.aws.amazon.com/lambda/latest/dg/lambda-environment-variables.html -- `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`

A couple of suggestions that might help you:
 * Double check the execution role IAM policy
 * Turn on debug logging to see what botocore is up to
 * Update the version of botocore you're using
 * Ensure environment variables are being propagated to the python application correctly

**Comment by garrettheel** [comment]
Closing for now, feel free to reopen if you have more questions!
