### ISSUE TITLE
Count class method always return 1

### ISSUE THREAD

**Issue by 3dw1np** [pynamodb/PynamoDB#683]
I have several model item into the dynamodb table but the class method of the pynamodb model is always returning 1 event with the consistent_read parameter.

```
TestModel.count(consistent_read=True)
```
I am trying to get a sequantial number value related to the number of item in the dynamodb table.

**Comment by ikonst** [comment]
This is not a PynamoDB issue.

See the [ItemCount](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TableDescription.html#DDB-Type-TableDescription-ItemCount) documentation:
> DynamoDB updates this value approximately every six hours. Recent changes might not be reflected in this value.

If you need to count the number of items precisely, you can scan the database, but then if you need to do it, DynamoDB is probably not the right tool for you.
