### ISSUE TITLE
Generate filter conditions

### ISSUE THREAD

**Issue by 3dw1np** [pynamodb/PynamoDB#684]
Since the deprecated conditional APIs have been remove on v4.0.0.
How can I generate filter conditions like this : 
```
filter_condition=(getattr(TestModel.name, operator)(value))
```

with in the example the operator can be __eq__ or contains.
What about multiple conditions with & or | ?

**Comment by ikonst** [comment]
Something like this should be easy:
```
condition = TestModel.name == "foo"
if something_else:
   condition &= TestModel.message == "bar"
```
and then use this condition wherever you need

Let me know if you have a more specific question.

**Comment by 3dw1np** [comment]
Thanks @ikonst !
Sorry for the delay, but in facts, I need generated condition from http query string like this:
```
?status__eq=terminated&id__contains=123
```

Which give me a dict in my python app:
```
query_filters = {
  'status__eq': 'terminated',
  'id__contains': '123'
}
```
How to transform operators (eq and contains with == and contains, with a map) ? 
And how to get a filter_condition with all my query filters ?

Many thanks !

**Comment by ikonst** [comment]
I'd parse the query string's keys, e.g.
```
conditions = None
for k, v in args:
  attr, op = k.split('__)
  if op == 'eq':
    conditions &= getattr(MyModel, attr) == v
  elif op == ...:
    ...
```
