### ISSUE TITLE
List of Map: How to delete an item in list if item attribute equal a value

### ISSUE THREAD

**Issue by wobeng** [pynamodb/PynamoDB#685]
How do I delete Justin from the employee list with a condition of OfficeEmployeeMap.person == 'justin' ?

```
class OfficeEmployeeMap(MapAttribute):
    office_employee_id = UnicodeAttribute()
    person = UnicodeAttribute()

    def __eq__(self, other):
        return isinstance(other, OfficeEmployeeMap) and self.person == other.person

    def __repr__(self):
        return str(vars(self))


class Office(Model):
    class Meta:
        read_capacity_units = 1
        write_capacity_units = 1
        table_name = 'Office'
        host = "http://localhost:8000"
    office_id = UnicodeAttribute(hash_key=True)
    employees = ListAttribute(of=OfficeEmployeeMap)
    name = UnicodeAttribute()
    version = VersionAttribute()

```

```
justin = OfficeEmployeeMap(office_employee_id=str(uuid4()), person='justin')
garrett = OfficeEmployeeMap(office_employee_id=str(uuid4()), person='garrett')
office = Office(office_id=str(uuid4()), name="office", employees=[justin, garrett])
office.save()
```

**Comment by ikonst** [comment]
Looking at the [UpdateItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) API documentation, you can see that the only action that mutates DynamoDB list types is `list_append` which appends items.

I don't think you can conditionally remove items from a list.

I would recommend simply re-saving the item. If you're concerned about overwriting concurrent changes, add a `VersionAttribute` which would make your "saves" conditional (on no concurrent modifications being made).

**Comment by wobeng** [comment]
@ikonst yea you can, you can delete by 

```Office.employees[0].remove() with a condition of Office.employees[0].person == 'justin'```

**Comment by wobeng** [comment]
got it, thank you
