### ISSUE TITLE
Query returning only HASH and Range. Attributes empty when printing serialized object

### ISSUE THREAD

**Issue by gowtham800** [pynamodb/PynamoDB#689]
I am getting empty attribute object response. Can some one help me please....

        class PNFGDINDEX(GlobalSecondaryIndex):

            class Meta:
                index_name = 'PN-FGD-Index'
                read_capacity_units = 5
                write_capacity_units = 5
                projection = AllProjection()

            ProjectName = UnicodeAttribute(hash_key=True)
            FileGeneratedDate = UnicodeAttribute(range_key=True)

        class TestModel(Model):
          
            class Meta:
                aws_access_key_id = "xxxxxxxxx"
                aws_secret_access_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                table_name = 'TEST_EDCBUILDDATA1'
                region = 'ap-south-1'
                
            Id = UnicodeAttribute(hash_key=True)
            createdTimeStamp = UnicodeAttribute(range_key=True)
            ProjectName = UnicodeAttribute
            FileGeneratedDate = UnicodeAttribute
            FileNameKey = UnicodeAttribute
            VehicleName = UnicodeAttribute
            view_index = PNFGDINDEX()
            

        for item in TestModel.view_index.query(pn):
            print(item._serialize())

**Comment by garrettheel** [comment]
If you check the table schema, is `PN-FGD-Index` actually set to have an `ALL` projection type? I'm guessing that the table was created prior to specifying that or it's managed externally to pynadmob and configured wrong.

**Comment by gowtham800** [comment]
@garrettheel ```PN-FGD-Index``` does not project all Attributes. It is set only to project Id, createdTimeStamp, ProjectName, FileGeneratedDate, FileNameKey & VehicleName respectively. I tried IncludeProjection(attributes)....still returned empty. 
And yes the Index was created a few months after table was created using AWS Console....

**Comment by grvhi** [comment]
@gowtham800 

```
ProjectName = UnicodeAttribute
FileGeneratedDate = UnicodeAttribute
FileNameKey = UnicodeAttribute
VehicleName = UnicodeAttribute
```
Should be:
```
ProjectName = UnicodeAttribute()
FileGeneratedDate = UnicodeAttribute()
FileNameKey = UnicodeAttribute()
VehicleName = UnicodeAttribute()
```
