### ISSUE TITLE
transactions module is not available

### ISSUE THREAD

**Issue by jminnie** [pynamodb/PynamoDB#693]
Hi,

I'm trying to use the newly added transaction functionality in `4.0.0`,  however,  the `transaction` module is nowhere to be found, leading to an unresolved reference when I do this:
```
from pynamodb.connection.transactions import TransactWrite
```
Please let me know if I'm doing something stupid that should allow this to work.

**Comment by horike37** [comment]
I ran into this issue too.

**Comment by horike37** [comment]
@jminnie 
Seems that the documentation is wrong. maybe here is a right 

```
from pynamodb.transactions import TransactWrite
```

**Comment by ikonst** [comment]
@hallie I think we forgot to update the docs here?

**Comment by hallie** [comment]
oops!

**Comment by jminnie** [comment]
Awesome,  [that worked](https://github.com/pynamodb/PynamoDB/issues/693#issuecomment-531815680).  Thanks!

**Comment by garrettheel** [comment]
Thanks for fixing the docs!
