### ISSUE TITLE
Question: Last Evaluated Key returning None

### ISSUE THREAD

**Issue by dengun-kevcal** [pynamodb/PynamoDB#696]
Hi i'm using pynamodb for a project in our company. I'm having issues with using scan and last evaluated key. I'm trying to do pagination. I created 100 of items and set my limit to 25. After querying i get 25 initial results but my last_evaluated_key always returns None. I'm fairly new to dynamodb and pynamodb so im not sure if this is correct way of doing things. I would expect that it would return something so i could have a cursor for my next request.

```
objs = MyModel.scan(
        limit=config.LIMIT,
        last_evaluated_key=last_key_value)
objs.last_evaluated_key 
```

tried it on 
local dynamodb, pytest, pynamodb==4.00

**Comment by ikonst** [comment]
Can you try iterating over objs first, i.e.
```
results = MyModel.scan(
        limit=config.LIMIT,
        last_evaluated_key=last_key_value,
)
objs = list(results)
assert len(obs) == config.LIMIT
print(result.last_evaluated_key)
```

**Comment by dengun-kevcal** [comment]
@ikonst that worked, thanks. I didn't knew that you had to iterate it over first probably since its generator. Maybe you can add this to the documentation. Thanks again.
