### ISSUE TITLE
Dynamic key in a map

### ISSUE THREAD

**Issue by wobeng** [pynamodb/PynamoDB#698]
How will I build a model with the example below. `random_media_id` will be auto-generated id when its being created.

```
class MediaMapAttributes(MapAttribute):
    media_id = UnicodeAttribute()
    media_group = UnicodeAttribute()
    media_size = NumberAttribute()
```

```
{
  "random_media_id": MediaMapAttributes(),
  "random_media_id": MediaMapAttributes(),
  "random_media_id": MediaMapAttributes()
}

```

**Comment by ikonst** [comment]
PynamoDB, being an ORM, isn't well-suited for data with such lose schema. You can have arbitrary data in an attribute by using an untyped `MapAttribute`, but you can't have arbitrarily named attributes in the top-level models. If you want to do that, you might as well just use boto directly.
