### ISSUE TITLE
Batch saving items with composite keys only saves one item per hash_key

### ISSUE THREAD

**Issue by Veilkrand** [pynamodb/PynamoDB#699]
I'm trying to save items in a batch with:
- `id` as hash_key
- `date` as range_key

After few batches new items with same id replace older items, where it should create new objects withe same id but different date value. Am I missing anything? How to create this behavior? Thanks

Model
```
class ListingModel(Model):

    class Meta:
        table_name = "Airbnb-Listings"

    id = UnicodeAttribute(hash_key=True)
    date = UTCDateTimeAttribute(range_key=True)
    location_query = UnicodeAttribute()
    name = UnicodeAttribute()
    city = UnicodeAttribute(null=True)  # is city None??
    address = UnicodeAttribute()
    category = UnicodeAttribute()
```

Batch save function:
```
def save_homes_dynamodb(homes, date_string, location_query):

    # query_date = datetime.strptime(date_string, '%Y-%m-%d')

    query_date = datetime.utcnow()

    print(f'{len(homes)} listings to batch write to DynamoDB.')
    with ListingModel.batch_write() as batch:
        for home in homes:
            row = ListingModel(
                str(home['listing']['id']), query_date,
                location_query=location_query,
                name=home['listing']['name'],
                address=home['listing']['public_address'],
                city=home['listing']['city'],
                category=home['listing']['room_type_category'],
                home_listing_json=home['listing'],
                pricing_quote_json=home['pricing_quote']
            )

            try:
                print(f'Saving {row.id} - {row.city} - {row.name}')
                batch.save(row)
                time.sleep(1 / 5)  # To avoid hitting limits
            except Exception as e:
                print(e)
                print(row)

```

**Comment by ikonst** [comment]
You're setting the same time (which you get outside the loop) on all your listings, so obviously they end up overwriting each other.

**Comment by Veilkrand** [comment]
The `time` of one batch have to be the same, the `id`s per batch are unique.
Every time I call a new batch with `save_homes_dynamodb()` I save a set of unique `id`s with the same `date`.
However after several batches processed, the table only shows one object per id with the last date, not several objects with the same ids and different dates.

**Comment by ikonst** [comment]
I have a theory: Perhaps the underlying DynamoDB table definition does not match the one that PynamoDB sees. PynamoDB doesn't try to ensure that its own view on the table definition matches reality, but you can do `aws dynamodb describe-table --table-name ...` and validate it yourself.

**Comment by Veilkrand** [comment]
Right, there's nothing related to range_key in the table description:
```
"KeySchema": [
            {
                "AttributeName": "id",
                "KeyType": "HASH"
            }
        ],
```

I created the table using the model definition with `.create_table()` 

How can I enforce the inclusion of the model defined range_key field in the table definition during creation?

**Comment by ikonst** [comment]
Perhaps you did `create_table` before defining the range key. As your PynamoDB class stands now, the table should've been created with a range key.

At this point, your best bet is deleting the table (possibly with `delete_table`) and re-creating it, possibly with `create_table`.
