### ISSUE TITLE
Understanding TransactWrite

### ISSUE THREAD

**Issue by getimti** [pynamodb/PynamoDB#706]
I am trying to simulate "unique" constraint using two tables. Example is, say file path. It is an attribute in main table that has a UUID attribute as hash key (uniqueness provided by Dynamodb). To ensure uniqueness on path attribute, I created another table that has path as hash key, and wrapped both inserts in TransactWrite.

```
                try:
                    with TransactWrite(connection=conn) as transaction:
                        # insert path in directory_paths table for unique test
                        new_path = DirectoryPaths(
                            path=format_path(partial_path, owner_id)
                        )
                        transaction.save(new_path)
                        current_app.logger.debug(f"saving path : {new_path}")
                        new_directory = Directory(
                            id=uuid.uuid4(),
                            path=format_path(partial_path, owner_id),
                            created_at=datetime.utcnow()
                        )
                        transaction.save(new_directory)
                except TransactWriteError as err:
                    current_app.logger.debug(err)
                    raise ValueError(f"Failed in Transaction {err}")
```

If i load test with 20 concurrent requests, I get unique entries in "DirectoryPaths" table, but duplicate paths in the main table. Expectation is if "DirectoryPaths" insert fails (to ensure uniqueness), both writes (saves()) should be reverted. It is not behaving as a transaction unit.

Any insights appreciated.

**Comment by ikonst** [comment]
PynamoDB "Save" translates to a PutItem action in DynamoDB: note that there's no separate action for create vs. update, they're both "put"s. Therefore, creating a new model instance whose HK exists in the table and calling `save` will just successfully overwrite the previous entry.

To make sure it's a "create but not an update", use a `does_not_exist` write condition:
```python
new_path.save(DirectoryPaths.path.does_not_exist())
```
Feel free to adapt it to the transactions API :)

**Comment by getimti** [comment]
Got it working by adding the condition to the save. Thanks

**Comment by erichonkanen** [comment]
@getimti could you paste example?
