### ISSUE TITLE
Given key conditions were not unique

### ISSUE THREAD

**Issue by amirvaza** [pynamodb/PynamoDB#707]
Hello all, 

Im trying to update_or_create a document which works most of the times

Table:
```
class Report(BaseEntity):
    class Meta(BaseEntity.Meta):
        table_name = 'Reports'

    SomeId = UnicodeAttribute(hash_key=True)
    Time = NumberAttribute(range_key=True)  # Time as UTC Unix timestamp
    IncAttr = NumberAttribute()

```
Here is the update command which sometimes failed:
`Report(SomeId="id", Time=get_current_time_report()).update(actions=[Report.IncAttr.add(1)])`

Somehow, in the database there are two documents with the same SomeId and Time

Is it some case of a race condition? Anyone have any idea?

Thanks.

**Comment by ikonst** [comment]
> there are two documents with the same SomeId and Time

I'm confused by this statement. DynamoDB is a key-value store where the key is a composite of (hash key, range key). How do you determine that a document "exists"? Do you perform `Report.get(some_id, some_time)`? This operation returns just one item.

Or do you perform a `Report.scan()`?

**Comment by amirvaza** [comment]
No, im counting on document locking which means if its already exists, it will inc. Most of the times it works.
I took the idea from here.

**Comment by ikonst** [comment]
Could you re-phrase what you're seeing then? (Two documents with the same hash and range key is technically impossible in DynamoDB.)

**Comment by amirvaza** [comment]
It is impossible, but - assuming there is a lock on this hash_key+range_key, and the only query im running is the one i put here. There should be no case which two documents with the same hash_key+range_key.

Unless there is a bug in pynamodb/dynamoDBLocal or something that i dont understand about range keys (probably)

**Comment by ikonst** [comment]
> It is impossible, but - assuming there is a lock on this hash_key+range_key, and the only query im running is the one i put here. There should be no case which two documents with the same hash_key+range_key.

Two documents with the same hash + range key are impossible. Not because of locking but simply because of how DynamoDB is.

Let me give you an example:
```python
my_dict = {}
my_dict['my_hash_key', 'my_range_key'] = 'something'
my_dict['my_hash_key', 'my_range_key'] = 'something else'
print(len(my_dict))
```
It's obvious that will always print 1, right? Same way for DynamoDB.

**Comment by amirvaza** [comment]
How would u explain these two documents then:
```
5: { 
    "Time":1571317200
    "SomeInc":1
    "SomeId":"0e88792321df"
}
6: { 
    "Time":1571317200
    "SomeInc":2
    "SomeId":"0e88792321df" 
}
```

**Comment by ikonst** [comment]
Where are you getting them from?

**Comment by amirvaza** [comment]
http://localhost:8000/shell/
```
var params = {
    TableName: 'Reports',
};
docClient.scan(params, function(err, data) {
    if (err) ppJson(err); // an error occurred
    else ppJson(data); // successful response
});
```

**Comment by ikonst** [comment]
Can you do a `describe table` operation on this table and paste the output?

**Comment by amirvaza** [comment]
Sure
```
"Table" {
	"AttributeDefinitions" [
		0: {
			"AttributeName":"Time"
			"AttributeType":"N"
		1: {
			"AttributeName":"SomeId"
			"AttributeType":"S"
	"TableName":"Reports"
	"KeySchema" [
		0: {
			"AttributeName":"SomeId"
			"KeyType":"HASH"
		1: {
			"AttributeName":"Time"
			"KeyType":"RANGE"
	"TableStatus":"ACTIVE"		
	"CreationDateTime":"2019-10-14T20:52:58.417Z"
	"ProvisionedThroughput" {
		"LastIncreaseDateTime":"1970-01-01T00:00:00.000Z"
		"LastDecreaseDateTime":"1970-01-01T00:00:00.000Z"
		"NumberOfDecreasesToday":0
		"ReadCapacityUnits":5
		"WriteCapacityUnits":5
	"TableSizeBytes":861
	"ItemCount":11
	"TableArn":"arn:aws:dynamodb:ddblocal:000000000000:table/Reports"

```

**Comment by ikonst** [comment]
Try as I might, I cannot understand how you got into this state.

What do you get for:
```py
print(Report.get('0e88792321df', 1571317200))
print([r for r in Report.scan() if r.SomeId == '0e88792321df' and r.Time == 1571317200])
```
?

**Comment by amirvaza** [comment]
Error
```
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/pynamodb/connection/base.py", line 1125, in get_item
    return self.dispatch(GET_ITEM, operation_kwargs)
  File "/venv/lib/python3.6/site-packages/pynamodb/connection/base.py", line 336, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs)
  File "/venv/lib/python3.6/site-packages/pynamodb/connection/base.py", line 439, in _make_api_call
    raise VerboseClientError(botocore_expected_format, operation_name, verbose_properties)
pynamodb.exceptions.VerboseClientError: An error occurred (InternalFailure) on request (97eb92db-2db4-45a8-b7f7-c683f8d8d378) on table (Reports) when calling the GetItem operation: The request processing has failed because of an unknown error, exception or failure.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app.py", line 3, in <module>
    print(Report.get('0e88792321df', 1571317200))
  File "/venv/lib/python3.6/site-packages/pynamodb/models.py", line 475, in get
    attributes_to_get=attributes_to_get
  File "/venv/lib/python3.6/site-packages/pynamodb/connection/table.py", line 174, in get_item
    attributes_to_get=attributes_to_get)
  File "/venv/lib/python3.6/site-packages/pynamodb/connection/base.py", line 1127, in get_item
    raise GetError("Failed to get item: {}".format(e), e)
pynamodb.exceptions.GetError: Failed to get item: An error occurred (InternalFailure) on request (97eb92db-2db4-45a8-b7f7-c683f8d8d378) on table (Reports) when calling the GetItem operation: The request processing has failed because of an unknown error, exception or failure.
```

And in DynamoDBLocal same error*4:
```
Oct 19, 2019 5:50:21 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] SQLiteDBAccess$14@1abecbd2: job exception
com.amazonaws.services.dynamodbv2.local.shared.exceptions.LocalDBAccessException: Given key conditions were not unique. Returned: [{Time={N: 1571317200,}, Requests={N: 1,}, UserId={S: 0e88792321df,}}] and [{UserId={S: 0e88792321df,}, Time={N: 1571317200,}, Requests={N: 2,}}].
  at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDBUtils.ldAccessFail(LocalDBUtils.java:800)
  at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccessJob.getRecordInternal(SQLiteDBAccessJob.java:224)
  at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$14.doWork(SQLiteDBAccess.java:1553)
  at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$14.doWork(SQLiteDBAccess.java:1549)
  at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.job(AmazonDynamoDBOfflineSQLiteJob.java:117)
  at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
  at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
  at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
  at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
  at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
  at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
  at java.lang.Thread.run(Thread.java:748)
db.1.80xmw851amk2@docker-desktop    | 
```

**Comment by ikonst** [comment]
🙀
This first one (`InternalFailure`) is with AWS DynamoDB?

**Comment by amirvaza** [comment]
It is latest indeed.

Plus - I think you're wrong with the python hash example.
https://stackoverflow.com/questions/25350256/dynamodb-key-uniqueness-across-primary-and-global-secondary-index

I don't think my mistake is within the creation of the documents since one of the documents was inc'ed more than once (and i got to 3 or 4 inc's before i opened this issue here, deleted the table).
In such case, both will be set to 1.
What I'm trying to say is, there is no locking on the hash+range creation of the document. (Just a guess)

**Comment by ikonst** [comment]
There is no uniqueness in GSIs -- that's why you can't "get" from a GSI, you can only "query" a GSI. In other words, for a (HK, RK) pair on a GSI, you can get 0 results, 1 result or 1,000,000 results.

As for tables themselves, see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey:
> In a table that has only a partition key, no two items can have the same partition key value.
> In a table that has a partition key and a sort key, it's possible for two items to have the same partition key value. However, those two items must have different sort key values.

(partition key = hash key, sort key = range key)

**Comment by amirvaza** [comment]
Yeah you're right, im too confused from this bug(?).

Any idea what to do next?

**Comment by ikonst** [comment]
I'm suspecting an issue in dynamodb-local :/ I wonder if it relies on some property of the underlying SQLite that fails.

**Comment by amirvaza** [comment]
Ill try to find a place to open a bug there then and in the meantime work on the real dynamoDB to see if it happens there too.
I guess you can close the issue, i will reopen if everything there is fine :/

**Comment by MobbinBiosilico** [comment]
> Ill try to find a place to open a bug there then and in the meantime work on the real dynamoDB to see if it happens there too. I guess you can close the issue, i will reopen if everything there is fine :/

Hi, have you been able to resolve this, i am running into a similar error where the function sometimes works, but other times i get 'Given key conditions were not unique.'
