### ISSUE TITLE
Failing import since botocore 1.13

### ISSUE THREAD

**Issue by baptisteem** [pynamodb/PynamoDB#713]
Since the update to botocore 1.13 the following import is failing

```
    File "/usr/local/lib/python3.6/site-packages/pynamodb/connection/base.py", line 20, in <module>
        from botocore.vendored.requests import Request
ImportError: cannot import name 'Request'
```

**Comment by ikonst** [comment]
@baptisteem As of PynamoDB 4.0 we're no longer using requests either.

**Comment by baptisteem** [comment]
Thanks for replying that fast, you're definitely right, I'll update it on my side 👍
