### ISSUE TITLE
How do I update programatically / dynamically in version >4.0 ?

### ISSUE THREAD

**Issue by flyinbutrs** [pynamodb/PynamoDB#725]
I'm trying to update a module I use to pynamodb 4.0, but I don't understand how to convert one particular block into the new version now that `update` does not include `attributes`. Basically, the function takes a dict of keys/values to be updated in the DDB item, and formats them to be updated. In looking at the docs, I can't see a straightforward way to do that. Is there an equivalent option in PynamoDB 4?

The code in question is this:

```python
    alarm = Alarm.get(hash_key, range_key)
    update_attributes = {
        attribute: dict(value=value, action="PUT")
        for attribute, value in attributes.items()
        if value
    }
    try:
        data = alarm.update(attributes=update_attributes)
        LOG.info(json.dumps({"Alarm Update Response": data}))
    except UpdateError as error:
        LOG.error(error)
```

**Comment by ikonst** [comment]
Normally you pass a list of actions to `Model.update`:
```python
alarm.update(
  actions=[
    Alarm.name.set('Hello'),
  ],
)
```

Are you trying to update attributes whose names you don't know in advance, e.g. that are coming from a free-form dict? How can you be sure that those attributes exist in your schema?

You can compose the list dynamically but you'd get an `AttributeError` if any of those attributes are not declared in your model:
```python
actions = [
    getattr(Alarm, attribute).set(value)
    for attribute, value in attributes.items()
    if value
]
```

**Comment by flyinbutrs** [comment]
Correct, the system receives info about which fields need to be updated, and this function is supposed to make it work. I think I figured it out by doing this:

```
alarm.attribute_values.update(attributes_to_update)
alarm.save()
```

Is there a reason not to do it like so?

**Comment by ikonst** [comment]
Doing it like this will rewrite the entire document including attributes that you didn't change. The reason to use `update` is to limit the update to specific attributes. For most cases, rewriting the whole document is OK. If you want to prevent conflicts with other saves done in parallel, you can also use a `VersionAttribute`.

**Comment by flyinbutrs** [comment]
Ahah. So is there an equivalent way to the using `attributes` in the earlier versions? Is there a way to specify a conditional update that doesn't involve a lot of meta functions involve `if hasattr(Alarm, attribute)` type operations?

**Comment by ikonst** [comment]
I think a big reason for using PynamoDB is to have schemas. If you don't need/have a schema, why not use boto directly?

**Comment by flyinbutrs** [comment]
In this particular case, it's a legacy application that we built a pynamodb schema for after these old functions were written, and the code above is how the developer chose to implement it. It's tech debt to update those functions to directly use the schema, but for now, I just need to be able to update to the newer pynamodb. I guess my method will have to do for now with a higher dynamo transaction cost. Thanks!

**Comment by chubz** [comment]
@ikonst Hi, I'm in a predicament about trying to set schemaless part of my table.
I agree there is a huge benefit to having a schema that is pynamodb enforced. However, considering the dynamodb limitations and that one of it's advantage is being schemaless shouldn't pynamodb leverage that too?

**Comment by ikonst** [comment]
@chubz There might be a case for PynamoDB models exposing the underlying table for operations, or perhaps exposing a schema-less "view" of itself. You can always hack something, of course, but I assume you want a more first-class citizen experience for storing schema-less data.

As it stands now, most of PynamoDB development is simply driven by how it's commonly used here at Lyft. Our many teams have a lot of autonomy, but having a concrete design and having business objects with a concrete schema seems to be a predominant pattern we can all agree on. Sometimes a service does store arbitrary data on behalf of another service (though it's considered to be a "smell" in most cases), and in those cases primitive `MapAttribute` and `ListAttribute` usually suffice (or even, say, a `BinaryAttribute` storing a serialized Protobuf...).

I suppose one advantage of going schema-less for the top-level attributes is that you can use those attributes in filter conditions (i.e. the kind of filters when you pay AWS per-item anyway but get only the items that pass the filter). Perhaps share more about what you're trying to do?

**Comment by chubz** [comment]
@ikonst thanks for answering.
I understand where your use case comes from, and if something like this isn't supported there will be hacking away for specific use cases.
We ended up dumping data in a file on s3.
My concrete case is that I'm calling a 3rd party api for some data, and then when I get that data I need to write it in the dynamodb. Since the data object itself is bigger than 400kb suported by dynamodb I wanted to split the data by having a part of it that is a list of some sub object turned into attributes named by the unique id those objects have.
so something like:
userid
3rd_party_access_token
request_meta
response_meta
trip_123456
trip_234567
trip_345678
...
thus managing to split the original response into chunks that can via a prefix of trip be connected back or managable.

I know this won't help anything and there are ways around this. But I really like pynamodb so wondered whether or not it should empower users to take advantage of this aspect of dynamo itself.
While having some limitation it has great possibilities in expanding data stored in it.

Thanks for reading and happy holidays.

**Comment by ikonst** [comment]
What I'm curious about is for those attributes that have arbitrary names like "trip_123456", any reason those shouldn't go into a MapAttribute instead of being direct attributes of the DynamoDB item?

**Comment by chubz** [comment]
there are more than 400kb of those trips. Let's say there are 50 trips and each is an object with subobjects etc. So I can either have 50 attributes, which should be fine.
Or I could try to anticipate that there will be max of 300 trips, and make fixed attributes and then run through each 25ish and store those in fixed attributes that I defined on the model.

In any case, as I'm not able to predict how many trips I will get I'm always at risk of having an error or edge case not covered.

**Comment by ikonst** [comment]
No, no, I mean:
```
class MyModel(Model):
   trips = MapAttribute()


my_model = MyModel.get(...)
my_model.trips['trip_12345'] = my_trip
my_model.save()
```
