### ISSUE TITLE
Documentation lacking on table/gsi/lsi query/scan.

### ISSUE THREAD

**Issue by erichonkanen** [pynamodb/PynamoDB#733]
Hello, new to this lib and I noticed the documentation seems to be lacking with examples on how to scans/queries on tables/gsi/lsi.

The documentation states [`Index queries use the same syntax as model queries.`](https://pynamodb.readthedocs.io/en/latest/indexes.html#querying-an-index) yet information on model queries can't be found on the doc site.

It would be nice if there were more examples for simple -> more complex queries using this lib.

**Comment by ikonst** [comment]
@erichonkanen This section seems to contain an introduction to querying tables:
https://pynamodb.readthedocs.io/en/latest/quickstart.html#querying

Can you suggest something you're missing or propose additional examples?

**Comment by erichonkanen** [comment]
@ikonst sorry I somehow missed that section!

**Comment by erichonkanen** [comment]
@ikonst what about examples of how to compare datetimes? Also what about using filter_condition?

For instance I have code that looks like this:
```
        cutoff = (arrow.utcnow().datetime -
                  dt.timedelta(seconds=MAX_PERSON_AGE))
        people = models.People.query(
            id,
            created_at__gt=cutoff,
        )
```
This was written and worked in < 4.0.0, but no longer works since `**filters` was removed. It's not clear how to write a filter expression using `query(index, filter_condition)`? How do you reference the correct value of the attribute? It is `models.People.created_at > cutoff`?

**Comment by erichonkanen** [comment]
maybe showing a table with all the available methods? 
![image](https://user-images.githubusercontent.com/230757/70016063-24e9b480-1534-11ea-8861-8cf36be020e9.png)

**Comment by ikonst** [comment]
Exactly!
```python
people = models.People.query(
    id,
    filter_condition=models.People.created_at > cutoff,
)
```

I suppose we could provide more examples in the docs.

**Comment by erichonkanen** [comment]
:) feel free to add above query
