### ISSUE TITLE
Configuration error in setup.py - "tests.integration" package is installed

### ISSUE THREAD

**Issue by biniow** [pynamodb/PynamoDB#757]
Due to configuration error in setup.py, pip install extra package called "tests.integration" which causes import problems while you have "tests" module in your local project. To confirm that:
```
wojtek@precision -> pip uninstall pynamodb
Found existing installation: pynamodb 4.3.1
Uninstalling pynamodb-4.3.1:
  Would remove:
    .venv/lib/python3.8/site-packages/pynamodb-4.3.1-py3.8.egg-info
    .venv/lib/python3.8/site-packages/pynamodb/*
    .venv/lib/python3.8/site-packages/tests/integration/*
```
As you can see, there is extra dependency in `.venv/lib/python3.8/site-packages/tests/integration/*`

**Comment by garrettheel** [comment]
Fixed in #758
