### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by artsiom-tsaryonau** [pynamodb/PynamoDB#783]
I am using `pynamodb 4.3.2` I have the model that looks like this

    class ServiceStateEnum:
        IN_PROGRESS = 'in progress'
        SUCCEEDED = 'succeeded'
        FAILED = 'failed'

    class ServiceOperationEnum:
        PROVISION = "provision"  # create
        DEPROVISION = "deprovision"

    class CloudFoundryEntityAttribute(MapAttribute):
        entity_id = UnicodeAttribute()
        state = UnicodeAttribute()

    class CloudFoundryLastOperationAttribute(MapAttribute):
        name = UnicodeAttribute()
        state = UnicodeAttribute()

    class ServiceStateModel(Model):
        class Meta:
            table_name = Config.AWS_DYNAMODB_TABLE_NAME
            region = Config.AWS_DEFAULT_REGION
            aws_access_key_id = Config.AWS_ACCESS_KEY_ID
            aws_secret_access_key = Config.AWS_SECRET_ACCESS_KEY

        instance_id = UnicodeAttribute(hash_key=True)
        plan_id = UnicodeAttribute()
        service_id = UnicodeAttribute()
        space_id = UnicodeAttribute()
        organization_id = UnicodeAttribute()
        apps = ListAttribute(of=CloudFoundryEntityAttribute)
        services = ListAttribute(of=CloudFoundryEntityAttribute)
        last_operation = CloudFoundryLastOperationAttribute()

However when I try to save it 

        ServiceStateModel(
            instance_id=service_request["instance_id"],
            plan_id=service_request["plan_id"],
            service_id=service_request["service_id"],
            space_id=service_request["space_guid"],
            organization_id=service_request["organization_guid"],
            last_operation={
                'name': ServiceOperationEnum.PROVISION,
                'state': ServiceStateEnum.IN_PROGRESS},
            apps=[],
            services=[]) \
            .save()

I get the error

    File "/.../state.py", line 190, in __provisioning_workflow
        services=[]) \
    File "/usr/local/lib/python3.7/site-packages/pynamodb/models.py", line 409, in save
        data = self._get_connection().put_item(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/pynamodb/connection/table.py", line 139, in put_item
        return_item_collection_metrics=return_item_collection_metrics)
    File "/usr/local/lib/python3.7/site-packages/pynamodb/connection/base.py", line 967, in put_item
        return_item_collection_metrics=return_item_collection_metrics
    File "/usr/local/lib/python3.7/site-packages/pynamodb/connection/base.py", line 859, in get_operation_kwargs
        operation_kwargs.update(self.get_identifier_map(table_name, hash_key, range_key, key=key))
    File "/usr/local/lib/python3.7/site-packages/pynamodb/connection/base.py", line 784, in get_identifier_map
        return tbl.get_identifier_map(hash_key, range_key=range_key, key=key)
    File "/usr/local/lib/python3.7/site-packages/pynamodb/connection/base.py", line 207, in get_identifier_map
        self.hash_keyname: {
    File "/usr/local/lib/python3.7/site-packages/pynamodb/connection/base.py", line 101, in hash_keyname
        for attr in self.data.get(KEY_SCHEMA):
    TypeError: 'NoneType' object is not iterable

I was trying to put some stubs in the lists but still got the same errors.

        ServiceStateModel(
            instance_id=service_request["instance_id"],
            plan_id=service_request["plan_id"],
            service_id=service_request["service_id"],
            space_id=service_request["space_guid"],
            organization_id=service_request["organization_guid"],
            last_operation={
                'name': ServiceOperationEnum.PROVISION,
                'state': ServiceStateEnum.IN_PROGRESS},
            # workaround for not allowing empty lists in DynamoDB
            apps=[CloudFoundryEntityAttribute(entity_id='stub', state='stub')],
            services=[CloudFoundryEntityAttribute(entity_id='stub', state='stub')]) \
            .save()

I also get the same error but on `last_operation` if I remove apss and services.
What is the problem? 

In addition I destroy and create tables during object instationation

        if ServiceStateModel.exists(): 
            ServiceStateModel.delete_table()
        if not ServiceStateModel.exists():
            ServiceStateModel.create_table(
                read_capacity_units=5, write_capacity_units=5, wait=True)

P.s it seems the problem appear from time to time - sometimes there is no error, sometimes there is an error

**Comment by ikonst** [comment]
Hm, I don't see anything immediately wrong.

**Comment by artsiom-tsaryonau** [comment]
@ikonst should I always instantiate attributes by class constructor? can I do it as a basic map?

**Comment by ikonst** [comment]
Maybe the fact you delete and re-create tables has something to do with it. The code currently relies on being able to do DescribeTable to get the schema, and perhaps that's not immediately available (though it'll be strange for us not to surface an error in DescribeTable if we get one).

I didn't trace through the code to see if it could cause the issue you're seeing.

What kind of application do you have? A web worker?

**Comment by ikonst** [comment]
> Should I always instantiate attributes by class constructor?

I believe that's the supported way.

**Comment by artsiom-tsaryonau** [comment]
@ikonst service broker

The thing is that in my workflow - as the service broker is being developed - I often stop the app using CTRL+C and run immediately. So probably on the normal runs, it will work fine as for example I sometimes get errors that it fails to delete table etc.

As I get the issue from time to time I thought that maybe some data is being corrupted as currently, I do know enough about custom attributes, so maybe I designed them wrong or something. For me, ideally, I would like to have the dynamic attribute keys - basically, store in`services` and `apps` list of maps instead of entities.

**Comment by ikonst** [comment]
What I'm suspecting is that your deleting and creating the table is happening in parallel with your broker already serving requests. You must of course wait for the new table to be created before giving your broker any opportunity to serve requests.

**Comment by artsiom-tsaryonau** [comment]
I added `sleep` in after table delete and creation and haven't run into `NoneType` attribute issue as of yet. 
Thanks!
