### ISSUE TITLE
What s the role of read_capacity_units when reading from an existing table?

### ISSUE THREAD

**Issue by xanguera** [pynamodb/PynamoDB#790]
Hi,
I have an existing table I created manually. Using pynamoDB I want to read from this table and so I create a model and add the read_capacity_units.
I have not seen it written anywhere, but it looks like the value I define here matters a lot on the throughout I get. 
I would like to confirm whether pynamodb constraints the reads/writes to the capacity defined in these variables, even though the original table might not have the same capacity set?

**Comment by ikonst** [comment]
Those capacities only affect creating new tables and indices. Annoyingly enough PynamoDB makes you have them even if you create your tables some other way, but you can keep it at e.g. `read/write_capacity_units = 1` without any ill effect.
