### ISSUE TITLE
Empty String/Binary values support?

### ISSUE THREAD

**Issue by nekonoshiri** [pynamodb/PynamoDB#804]
DynamoDB recently supported empty values for _non-key_ String/Binary attributes.

Though PynamoDB currently supports empty value as null (None), 
does PynamoDB have any plans to support this new feature of DynamoDB?

**Comment by jpinner-lyft** [comment]
addressed in https://github.com/pynamodb/PynamoDB/pull/830

**Comment by nekonoshiri** [comment]
Thank you!
