### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'instance_id'

### ISSUE THREAD

**Issue by Tristanbox09** [pynamodb/PynamoDB#805]
Hello, I am getting this error and I do not know why:
` File "C:\Users\Owner\Desktop\Ubotica\cloud_detect\venv\lib\site-packages\sentinelhub\ogc.py", line 369, in __init__
     super().__init__(**kwargs)
 TypeError: __init__() got an unexpected keyword argument 'instance_id'`

Does anyone know how to fix this error or what the issue is? My code is below! Thank you!

`class WebFeatureService(OgcService):
    """ Class for interaction with Sentinel Hub WFS service

    The class is an iterator over info data of all available satellite tiles for requested parameters. It collects data
    from Sentinel Hub service only during the first iteration. During next iterations it returns already obtained data.
    The data is in the order returned by Sentinel Hub WFS service.
    """
    def __init__(self, bbox, time_interval, *, data_source=DataSource.SENTINEL2_L1C, maxcc=1.0, **kwargs):
        """
        :param bbox: Bounding box of the requested image. Coordinates must be in the specified coordinate reference
            system.
        :type bbox: geometry.BBox
        :param time_interval: interval with start and end date of the form YYYY-MM-DDThh:mm:ss or YYYY-MM-DD
        :type time_interval: (str, str)
        :param data_source: Source of requested satellite data. Default is Sentinel-2 L1C data.
        :type data_source: constants.DataSource
        :param maxcc: Maximum accepted cloud coverage of an image. Float between 0.0 and 1.0. Default is 1.0.
        :type maxcc: float
        :param config: A custom instance of config class to override parameters from the saved configuration.
        :type config: SHConfig or None
        """
        super().__init__(**kwargs)

        self.bbox = bbox
        self.time_interval = parse_time_interval(time_interval)
        self.data_source = data_source
        self.maxcc = maxcc

        self.tile_list = []
        self.index = 0
        self.feature_offset = 0
        self.latest_time_only = time_interval == SHConstants.LATEST
        self.max_features_per_request = 1 if self.latest_time_only else SHConfig().max_wfs_records_per_query

    def __iter__(self):
        """ Iteration method

        :return: iterator of dictionaries containing info about product tiles
        :rtype: Iterator[dict]
        """
        self.index = 0
        return self`

**Comment by ikonst** [comment]
This doesn't seem to involve PynamoDB.
