### ISSUE TITLE
Question to TransactWrite

### ISSUE THREAD

**Issue by patrickwerz** [pynamodb/PynamoDB#809]
Hi guys, 
I try to create 2 new items in different tables. The process should fail if one item can't be created. I tried the following code 

>     connection = Connection()
>     reg_item = _create_asset_registrations_model_from_event(event)
>     md_item = _create_asset_master_data_model_from_registration_model(reg_item)
>     with TransactWrite(connection=connection) as transaction:
>         transaction.save(reg_item)
>         transaction.save(md_item)
>     return reg_item

The first *.save(*) method was ok, the second one throwed a TransactWriteError Exception. 

`'An error occurred (ResourceNotFoundException) on request (27D2HSHEKVJ6BGV6CCK5N4US6NVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (None) when calling the TransactWriteItems operation: Requested resource not found'`

Do you have an idea what the problem is? If I save() each model instance individually (without TransactWrite) the items are created on dynamo.
Thanks in advance,
Patrick

**Comment by ikonst** [comment]
Are you creating the tables shortly before performing the transaction, e.g. as part of some test boostrap?

**Comment by patrickwerz** [comment]
The tables have been created via serverless. The model that fails has also an gsi - if that matters in any case.

**Comment by patrickwerz** [comment]
I found the error:
I need to provide the correct region in the connection class 
> connection = Connection(region=os.environ['aws_region'])
