### ISSUE TITLE
Can't query by date: 'Comparison' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by vedmant** [pynamodb/PynamoDB#822]
Hi, I'm trying to get all items that were created for last 24 hours, here is my models and query

```python
class CreatedDateIndex(GlobalSecondaryIndex):
    class Meta:
        index_name = 'createdDateIndex'
        projection = AllProjection()
        write_capacity_units = 100
        read_capacity_units = 100
    createdDate = UTCDateTimeAttribute(hash_key=True)

class CommentModel(Model):
    class Meta:
        table_name = COMMENTS_TABLE_NAME
        write_capacity_units = 100
        read_capacity_units = 100

    ideaId = UnicodeAttribute(hash_key=True)
    commentId = UnicodeAttribute(hash_key=True)
    createdDate = UTCDateTimeAttribute(null=True)
    body = UnicodeAttribute(null=True)
    ideaOwnerId = UnicodeAttribute(null=True)
    userId = UnicodeAttribute(null=True)
    userName = UnicodeAttribute(null=True)
    userSlug = UnicodeAttribute(null=True)

    createdDateIndex = CreatedDateIndex()


now = datetime.now()
dayAgo = datetime.now() - timedelta(days=1)

comments_iterator = CommentModel.createdDateIndex.query(CommentModel.createdDate >= dayAgo)
```

And I have following error:
```
AttributeError: 'Comparison' object has no attribute 'tzinfo'
```

**Comment by ikonst** [comment]
@vedmant The first argument to the `Index.query` method is a hash key value, not a condition. Furthermore, DynamoDB doesn't allow hash key conditions. The reason is that a hash key is the shard key so there's no efficient way to do what you're doing, i.e. what you're trying to do is as efficient as scanning.

Try creating a GSI where createdDate is a range key and use a range key condition.

**Comment by vedmant** [comment]
@ikonst Thanks for explanation, but I need to select all comments that created in last 24 hours, there is no other key I can use for hash key as I need to just select all records. Then there is no way to do this, unless I create another field with the same value for whole table and use it as hash key plus date as a range key?

**Comment by ikonst** [comment]
Pretty much. You can't shard that operation so you'll be effectively querying a single shard.

At this point it's worth asking the higher level question: what you're building? If it's really "I need a web site where a human can see the exact latest ten comments at any given time" then yes, that's what you'd do.

Will this result in a "hot shard"? Think of it this way, by the time your number of comments per second outgrows a single DynamoDB's shard -- let's say you're amazon.com and those are the comments on Amazon products -- the query for the true latest N comments couldn't be meaningful to a human anymore as you're adding hundreds of comments per second.

**Comment by ikonst** [comment]
Pretty much. You can't shard that operation so you'll be effectively querying a single shard.

At this point it's worth asking the higher level question: what you're building? If it's really "I need a web site where a human can see the exact latest ten comments at any given time" then yes, that's what you'd do.

Will this result in a "hot shard"? Think of it this way, by the time your number of comments per second outgrows a single DynamoDB's shard -- let's say you're amazon.com and those are the comments on Amazon products -- the query for the true latest N comments couldn't be meaningful to a human anymore as you're adding hundreds of comments per second.

**Comment by vedmant** [comment]
@ikonst Thanks, that's very helpful. Closing this issue then.
