### ISSUE TITLE
automatic terraform generation

### ISSUE THREAD

**Issue by abe-winter** [pynamodb/PynamoDB#832]
I'm using terraform to manage my dynamo tables, and generating the terraform automatically from pynamodb models.

Should I submit a PR merging the terraform generation? Or is this outside the scope of pynamodb.

**Comment by ikonst** [comment]
IMHO this could very well be a small project that builds on top of PynamoDB rather than something integrated into PynamoDB.

**Comment by abe-winter** [comment]
yup, makes sense

**Comment by abe-winter** [comment]
terraform generator shared here if useful:

https://github.com/abe-winter/pynamotf
