### ISSUE TITLE
graceful filter_key handling conflicts with is_range_key_valid, throws wrong error

### ISSUE THREAD

**Issue by abe-winter** [pynamodb/PynamoDB#844]
This is happening in 4.3.3 but it looks like all the relevant code has been refactored on master; sorry in advance if this is a stale report.

I used an `is_in()` condition for a range key, which isn't allowed. This created a chain of events that raised the `'filter_condition' cannot contain key attributes` error, which is not the right error for this case.

First my `range_key_condition` failed the validity test here:
https://github.com/pynamodb/PynamoDB/blob/4.3.3/pynamodb/expressions/condition.py#L20

This caused the `query()` method to swap `range_key_condition` and `filter_key_condition` here:
https://github.com/pynamodb/PynamoDB/blob/4.3.3/pynamodb/connection/base.py#L1232

And then the new `filter_key_condition` failed a test and threw the error:
https://github.com/pynamodb/PynamoDB/blob/4.3.3/pynamodb/connection/base.py#L1247

Ideally the error would say 'invalid range key condition' or something.

I'm happy to pitch in with a PR if useful.

**Comment by ikonst** [comment]
Thanks, this was resolved in https://github.com/pynamodb/PynamoDB/pull/798. Agree it was super-confusing.

**Comment by abe-winter** [comment]
Thank you!
