### ISSUE TITLE
How to update dynamic attribute changes?

### ISSUE THREAD

**Issue by burritoIand** [pynamodb/PynamoDB#845]
Hello, in the past I could do this to update dynamic attributes:
```
        update_params = {k: {'action': 'put', 'value': v}
                         for (k, v) in data.items()}
        if update_params:
            user.update(update_params)
```
However when I try to do that now, I get the error `TypeError("the value of `actions` is expected to be a non-empty list")`
(https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/models.py#L415)

How can I update multiple dynamic attributes at once with current version?

**Comment by jpinner-lyft** [comment]
Starting with the v4.0.0 release, you need to use the expression syntax to create a list of actions. Dynamic attributes are supported through the `Path` operand (statically defined attributes provider "pythonic" methods for creating these based on the attribute names). Note that when creating Path instances manually, the input value will be broken down into segments based on DynamoDB's syntax: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Attributes.html
```
from pynamodb.expressions.operand import Path

actions = [Path(k).set(v) for (k, v) in data.items()]
if actions:
    user.update(actions)
```

**Comment by burritoIand** [comment]
ok great thanks @jpinner-lyft
