### ISSUE TITLE
Add typing

### ISSUE THREAD

**Issue by ikamensh** [pynamodb/PynamoDB#854]
Hello, thanks for this library!

While going through tutorials I've noticed that typing is not added. Do you consider it's OK to add  typing, e.g. as `foo(arg: List[str]) -> "Type"` as that would be compatible with python3.6 ?

I would also contribute a PR or two, but this is only practical to do partially imo - converting entire library at once is huge amount of work.

**Comment by ikonst** [comment]
We have _some_ typing but definitely should add some more :)

**Comment by ikamensh** [comment]
oh, I was looking at the release 4.3.3, indeed much more typing since then :) will make a PR if I'll find anything obvious missing.
