### ISSUE TITLE
pynamodb.exceptions.TableError

### ISSUE THREAD

**Issue by KapilVijay28** [pynamodb/PynamoDB#856]
**Error:**
> pynamodb.exceptions.TableError: Failed to create table: An error occurred (UnrecognizedClientException) on request (ABB7UEGGG************************************66Q9ASUAAJG) on table (logging) when calling the CreateTable operation: The security token included in the request is invalid.

Code Snippet:
```
self.client = Connection()

logging_table = self.client.create_table(
                table_name="logging",
                attribute_definitions=[
                    {
                    "AttributeName": "call_id",
                    "AttributeType": "S"
                    },
                    {
                    "AttributeName": "service_name",
                    "AttributeType": "S"
                    },
                    {
                    "AttributeName": "method_name",
                    "AttributeType": "S"
                    },
                    {
                    "AttributeName": "status",
                    "AttributeType": "S"
                    },
                    {
                    "AttributeName": "start",
                    "AttributeType": "S"
                    }
                ],
                key_schema=[
                    {
                    "AttributeName": "call_id",
                    "KeyType": "HASH"
                    }
                ]
            )
            item = {
                'call_id': call_id,
                'service_name': service_name,
                'method_name': method_name,
                'status': 'PENDING',
                'start': self.logs[worker_ctx]
            }

            logging_insert = self.client.put_item(
                table_name='logging', 
                item=item
            )
```

I am using [DynamoDB-local](https://hub.docker.com/r/amazon/dynamodb-local/) and executing it using docker locally. I have used 'dummy' values for the `aws configure` command. I think for dynamodb-local we don't need actual AWS key_id & secret_key. 

Could anyone please help?

**Comment by KapilVijay28** [comment]
@mattjegan @venkateshanbalagan

Could you guyz help?

**Comment by alivcor** [comment]
@KapilVijay28 you do need to provide the hostname as in `http://localhost:8000` - if not probably it will go check your locally configured aws credentials

**Comment by garrettheel** [comment]
@alivcor is correct -- you need to configure the hostname when you instantiate the `Connection`. https://pynamodb.readthedocs.io/en/latest/local.html discusses this, though at the `Model` level so you'll need to adjust for `Connection`
