### ISSUE TITLE
Throttles do not distinguish between read and write operations

### ISSUE THREAD

**Issue by danielhochman** [pynamodb/PynamoDB#86]
Since read and write are provisioned separately, it does not make sense for the throttle code to treat them as a single pool.

**Comment by joshowen** [comment]
Out of curiosity, does anyone use the throttle feature?  If so, how?  Are there a fixed number of processes running?

**Comment by danielhochman** [comment]
Consumption tracking was a great idea but with a limited implementation.

I really want to add some kind of event bus, where you can hook into events within Pynamo and have it fire custom handlers with the result on it's way back to the caller.

You could use the event bus to send consumption stats to graphite for alerting and monitoring. You could also implement global throttling by persisting the consumption count to a centralized Redis. You can instrument per-call latency to the DynamoDB API, before parsing and other processing.

The possibilities are endless. I've hacked in some of these changes to our own code by subclassing and patching, but it's no substitute for a real event bus. I haven't had time to start sketching it out in the code unfortunately.
