### ISSUE TITLE
Issues with refresh() and update() when using Model Discriminators

### ISSUE THREAD

**Issue by dustymugs** [pynamodb/PynamoDB#879]
Small contained test case. I am using dynamodb-local so I hope that's not the problem...

```
from pynamodb.attributes import (
    DiscriminatorAttribute,
    UnicodeAttribute,
)
from pynamodb.models import Model

class ParentModel(Model):
    class Meta:
        table_name = 'polymorphic_table'
        write_capacity_units = 1
        read_capacity_units = 1

    id = UnicodeAttribute(hash_key=True)
    cls = DiscriminatorAttribute()

class FooModel(ParentModel, discriminator='Foo'):
    foo = UnicodeAttribute()

class BarModel(ParentModel, discriminator='Bar'):
    bar = UnicodeAttribute()

# dynamodb-local
ParentModel.Meta.host = 'http://172.17.0.4:8000'

if ParentModel.exists():
    ParentModel.delete_table()
ParentModel.create_table(wait=True)

bar = BarModel(id='Hello', bar='World!')

bar.save()
bar.refresh() # boom
```

**Comment by dustymugs** [comment]
Tested with AWS dynamo instead of dynamo-local and seeing the same error...

```bug.py
from pynamodb.attributes import (
    DiscriminatorAttribute,
    UnicodeAttribute,
)
from pynamodb.models import Model

class ParentModel(Model):
    class Meta:
        table_name = 'test_pynamo_polymorphic_table'
        write_capacity_units = 1
        read_capacity_units = 1

    id = UnicodeAttribute(hash_key=True)
    cls = DiscriminatorAttribute()

class FooModel(ParentModel, discriminator='Foo'):
    foo = UnicodeAttribute()

class BarModel(ParentModel, discriminator='Bar'):
    bar = UnicodeAttribute()

def do_it():
    if ParentModel.exists():
        ParentModel.delete_table()
    ParentModel.create_table(wait=True)

    bar = BarModel(id='Hello', bar='World!')

    bar.save()
    bar.refresh() # boom

if __name__ == '__main__':
    # dynamodb-local
    #ParentModel.Meta.host = 'http://172.17.0.4:8000'

    try:
        do_it()
    finally:
        if ParentModel.exists():
            ParentModel.delete_table()
```

```
Traceback (most recent call last):
  File "bug.py", line 37, in <module>
    do_it()
  File "bug.py", line 30, in do_it
    bar.refresh() # boom
  File "/opt/conda/lib/python3.8/site-packages/pynamodb/models.py", line 456, in refresh
    self.deserialize(item_data)
  File "/opt/conda/lib/python3.8/site-packages/pynamodb/attributes.py", line 371, in deserialize
    setattr(self, name, value)
  File "/opt/conda/lib/python3.8/site-packages/pynamodb/attributes.py", line 425, in __set__
    raise TypeError("'{}' object does not support item assignment".format(self.__class__.__name__))
TypeError: 'DiscriminatorAttribute' object does not support item assignment

```

**Comment by jpinner-lyft** [comment]
@dustymugs thanks for the bug report

The issue here seems to be that `refresh()` and `update()` call `deserialize()` directly and fail when deserializing the discriminator. Normally `_instantiate` is called when reading without an existing item which removes the discriminator attribute.

**Comment by jpinner-lyft** [comment]
@dustymugs I've linked a possible fix -- it only supports `refresh` right now and not `update` but take a look and let me know if that addresses your issue.

**Comment by dustymugs** [comment]
@jpinner-lyft Yes, that fixed the `refresh()` case. For me, the `update()` case was the main case and then I stumbled across the `refresh()` case

**Comment by dustymugs** [comment]
I was thinking that maybe it'd be easier (don't know about better) if `__set__()` for DiscriminatorAttribute just validated that the value internally matches the value passed by `setattr`

**Comment by jpinner-lyft** [comment]
@dustymugs I've added another commit to the linked PR to perform the same logic on update

I'll look at modifying `__set__` but I'm not sold on it. It could make this case easier but we probably should be validating that the item matches the data model when using discriminators.

**Comment by dustymugs** [comment]
@jpinner-lyft yep... that change fixes `update()` case as well

**Comment by jpinner-lyft** [comment]
@dustymugs I took your advice and updated the PR to allow setting discriminator attributes to their instance type. Would you mind retesting to change?

**Comment by dustymugs** [comment]
@jpinner-lyft eek... can't say my advice is ever safe ;-). Tested the bug script from above and longer full lifecycle script with both dynamodb-local and aws with zero issues.
