### ISSUE TITLE
Is it possible to implement ScanIndexForward for scan operation also ? 

### ISSUE THREAD

**Issue by dimavitvickiy** [pynamodb/PynamoDB#885]
https://github.com/pynamodb/PynamoDB/blob/b10da8e3d58d22abd70a4bdb3d6a2c526168c700/pynamodb/models.py#L666

**Comment by ikonst** [comment]
@dimavitvickiy I don't see this option in [DynamoDB's documentation for Scan](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html)

**Comment by dimavitvickiy** [comment]
Yes, you are correct, my mistake, wrongly read the docs.
