### ISSUE TITLE
_fast_parse_utc_date_string fails on pre year 1000

### ISSUE THREAD

**Issue by l0b0** [pynamodb/PynamoDB#899]
Python `datetime` supports dates back to year 0, but `_fast_parse_utc_date_string` forces datetimes to have four digit years. This resulted in the following error:

> ValueError: Datetime string '539-02-20T08:36:49.000000+0000' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

`_fast_parse_utc_date_string` should fall back to a library call if it fails.

Edit:

My bad, looks like `datetime.datetime.strptime('539-02-20T08:36:49.000000+0000', '%Y-%m-%dT%H:%M:%S.%f%z')` also fails, meaning `isoformat()` doesn't produce parseable datetimes. :/

**Comment by l0b0** [comment]
On the other hand, it looks like [this](https://github.com/linz/geospatial-data-lake/pull/222/checks?check_run_id=1859524592) happens when trying to run a [simple loop](https://github.com/linz/geospatial-data-lake/blob/b4dad161f5ea1e5d7a41e91986a5f2672352b45a/datalake/backend/endpoints/datasets/get.py#L105) over a query of a [model with a `UTCDateTimeAttribute`](https://github.com/linz/geospatial-data-lake/blob/b4dad161f5ea1e5d7a41e91986a5f2672352b45a/datalake/backend/endpoints/datasets/model.py#L54). So it looks like the issue is with pynamodb, not the application code. Sorry for the flip-flopping.

**Comment by ikonst** [comment]
Thanks, it does make sense to either call `strptime` when `len(date_string) != 31` or perhaps pad with zeros?
```python
length = len(date_string)
if 27 < length < 31:
  date_string = '0' * (31 - length) + date_string
```

**Comment by ikonst** [comment]
@l0b0 Can you provide a sample of the data you're deserializing and perhaps where it's coming from?

btw, your `created_at` appears to be stuck at load time:
```
created_at = UTCDateTimeAttribute(null=False, default=datetime.now(timezone.utc))
```
you probably meant to do:
```
created_at = UTCDateTimeAttribute(null=False, default=lambda: datetime.now(timezone.utc))
```

**Comment by l0b0** [comment]
@ikonst I don't have specific data, because I'm generating random datetimes for tests in the `Dataset` class in datalake/backend/tests/utils.py.

**Comment by ikonst** [comment]
Yeah. It's just that I tried it now myself and UTCDateTimeAttribute seems to encode pre-1000 years as YYYY padded with zeroes, so it should encode and decode well.

**Comment by l0b0** [comment]
If you want to reproduce yourself, you could try with https://github.com/linz/geospatial-data-lake/pull/64, but it's not exactly simple:

1. Check out that branch
2. Build and deploy the AWS resources (see README.md)
3. Run the tests (see .github/workflows/test.yml). Each run has at least a 75% chance of failing, but you might have to try with more than one random seed.

**Comment by ikonst** [comment]
Can you explain a little bit more what it does? Does it write to DynamoDB through some other means? Does it deal with existing data?

**Comment by l0b0** [comment]
For padding, you could use `value.zfill(31)`.

**Comment by l0b0** [comment]
I got everything working by holding back pynamodb to version 4.3.3. I'll try upgrading pynamodb to 5.0.3 and report back.

**Comment by ikonst** [comment]
Padding isn't the challenge. The problem is that I could not understand how the issue can be reproduced. I'd like to add a regression test.

**Comment by l0b0** [comment]
From the above it looks like `UTCDateTimeAttribute._fast_parse_utc_date_string("539-02-20T08:36:49.000000+0000")` would be a useful test - it currently throws an exception.

**Comment by ikonst** [comment]
@l0b0 it's well understood why it fails to parse that string, but this is an internal method.

The rationale for that method not having to support 3-digit years is because we always serialize years as zero-padded 4 digit. We "fix" that function to parse 3-digit years, but it means we have a lurking bug somewhere else that causes 3-digit years to be written in the first place.

**Comment by l0b0** [comment]
I'm going to have to see if I have time to look into this; it's a work project. I've worked around it by changing `any_past_datetime` to return only datetimes back to year 1049. Unfortunately GitHub seems to throw away Actions output, so I can't even see the original test output as linked above.

**Comment by stoppablemurph** [comment]
The way [UTCDateTimeAttribute serializes datetimes](https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/attributes.py#L688) with < 4 digit years doesn't pad in zeros as far as I can tell.

Example copy/pasting the logic:
```In [78]: test_date                                                                                                                                                                          
Out[78]: datetime.datetime(1, 1, 1, 0, 0, 0, 1, tzinfo=datetime.timezone.utc)

In [79]: test_date.astimezone(tzutc()).strftime('%Y-%m-%dT%H:%M:%S.%f%z')                                                                                                                   
Out[79]: '1-01-01T00:00:00.000001+0000'
```

If I set an item with a datetime attribute to a datetime with a < 4 digit year, it serializes (and saves) like this without error:
```
In [81]: obj.serialize()                                                                                                                                                                    
Out[81]: 
{'id': {'S': 'b1900ca1-896f-445a-98b6-f2eaf7be8e17'},
 'timestamp': {'S': '1-01-01T00:00:00.000000+0000'},
 'name': {'S': 'test'},
 'version': {'N': '34'}}

In [82]: obj.save()                                                                                                                                                                         
Out[82]: {'ConsumedCapacity': {'CapacityUnits': 1.0, 'TableName': 'test-table'}}
```

But then if I attempt to refresh the item:
```
In [83]: obj.refresh()                                                                                                                                                                      
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/<redacted>/lib/python3.6/site-packages/pynamodb/attributes.py in _fast_parse_utc_date_string(date_string)
    701                     or date_string[19] != '.' or date_string[26:31] != '+0000'):
--> 702                 raise ValueError("Datetime string '{}' does not match format '{}'".format(date_string, DATETIME_FORMAT))
    703             return datetime(

ValueError: Datetime string '1-01-01T00:00:00.000000+0000' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

[Python strftime documentation](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) indicates `%Y` doesn't include padding for years prior to 1000.

It looks like `UTCDateTimeAttribute.serialize` [has been *not* padding zeros since April 2017](https://github.com/pynamodb/PynamoDB/commit/3112092008ab98d5396fa745ac4b654bd1f2f674#diff-036d5fdbbcdad0183d26970d7632121a91726f121c4a1cfc05232826a36d32e5L387-R390) when Delorean was replaced.

```
In [8]: test_date
Out[8]: datetime.datetime(1, 1, 1, 0, 0, 0, 1, tzinfo=datetime.timezone.utc)

In [9]: Delorean(test_date, timezone="UTC").datetime.strftime("%Y-%m-%dT%H:%M:%S.%f%z")
Out[9]: '0001-01-01T00:00:00.000001+0000'
```

**Comment by ikonst** [comment]
Yikes, you're right. This is apparently platform dependent too: https://bugs.python.org/issue13305

**Comment by ikonst** [comment]
@l0b0 Apologize for my lack of faith. Took me getting a Docker image of a random Python version on a random Linux to witness this myself.

**Comment by l0b0** [comment]
No worries @ikonst; I would be really sceptical too. It's kinda unbelievable that that bug has survived ten years already.
