### ISSUE TITLE
Running queries

### ISSUE THREAD

**Issue by jhmartin** [pynamodb/PynamoDB#902]
The documentation indicates that queries are done in this syntax:
```
for item in Thread.query('ForumName', thread__begins_with='mygreatprefix'):
```

However that results in a NameError.

The test cases use an alternate format:
```
    for item in TestModel.query('setitem', TestModel.thread.startswith('set')):
```
which works. Am I missing something about how the query syntax functions?

pynamodb==5.0.0
Python 3.8.3
DDB is amazon/dynamodb-local:latest

**Comment by ikonst** [comment]
This looks like old documentation. Can you provide a link?

**Comment by jhmartin** [comment]
Ohhh google failed me and sent me to 0.1.0, disregard.
