### ISSUE TITLE
Incomplete Typing with Transaction context managers

### ISSUE THREAD

**Issue by prestomation** [pynamodb/PynamoDB#916]
In my project, I use transactions with context managers like:

```
with TransactWrite(...) as transaction:
   transaction.save(...)
   transaction.save(...)
```

The typing is incomplete, as TransactWrite::__enter__ is just `Transaction::__enter__` and returns `Transaction`: https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/transactions.py#L25

For this reason, mypy does not understand the `save()` method as above, as this is not part of the Transaction base class.

Potentially relevant: Mypy didn't used to complain about this, but it does now that I've upgraded to 0.782.

**Comment by ikonst** [comment]
Agree, should be probably better with a [generic self](https://mypy.readthedocs.io/en/stable/generics.html#generic-methods-and-generic-self):
```python
TTransaction = TypeVar('TTransaction', bound=Transaction)

class Transaction:
     ...
    def __enter__(self: T) -> T:
        return self
```

Care submitting a PR? Also might warrant adding a test case to test_mypy.py.
