### ISSUE TITLE
Combine Index Queries

### ISSUE THREAD

**Issue by markatcody** [pynamodb/PynamoDB#958]
Is there a way to combine index query conditions?

```python
queries = MyModel.index_a.query(1) & MyModel.index_b.query(2)
for q in queries:
   ...
```

**Comment by ikonst** [comment]
```python
import itertools

queries = MyModel.index_a.query(1), MyModel.index_b.query(2)
for q in itertools.chain(*queries):
   ...
```

(There's nothing intrinsic to DynamoDB for batching queries, as far as I'm aware.)

**Comment by markatcody** [comment]
I might have seen a Java implementation somewhere in SO. Now I just got to find it.

**Comment by markatcody** [comment]
@ikonst 
Yeah I think it's not possible. Thanks for the clarification. https://stackoverflow.com/questions/17663695/is-there-a-way-to-query-multiple-hash-keys-in-dynamodb.
