### ISSUE TITLE
None value for sets and json attributes shouldn't return None

### ISSUE THREAD

**Issue by ryan-lane** [pynamodb/PynamoDB#96]
```
myobj = Myobj(
     id=id,
     listAttr=[]
 ).save()
print type(myobj.listAttr)
<type 'NoneType'>
```

It's really difficult to work with models when the type of the data being passed in doesn't match the data fetched. This occurs whether or not null=True is used. The only way to get around this is to create a custom attribute and override the internal __get__ function, which feels fragile.

**Comment by jlafon** [comment]
@ryan-lane what behavior would you expect in this case?

**Comment by zbyte64** [comment]
I would expect myobj.listAttr to be an empty list.

**Comment by ryan-lane** [comment]
Same

**Comment by ryan-lane** [comment]
Basically, I expect whatever I set as the default to be the attribute I get back, if no value is provided.

**Comment by jpinner-lyft** [comment]
Verified that this has been fixed on latest version of PynamoDB:
```
>>> class MyObj(Model):
...     id = UnicodeAttribute(hash_key=True)
...     listAttr = ListAttribute(null=True)
... 
>>> myobj = MyObj(id='id', listAttr=[])     
>>> myobj.save() 
{}
>>> print(type(myobj.listAttr))
<type 'list'>
>>> myobj.refresh()
>>> print(type(myobj.listAttr))
<type 'list'>
>>> myobj = MyObj.get('id')
>>> print(type(myobj.listAttr))
<type 'list'>
```
