### ISSUE TITLE
Pynamodb query index filtering contains list

### ISSUE THREAD

**Issue by kimletsdelivery** [pynamodb/PynamoDB#971]
Hello, I'm facing an issue which is, my index query is a list of id's, but also, on my filter_conditions, I would like to query by a list...Couldn't find any solution...
It would be something like this:
```
list_ids = ['first', 'second']
list_filters = ['city_one', 'city_two', 'city_three']
response = []

for ids in list_ids:
    response.append(Model.attribute_index.query(ids, filter_condition=(Model.attribute.contains(list_filters)))
```

I really don't want to use scan for such but this is getting quite complex since I have other filter conditions as well besides the one I want to search by list on contains or is_in...

Any thoughts? Thank you in advance

**Comment by ikonst** [comment]
> my index query is a list of id's

The Query method in DynamoDB accepts just a single item for the partition key, so you probably mean to use BatchGet (aka "batch_get" in PynamoDB)?

**Comment by kimletsdelivery** [comment]
makes sense.. but I couldn't find on the doc batch get on table indexes ? Is there a way to do a query get batch for index?

**Comment by ikonst** [comment]
I guess it's not possible :| Perhaps just make multiple calls in parallel? That's probably what happens behind the scenes for BatchGetItems since it should be hitting different partitions.

**Comment by kimletsdelivery** [comment]
My solution for whom may interest:
So I wouldn't have two iterators list as my response, I did this workaround, probably not the ideal but it works...

```
list_ids = ['first', 'second']
list_filters = ['city_one', 'city_two', 'city_three']
response = []
r_batch = []

for ids in list_ids:
    r_batch = Model.attribute_index.query(ids, filter_condition=(Model.attribute.is_in(*list_filters))
    for resp in r_batch:
                    response.append(resp)

return response
```
