### ISSUE TITLE
batch_write not respecting 25 WCU 

### ISSUE THREAD

**Issue by sofialunkes** [pynamodb/PynamoDB#973]
Hello,

I'm using pynamodb to load a csv file with two columns and save in dynamodb.
When I try to use:
``` python
with Thread.batch_write() as batch:
  for row in csv.DictReader(codecs.getreader("utf-8")(__object_file)):
      items.append(HighChurn(row['firstColumn'], row['secondColumn']))
  for item in items:
      batch.save(item)
```
in a file that contains 300k lines, it returns an error with following message:

> pynamodb.exceptions.PutError: Failed to batch write items: An error occurred (ProvisionedThroughputExceededException) on request (<random id here>) on table (thread-table) when calling the BatchWriteItem operation: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.

Wasn't suppossed to batch_write command deal with provisioned throughput?

**Comment by garrettheel** [comment]
The [DynamoDB docs ](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) discuss why batch write does not help you here:

> Parallel processing reduces latency, but each specified put and delete request consumes the same number of write capacity units whether it is processed in parallel or not. Delete operations on nonexistent items consume one write capacity unit.

You'll need to either raise your provisioned throughput or write slower.
