### ISSUE TITLE
Need type annotation for ListAttribute, MapAttribute

### ISSUE THREAD

**Issue by mhihasan** [pynamodb/PynamoDB#978]
I am using python 3.9 type annotation with pynamodb installed.
But, I am getting errors while running `mypy` incase of `ListAttribute`,`MapAttribute`
How could I fix this type error?

Thanks

**Comment by garrettheel** [comment]
Please provide enough information to reproduce your issue. Version of pynamodb, sample code, error output etc.

**Comment by mhihasan** [comment]
Suppose, `example.py` Contains.
```python
class A(Model):
    class Meta:
        write_capacity_units = 1
        read_capacity_units = 1

    b = ListAttribute(default=list, null=False)
    c = MapAttribute(default=dict)

```
If I run `mypy sample.py`, I am getting the following errors:
```bash
 Need type annotation for "b"
 Need type annotation for "c"
```

With:
pynamodb==5.1.0
mypy==0.910

**Comment by garrettheel** [comment]
@mhihasan your best bet for now would be to declare the attribute type explicitly, e.g

```
b: ListAttribute[str] = ListAttribute(default=list, null=False)
c: MapAttribute[str, int] = MapAttribute(default=dict)
```

Note that pynamodb will not check this type at runtime, but it will allow mypy to catch errors.

https://pynamodb.readthedocs.io/en/latest/attributes.html#list-attributes describes how you can use the `of=` argument when you're sticking in a `MapAttribute` subclass, but this doesn't currently work for basic types

**Comment by hanzheliva** [comment]
Hi @garrettheel  I've tried to declare as you indicated but got errors when running, like
```
TypeError: 'type' object is not subscriptable
```

Could you please help check this?

**Comment by garrettheel** [comment]
@hanzheliva can you open a new issue for your problem and include enough code to reproduce? thanks!
