### ISSUE TITLE
Is there a way to do a upsert MySQL like

### ISSUE THREAD

**Issue by gfonseca** [pynamodb/PynamoDB#988]
Hello every one.
I would like to execute an INSERT or UPDATE like MySQL does.
In case the primary key yet not exists the db must create a new one.
Case it already exists, I want to update just some fields

```sql
INSERT INTO table (id, name, age) VALUES(1, "A", 19) ON DUPLICATE KEY UPDATE  age=19
```

is there a way with just one transaction?

**Comment by ikonst** [comment]
The [UpdateItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) action will create a new item if it doesn't exist (unless you prevent that with a conditional expression).
