### ISSUE TITLE
Query on GSI not respecting polymorphism filter condition

### ISSUE THREAD

**Issue by mstykow** [pynamodb/PynamoDB#992]
Hello everyone! Great library.

The [polymorphism documentation](https://pynamodb.readthedocs.io/en/latest/polymorphism.html) states: "Query and scan operations transparently add a filter condition to ensure that only items with a matching discriminator value are returned."

However, when running a query on a GSI using a child class the filter condition does not seem to be correctly added as I still receive results matching another child class.

Setup:
```
class MyGSI(GlobalSecondaryIndex):
    class Meta:
        index_name = 'foo-index'
        read_capacity_units = 2
        write_capacity_units = 1
        projection = AllProjection()

    modelId = UnicodeAttribute(hash_key=True)

class ParentModel(Model):
    class Meta:
        table_name = 'polymorphic_table'
    id = UnicodeAttribute(hash_key=True)
    modelId = UnicodeAttribute()
    my_gsi = MyGSI()
    cls = DiscriminatorAttribute()

class FooModel(ParentModel, discriminator='Foo'):
    foo = UnicodeAttribute()

class BarModel(ParentModel, discriminator='Bar'):
    bar = UnicodeAttribute()
```

Then

```
FooModel.my_gsi.query(...)
```

will also return results from `BarModel`.

Is there a mistake in my setup or is this a bug?

**Comment by ikonst** [comment]
@jpinner-lyft

**Comment by jpinner-lyft** [comment]
This is a bug.

When `ParentModel` is created, the metaclass sets a property on `my_gsi.Meta`: `my_gsi.Meta.model = ParentModel`.
The GSI query actually calls `FooModel.my_gsi.Meta.model.query(...)`, so the filter condition isn't correctly applied.

We need to change the behavior of the index class to either dynamically determine the model class or copy the attribute to the child class and override the model property.

@ikonst This brings up an interesting edge case btw, what should we do if the discriminator attribute isn't projected into the index?

**Comment by ikonst** [comment]
> This brings up an interesting edge case btw, what should we do if the discriminator attribute isn't projected into the index?

Maybe it's something an "audit_against_table_description" function (to be built :) should check.
